// Code generated by ent, DO NOT EDIT.

package adminconfig

import (
	"gitlens/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLTE(FieldID, id))
}

// OtelEndpoint applies equality check predicate on the "otel_endpoint" field. It's identical to OtelEndpointEQ.
func OtelEndpoint(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldOtelEndpoint, v))
}

// TracesEnabled applies equality check predicate on the "traces_enabled" field. It's identical to TracesEnabledEQ.
func TracesEnabled(v bool) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldTracesEnabled, v))
}

// MetricsEnabled applies equality check predicate on the "metrics_enabled" field. It's identical to MetricsEnabledEQ.
func MetricsEnabled(v bool) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldMetricsEnabled, v))
}

// LogsEnabled applies equality check predicate on the "logs_enabled" field. It's identical to LogsEnabledEQ.
func LogsEnabled(v bool) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldLogsEnabled, v))
}

// LogSeverity applies equality check predicate on the "log_severity" field. It's identical to LogSeverityEQ.
func LogSeverity(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldLogSeverity, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// OtelEndpointEQ applies the EQ predicate on the "otel_endpoint" field.
func OtelEndpointEQ(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldOtelEndpoint, v))
}

// OtelEndpointNEQ applies the NEQ predicate on the "otel_endpoint" field.
func OtelEndpointNEQ(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNEQ(FieldOtelEndpoint, v))
}

// OtelEndpointIn applies the In predicate on the "otel_endpoint" field.
func OtelEndpointIn(vs ...string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldIn(FieldOtelEndpoint, vs...))
}

// OtelEndpointNotIn applies the NotIn predicate on the "otel_endpoint" field.
func OtelEndpointNotIn(vs ...string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNotIn(FieldOtelEndpoint, vs...))
}

// OtelEndpointGT applies the GT predicate on the "otel_endpoint" field.
func OtelEndpointGT(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGT(FieldOtelEndpoint, v))
}

// OtelEndpointGTE applies the GTE predicate on the "otel_endpoint" field.
func OtelEndpointGTE(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGTE(FieldOtelEndpoint, v))
}

// OtelEndpointLT applies the LT predicate on the "otel_endpoint" field.
func OtelEndpointLT(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLT(FieldOtelEndpoint, v))
}

// OtelEndpointLTE applies the LTE predicate on the "otel_endpoint" field.
func OtelEndpointLTE(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLTE(FieldOtelEndpoint, v))
}

// OtelEndpointContains applies the Contains predicate on the "otel_endpoint" field.
func OtelEndpointContains(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldContains(FieldOtelEndpoint, v))
}

// OtelEndpointHasPrefix applies the HasPrefix predicate on the "otel_endpoint" field.
func OtelEndpointHasPrefix(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldHasPrefix(FieldOtelEndpoint, v))
}

// OtelEndpointHasSuffix applies the HasSuffix predicate on the "otel_endpoint" field.
func OtelEndpointHasSuffix(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldHasSuffix(FieldOtelEndpoint, v))
}

// OtelEndpointIsNil applies the IsNil predicate on the "otel_endpoint" field.
func OtelEndpointIsNil() predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldIsNull(FieldOtelEndpoint))
}

// OtelEndpointNotNil applies the NotNil predicate on the "otel_endpoint" field.
func OtelEndpointNotNil() predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNotNull(FieldOtelEndpoint))
}

// OtelEndpointEqualFold applies the EqualFold predicate on the "otel_endpoint" field.
func OtelEndpointEqualFold(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEqualFold(FieldOtelEndpoint, v))
}

// OtelEndpointContainsFold applies the ContainsFold predicate on the "otel_endpoint" field.
func OtelEndpointContainsFold(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldContainsFold(FieldOtelEndpoint, v))
}

// TracesEnabledEQ applies the EQ predicate on the "traces_enabled" field.
func TracesEnabledEQ(v bool) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldTracesEnabled, v))
}

// TracesEnabledNEQ applies the NEQ predicate on the "traces_enabled" field.
func TracesEnabledNEQ(v bool) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNEQ(FieldTracesEnabled, v))
}

// MetricsEnabledEQ applies the EQ predicate on the "metrics_enabled" field.
func MetricsEnabledEQ(v bool) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldMetricsEnabled, v))
}

// MetricsEnabledNEQ applies the NEQ predicate on the "metrics_enabled" field.
func MetricsEnabledNEQ(v bool) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNEQ(FieldMetricsEnabled, v))
}

// LogsEnabledEQ applies the EQ predicate on the "logs_enabled" field.
func LogsEnabledEQ(v bool) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldLogsEnabled, v))
}

// LogsEnabledNEQ applies the NEQ predicate on the "logs_enabled" field.
func LogsEnabledNEQ(v bool) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNEQ(FieldLogsEnabled, v))
}

// LogSeverityEQ applies the EQ predicate on the "log_severity" field.
func LogSeverityEQ(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldLogSeverity, v))
}

// LogSeverityNEQ applies the NEQ predicate on the "log_severity" field.
func LogSeverityNEQ(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNEQ(FieldLogSeverity, v))
}

// LogSeverityIn applies the In predicate on the "log_severity" field.
func LogSeverityIn(vs ...string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldIn(FieldLogSeverity, vs...))
}

// LogSeverityNotIn applies the NotIn predicate on the "log_severity" field.
func LogSeverityNotIn(vs ...string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNotIn(FieldLogSeverity, vs...))
}

// LogSeverityGT applies the GT predicate on the "log_severity" field.
func LogSeverityGT(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGT(FieldLogSeverity, v))
}

// LogSeverityGTE applies the GTE predicate on the "log_severity" field.
func LogSeverityGTE(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGTE(FieldLogSeverity, v))
}

// LogSeverityLT applies the LT predicate on the "log_severity" field.
func LogSeverityLT(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLT(FieldLogSeverity, v))
}

// LogSeverityLTE applies the LTE predicate on the "log_severity" field.
func LogSeverityLTE(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLTE(FieldLogSeverity, v))
}

// LogSeverityContains applies the Contains predicate on the "log_severity" field.
func LogSeverityContains(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldContains(FieldLogSeverity, v))
}

// LogSeverityHasPrefix applies the HasPrefix predicate on the "log_severity" field.
func LogSeverityHasPrefix(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldHasPrefix(FieldLogSeverity, v))
}

// LogSeverityHasSuffix applies the HasSuffix predicate on the "log_severity" field.
func LogSeverityHasSuffix(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldHasSuffix(FieldLogSeverity, v))
}

// LogSeverityEqualFold applies the EqualFold predicate on the "log_severity" field.
func LogSeverityEqualFold(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEqualFold(FieldLogSeverity, v))
}

// LogSeverityContainsFold applies the ContainsFold predicate on the "log_severity" field.
func LogSeverityContainsFold(v string) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldContainsFold(FieldLogSeverity, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AdminConfig {
	return predicate.AdminConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdminConfig) predicate.AdminConfig {
	return predicate.AdminConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdminConfig) predicate.AdminConfig {
	return predicate.AdminConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdminConfig) predicate.AdminConfig {
	return predicate.AdminConfig(sql.NotPredicates(p))
}
