version: '3.8'

services:
  gitlens:
    image: ghcr.io/martynvdijke/gitlens:latest
    container_name: gitlens
    ports:
      - "6270:6270"
    env_file:
      - .env
    volumes:
      - gitlens-data:/app
      - gitlens-db:/db

volumes:
  gitlens-data:
  gitlens-db:
