// Code generated by ent, DO NOT EDIT.

package metricsnapshot

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the metricsnapshot type in the database.
	Label = "metric_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRepoID holds the string denoting the repo_id field in the database.
	FieldRepoID = "repo_id"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// FieldFeatCount holds the string denoting the feat_count field in the database.
	FieldFeatCount = "feat_count"
	// FieldFixCount holds the string denoting the fix_count field in the database.
	FieldFixCount = "fix_count"
	// FieldDocsCount holds the string denoting the docs_count field in the database.
	FieldDocsCount = "docs_count"
	// FieldChoreCount holds the string denoting the chore_count field in the database.
	FieldChoreCount = "chore_count"
	// FieldOtherCommitCount holds the string denoting the other_commit_count field in the database.
	FieldOtherCommitCount = "other_commit_count"
	// FieldTotalCommitsFetched holds the string denoting the total_commits_fetched field in the database.
	FieldTotalCommitsFetched = "total_commits_fetched"
	// FieldReleaseCount holds the string denoting the release_count field in the database.
	FieldReleaseCount = "release_count"
	// FieldAvgLeadTimeHours holds the string denoting the avg_lead_time_hours field in the database.
	FieldAvgLeadTimeHours = "avg_lead_time_hours"
	// FieldWorkflowSuccessCount holds the string denoting the workflow_success_count field in the database.
	FieldWorkflowSuccessCount = "workflow_success_count"
	// FieldWorkflowFailureCount holds the string denoting the workflow_failure_count field in the database.
	FieldWorkflowFailureCount = "workflow_failure_count"
	// FieldWorkflowStatus holds the string denoting the workflow_status field in the database.
	FieldWorkflowStatus = "workflow_status"
	// Table holds the table name of the metricsnapshot in the database.
	Table = "metric_snapshots"
)

// Columns holds all SQL columns for metricsnapshot fields.
var Columns = []string{
	FieldID,
	FieldRepoID,
	FieldTimestamp,
	FieldFeatCount,
	FieldFixCount,
	FieldDocsCount,
	FieldChoreCount,
	FieldOtherCommitCount,
	FieldTotalCommitsFetched,
	FieldReleaseCount,
	FieldAvgLeadTimeHours,
	FieldWorkflowSuccessCount,
	FieldWorkflowFailureCount,
	FieldWorkflowStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the MetricSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRepoID orders the results by the repo_id field.
func ByRepoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepoID, opts...).ToFunc()
}

// ByTimestamp orders the results by the timestamp field.
func ByTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimestamp, opts...).ToFunc()
}

// ByFeatCount orders the results by the feat_count field.
func ByFeatCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeatCount, opts...).ToFunc()
}

// ByFixCount orders the results by the fix_count field.
func ByFixCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFixCount, opts...).ToFunc()
}

// ByDocsCount orders the results by the docs_count field.
func ByDocsCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocsCount, opts...).ToFunc()
}

// ByChoreCount orders the results by the chore_count field.
func ByChoreCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChoreCount, opts...).ToFunc()
}

// ByOtherCommitCount orders the results by the other_commit_count field.
func ByOtherCommitCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOtherCommitCount, opts...).ToFunc()
}

// ByTotalCommitsFetched orders the results by the total_commits_fetched field.
func ByTotalCommitsFetched(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalCommitsFetched, opts...).ToFunc()
}

// ByReleaseCount orders the results by the release_count field.
func ByReleaseCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleaseCount, opts...).ToFunc()
}

// ByAvgLeadTimeHours orders the results by the avg_lead_time_hours field.
func ByAvgLeadTimeHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvgLeadTimeHours, opts...).ToFunc()
}

// ByWorkflowSuccessCount orders the results by the workflow_success_count field.
func ByWorkflowSuccessCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowSuccessCount, opts...).ToFunc()
}

// ByWorkflowFailureCount orders the results by the workflow_failure_count field.
func ByWorkflowFailureCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowFailureCount, opts...).ToFunc()
}

// ByWorkflowStatus orders the results by the workflow_status field.
func ByWorkflowStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowStatus, opts...).ToFunc()
}
