// Code generated by ent, DO NOT EDIT.

package metricsnapshot

import (
	"gitlens/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldID, id))
}

// RepoID applies equality check predicate on the "repo_id" field. It's identical to RepoIDEQ.
func RepoID(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldRepoID, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldTimestamp, v))
}

// FeatCount applies equality check predicate on the "feat_count" field. It's identical to FeatCountEQ.
func FeatCount(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldFeatCount, v))
}

// FixCount applies equality check predicate on the "fix_count" field. It's identical to FixCountEQ.
func FixCount(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldFixCount, v))
}

// DocsCount applies equality check predicate on the "docs_count" field. It's identical to DocsCountEQ.
func DocsCount(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldDocsCount, v))
}

// ChoreCount applies equality check predicate on the "chore_count" field. It's identical to ChoreCountEQ.
func ChoreCount(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldChoreCount, v))
}

// OtherCommitCount applies equality check predicate on the "other_commit_count" field. It's identical to OtherCommitCountEQ.
func OtherCommitCount(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldOtherCommitCount, v))
}

// TotalCommitsFetched applies equality check predicate on the "total_commits_fetched" field. It's identical to TotalCommitsFetchedEQ.
func TotalCommitsFetched(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldTotalCommitsFetched, v))
}

// ReleaseCount applies equality check predicate on the "release_count" field. It's identical to ReleaseCountEQ.
func ReleaseCount(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldReleaseCount, v))
}

// AvgLeadTimeHours applies equality check predicate on the "avg_lead_time_hours" field. It's identical to AvgLeadTimeHoursEQ.
func AvgLeadTimeHours(v float64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldAvgLeadTimeHours, v))
}

// WorkflowSuccessCount applies equality check predicate on the "workflow_success_count" field. It's identical to WorkflowSuccessCountEQ.
func WorkflowSuccessCount(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldWorkflowSuccessCount, v))
}

// WorkflowFailureCount applies equality check predicate on the "workflow_failure_count" field. It's identical to WorkflowFailureCountEQ.
func WorkflowFailureCount(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldWorkflowFailureCount, v))
}

// WorkflowStatus applies equality check predicate on the "workflow_status" field. It's identical to WorkflowStatusEQ.
func WorkflowStatus(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldWorkflowStatus, v))
}

// RepoIDEQ applies the EQ predicate on the "repo_id" field.
func RepoIDEQ(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldRepoID, v))
}

// RepoIDNEQ applies the NEQ predicate on the "repo_id" field.
func RepoIDNEQ(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldRepoID, v))
}

// RepoIDIn applies the In predicate on the "repo_id" field.
func RepoIDIn(vs ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldRepoID, vs...))
}

// RepoIDNotIn applies the NotIn predicate on the "repo_id" field.
func RepoIDNotIn(vs ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldRepoID, vs...))
}

// RepoIDGT applies the GT predicate on the "repo_id" field.
func RepoIDGT(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldRepoID, v))
}

// RepoIDGTE applies the GTE predicate on the "repo_id" field.
func RepoIDGTE(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldRepoID, v))
}

// RepoIDLT applies the LT predicate on the "repo_id" field.
func RepoIDLT(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldRepoID, v))
}

// RepoIDLTE applies the LTE predicate on the "repo_id" field.
func RepoIDLTE(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldRepoID, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldTimestamp, v))
}

// FeatCountEQ applies the EQ predicate on the "feat_count" field.
func FeatCountEQ(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldFeatCount, v))
}

// FeatCountNEQ applies the NEQ predicate on the "feat_count" field.
func FeatCountNEQ(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldFeatCount, v))
}

// FeatCountIn applies the In predicate on the "feat_count" field.
func FeatCountIn(vs ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldFeatCount, vs...))
}

// FeatCountNotIn applies the NotIn predicate on the "feat_count" field.
func FeatCountNotIn(vs ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldFeatCount, vs...))
}

// FeatCountGT applies the GT predicate on the "feat_count" field.
func FeatCountGT(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldFeatCount, v))
}

// FeatCountGTE applies the GTE predicate on the "feat_count" field.
func FeatCountGTE(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldFeatCount, v))
}

// FeatCountLT applies the LT predicate on the "feat_count" field.
func FeatCountLT(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldFeatCount, v))
}

// FeatCountLTE applies the LTE predicate on the "feat_count" field.
func FeatCountLTE(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldFeatCount, v))
}

// FeatCountIsNil applies the IsNil predicate on the "feat_count" field.
func FeatCountIsNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIsNull(FieldFeatCount))
}

// FeatCountNotNil applies the NotNil predicate on the "feat_count" field.
func FeatCountNotNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotNull(FieldFeatCount))
}

// FixCountEQ applies the EQ predicate on the "fix_count" field.
func FixCountEQ(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldFixCount, v))
}

// FixCountNEQ applies the NEQ predicate on the "fix_count" field.
func FixCountNEQ(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldFixCount, v))
}

// FixCountIn applies the In predicate on the "fix_count" field.
func FixCountIn(vs ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldFixCount, vs...))
}

// FixCountNotIn applies the NotIn predicate on the "fix_count" field.
func FixCountNotIn(vs ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldFixCount, vs...))
}

// FixCountGT applies the GT predicate on the "fix_count" field.
func FixCountGT(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldFixCount, v))
}

// FixCountGTE applies the GTE predicate on the "fix_count" field.
func FixCountGTE(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldFixCount, v))
}

// FixCountLT applies the LT predicate on the "fix_count" field.
func FixCountLT(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldFixCount, v))
}

// FixCountLTE applies the LTE predicate on the "fix_count" field.
func FixCountLTE(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldFixCount, v))
}

// FixCountIsNil applies the IsNil predicate on the "fix_count" field.
func FixCountIsNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIsNull(FieldFixCount))
}

// FixCountNotNil applies the NotNil predicate on the "fix_count" field.
func FixCountNotNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotNull(FieldFixCount))
}

// DocsCountEQ applies the EQ predicate on the "docs_count" field.
func DocsCountEQ(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldDocsCount, v))
}

// DocsCountNEQ applies the NEQ predicate on the "docs_count" field.
func DocsCountNEQ(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldDocsCount, v))
}

// DocsCountIn applies the In predicate on the "docs_count" field.
func DocsCountIn(vs ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldDocsCount, vs...))
}

// DocsCountNotIn applies the NotIn predicate on the "docs_count" field.
func DocsCountNotIn(vs ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldDocsCount, vs...))
}

// DocsCountGT applies the GT predicate on the "docs_count" field.
func DocsCountGT(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldDocsCount, v))
}

// DocsCountGTE applies the GTE predicate on the "docs_count" field.
func DocsCountGTE(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldDocsCount, v))
}

// DocsCountLT applies the LT predicate on the "docs_count" field.
func DocsCountLT(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldDocsCount, v))
}

// DocsCountLTE applies the LTE predicate on the "docs_count" field.
func DocsCountLTE(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldDocsCount, v))
}

// DocsCountIsNil applies the IsNil predicate on the "docs_count" field.
func DocsCountIsNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIsNull(FieldDocsCount))
}

// DocsCountNotNil applies the NotNil predicate on the "docs_count" field.
func DocsCountNotNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotNull(FieldDocsCount))
}

// ChoreCountEQ applies the EQ predicate on the "chore_count" field.
func ChoreCountEQ(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldChoreCount, v))
}

// ChoreCountNEQ applies the NEQ predicate on the "chore_count" field.
func ChoreCountNEQ(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldChoreCount, v))
}

// ChoreCountIn applies the In predicate on the "chore_count" field.
func ChoreCountIn(vs ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldChoreCount, vs...))
}

// ChoreCountNotIn applies the NotIn predicate on the "chore_count" field.
func ChoreCountNotIn(vs ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldChoreCount, vs...))
}

// ChoreCountGT applies the GT predicate on the "chore_count" field.
func ChoreCountGT(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldChoreCount, v))
}

// ChoreCountGTE applies the GTE predicate on the "chore_count" field.
func ChoreCountGTE(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldChoreCount, v))
}

// ChoreCountLT applies the LT predicate on the "chore_count" field.
func ChoreCountLT(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldChoreCount, v))
}

// ChoreCountLTE applies the LTE predicate on the "chore_count" field.
func ChoreCountLTE(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldChoreCount, v))
}

// ChoreCountIsNil applies the IsNil predicate on the "chore_count" field.
func ChoreCountIsNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIsNull(FieldChoreCount))
}

// ChoreCountNotNil applies the NotNil predicate on the "chore_count" field.
func ChoreCountNotNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotNull(FieldChoreCount))
}

// OtherCommitCountEQ applies the EQ predicate on the "other_commit_count" field.
func OtherCommitCountEQ(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldOtherCommitCount, v))
}

// OtherCommitCountNEQ applies the NEQ predicate on the "other_commit_count" field.
func OtherCommitCountNEQ(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldOtherCommitCount, v))
}

// OtherCommitCountIn applies the In predicate on the "other_commit_count" field.
func OtherCommitCountIn(vs ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldOtherCommitCount, vs...))
}

// OtherCommitCountNotIn applies the NotIn predicate on the "other_commit_count" field.
func OtherCommitCountNotIn(vs ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldOtherCommitCount, vs...))
}

// OtherCommitCountGT applies the GT predicate on the "other_commit_count" field.
func OtherCommitCountGT(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldOtherCommitCount, v))
}

// OtherCommitCountGTE applies the GTE predicate on the "other_commit_count" field.
func OtherCommitCountGTE(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldOtherCommitCount, v))
}

// OtherCommitCountLT applies the LT predicate on the "other_commit_count" field.
func OtherCommitCountLT(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldOtherCommitCount, v))
}

// OtherCommitCountLTE applies the LTE predicate on the "other_commit_count" field.
func OtherCommitCountLTE(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldOtherCommitCount, v))
}

// OtherCommitCountIsNil applies the IsNil predicate on the "other_commit_count" field.
func OtherCommitCountIsNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIsNull(FieldOtherCommitCount))
}

// OtherCommitCountNotNil applies the NotNil predicate on the "other_commit_count" field.
func OtherCommitCountNotNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotNull(FieldOtherCommitCount))
}

// TotalCommitsFetchedEQ applies the EQ predicate on the "total_commits_fetched" field.
func TotalCommitsFetchedEQ(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldTotalCommitsFetched, v))
}

// TotalCommitsFetchedNEQ applies the NEQ predicate on the "total_commits_fetched" field.
func TotalCommitsFetchedNEQ(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldTotalCommitsFetched, v))
}

// TotalCommitsFetchedIn applies the In predicate on the "total_commits_fetched" field.
func TotalCommitsFetchedIn(vs ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldTotalCommitsFetched, vs...))
}

// TotalCommitsFetchedNotIn applies the NotIn predicate on the "total_commits_fetched" field.
func TotalCommitsFetchedNotIn(vs ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldTotalCommitsFetched, vs...))
}

// TotalCommitsFetchedGT applies the GT predicate on the "total_commits_fetched" field.
func TotalCommitsFetchedGT(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldTotalCommitsFetched, v))
}

// TotalCommitsFetchedGTE applies the GTE predicate on the "total_commits_fetched" field.
func TotalCommitsFetchedGTE(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldTotalCommitsFetched, v))
}

// TotalCommitsFetchedLT applies the LT predicate on the "total_commits_fetched" field.
func TotalCommitsFetchedLT(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldTotalCommitsFetched, v))
}

// TotalCommitsFetchedLTE applies the LTE predicate on the "total_commits_fetched" field.
func TotalCommitsFetchedLTE(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldTotalCommitsFetched, v))
}

// TotalCommitsFetchedIsNil applies the IsNil predicate on the "total_commits_fetched" field.
func TotalCommitsFetchedIsNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIsNull(FieldTotalCommitsFetched))
}

// TotalCommitsFetchedNotNil applies the NotNil predicate on the "total_commits_fetched" field.
func TotalCommitsFetchedNotNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotNull(FieldTotalCommitsFetched))
}

// ReleaseCountEQ applies the EQ predicate on the "release_count" field.
func ReleaseCountEQ(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldReleaseCount, v))
}

// ReleaseCountNEQ applies the NEQ predicate on the "release_count" field.
func ReleaseCountNEQ(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldReleaseCount, v))
}

// ReleaseCountIn applies the In predicate on the "release_count" field.
func ReleaseCountIn(vs ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldReleaseCount, vs...))
}

// ReleaseCountNotIn applies the NotIn predicate on the "release_count" field.
func ReleaseCountNotIn(vs ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldReleaseCount, vs...))
}

// ReleaseCountGT applies the GT predicate on the "release_count" field.
func ReleaseCountGT(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldReleaseCount, v))
}

// ReleaseCountGTE applies the GTE predicate on the "release_count" field.
func ReleaseCountGTE(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldReleaseCount, v))
}

// ReleaseCountLT applies the LT predicate on the "release_count" field.
func ReleaseCountLT(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldReleaseCount, v))
}

// ReleaseCountLTE applies the LTE predicate on the "release_count" field.
func ReleaseCountLTE(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldReleaseCount, v))
}

// ReleaseCountIsNil applies the IsNil predicate on the "release_count" field.
func ReleaseCountIsNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIsNull(FieldReleaseCount))
}

// ReleaseCountNotNil applies the NotNil predicate on the "release_count" field.
func ReleaseCountNotNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotNull(FieldReleaseCount))
}

// AvgLeadTimeHoursEQ applies the EQ predicate on the "avg_lead_time_hours" field.
func AvgLeadTimeHoursEQ(v float64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldAvgLeadTimeHours, v))
}

// AvgLeadTimeHoursNEQ applies the NEQ predicate on the "avg_lead_time_hours" field.
func AvgLeadTimeHoursNEQ(v float64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldAvgLeadTimeHours, v))
}

// AvgLeadTimeHoursIn applies the In predicate on the "avg_lead_time_hours" field.
func AvgLeadTimeHoursIn(vs ...float64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldAvgLeadTimeHours, vs...))
}

// AvgLeadTimeHoursNotIn applies the NotIn predicate on the "avg_lead_time_hours" field.
func AvgLeadTimeHoursNotIn(vs ...float64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldAvgLeadTimeHours, vs...))
}

// AvgLeadTimeHoursGT applies the GT predicate on the "avg_lead_time_hours" field.
func AvgLeadTimeHoursGT(v float64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldAvgLeadTimeHours, v))
}

// AvgLeadTimeHoursGTE applies the GTE predicate on the "avg_lead_time_hours" field.
func AvgLeadTimeHoursGTE(v float64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldAvgLeadTimeHours, v))
}

// AvgLeadTimeHoursLT applies the LT predicate on the "avg_lead_time_hours" field.
func AvgLeadTimeHoursLT(v float64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldAvgLeadTimeHours, v))
}

// AvgLeadTimeHoursLTE applies the LTE predicate on the "avg_lead_time_hours" field.
func AvgLeadTimeHoursLTE(v float64) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldAvgLeadTimeHours, v))
}

// AvgLeadTimeHoursIsNil applies the IsNil predicate on the "avg_lead_time_hours" field.
func AvgLeadTimeHoursIsNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIsNull(FieldAvgLeadTimeHours))
}

// AvgLeadTimeHoursNotNil applies the NotNil predicate on the "avg_lead_time_hours" field.
func AvgLeadTimeHoursNotNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotNull(FieldAvgLeadTimeHours))
}

// WorkflowSuccessCountEQ applies the EQ predicate on the "workflow_success_count" field.
func WorkflowSuccessCountEQ(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldWorkflowSuccessCount, v))
}

// WorkflowSuccessCountNEQ applies the NEQ predicate on the "workflow_success_count" field.
func WorkflowSuccessCountNEQ(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldWorkflowSuccessCount, v))
}

// WorkflowSuccessCountIn applies the In predicate on the "workflow_success_count" field.
func WorkflowSuccessCountIn(vs ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldWorkflowSuccessCount, vs...))
}

// WorkflowSuccessCountNotIn applies the NotIn predicate on the "workflow_success_count" field.
func WorkflowSuccessCountNotIn(vs ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldWorkflowSuccessCount, vs...))
}

// WorkflowSuccessCountGT applies the GT predicate on the "workflow_success_count" field.
func WorkflowSuccessCountGT(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldWorkflowSuccessCount, v))
}

// WorkflowSuccessCountGTE applies the GTE predicate on the "workflow_success_count" field.
func WorkflowSuccessCountGTE(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldWorkflowSuccessCount, v))
}

// WorkflowSuccessCountLT applies the LT predicate on the "workflow_success_count" field.
func WorkflowSuccessCountLT(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldWorkflowSuccessCount, v))
}

// WorkflowSuccessCountLTE applies the LTE predicate on the "workflow_success_count" field.
func WorkflowSuccessCountLTE(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldWorkflowSuccessCount, v))
}

// WorkflowSuccessCountIsNil applies the IsNil predicate on the "workflow_success_count" field.
func WorkflowSuccessCountIsNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIsNull(FieldWorkflowSuccessCount))
}

// WorkflowSuccessCountNotNil applies the NotNil predicate on the "workflow_success_count" field.
func WorkflowSuccessCountNotNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotNull(FieldWorkflowSuccessCount))
}

// WorkflowFailureCountEQ applies the EQ predicate on the "workflow_failure_count" field.
func WorkflowFailureCountEQ(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldWorkflowFailureCount, v))
}

// WorkflowFailureCountNEQ applies the NEQ predicate on the "workflow_failure_count" field.
func WorkflowFailureCountNEQ(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldWorkflowFailureCount, v))
}

// WorkflowFailureCountIn applies the In predicate on the "workflow_failure_count" field.
func WorkflowFailureCountIn(vs ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldWorkflowFailureCount, vs...))
}

// WorkflowFailureCountNotIn applies the NotIn predicate on the "workflow_failure_count" field.
func WorkflowFailureCountNotIn(vs ...int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldWorkflowFailureCount, vs...))
}

// WorkflowFailureCountGT applies the GT predicate on the "workflow_failure_count" field.
func WorkflowFailureCountGT(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldWorkflowFailureCount, v))
}

// WorkflowFailureCountGTE applies the GTE predicate on the "workflow_failure_count" field.
func WorkflowFailureCountGTE(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldWorkflowFailureCount, v))
}

// WorkflowFailureCountLT applies the LT predicate on the "workflow_failure_count" field.
func WorkflowFailureCountLT(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldWorkflowFailureCount, v))
}

// WorkflowFailureCountLTE applies the LTE predicate on the "workflow_failure_count" field.
func WorkflowFailureCountLTE(v int) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldWorkflowFailureCount, v))
}

// WorkflowFailureCountIsNil applies the IsNil predicate on the "workflow_failure_count" field.
func WorkflowFailureCountIsNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIsNull(FieldWorkflowFailureCount))
}

// WorkflowFailureCountNotNil applies the NotNil predicate on the "workflow_failure_count" field.
func WorkflowFailureCountNotNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotNull(FieldWorkflowFailureCount))
}

// WorkflowStatusEQ applies the EQ predicate on the "workflow_status" field.
func WorkflowStatusEQ(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEQ(FieldWorkflowStatus, v))
}

// WorkflowStatusNEQ applies the NEQ predicate on the "workflow_status" field.
func WorkflowStatusNEQ(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNEQ(FieldWorkflowStatus, v))
}

// WorkflowStatusIn applies the In predicate on the "workflow_status" field.
func WorkflowStatusIn(vs ...string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIn(FieldWorkflowStatus, vs...))
}

// WorkflowStatusNotIn applies the NotIn predicate on the "workflow_status" field.
func WorkflowStatusNotIn(vs ...string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotIn(FieldWorkflowStatus, vs...))
}

// WorkflowStatusGT applies the GT predicate on the "workflow_status" field.
func WorkflowStatusGT(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGT(FieldWorkflowStatus, v))
}

// WorkflowStatusGTE applies the GTE predicate on the "workflow_status" field.
func WorkflowStatusGTE(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldGTE(FieldWorkflowStatus, v))
}

// WorkflowStatusLT applies the LT predicate on the "workflow_status" field.
func WorkflowStatusLT(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLT(FieldWorkflowStatus, v))
}

// WorkflowStatusLTE applies the LTE predicate on the "workflow_status" field.
func WorkflowStatusLTE(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldLTE(FieldWorkflowStatus, v))
}

// WorkflowStatusContains applies the Contains predicate on the "workflow_status" field.
func WorkflowStatusContains(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldContains(FieldWorkflowStatus, v))
}

// WorkflowStatusHasPrefix applies the HasPrefix predicate on the "workflow_status" field.
func WorkflowStatusHasPrefix(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldHasPrefix(FieldWorkflowStatus, v))
}

// WorkflowStatusHasSuffix applies the HasSuffix predicate on the "workflow_status" field.
func WorkflowStatusHasSuffix(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldHasSuffix(FieldWorkflowStatus, v))
}

// WorkflowStatusIsNil applies the IsNil predicate on the "workflow_status" field.
func WorkflowStatusIsNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldIsNull(FieldWorkflowStatus))
}

// WorkflowStatusNotNil applies the NotNil predicate on the "workflow_status" field.
func WorkflowStatusNotNil() predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldNotNull(FieldWorkflowStatus))
}

// WorkflowStatusEqualFold applies the EqualFold predicate on the "workflow_status" field.
func WorkflowStatusEqualFold(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldEqualFold(FieldWorkflowStatus, v))
}

// WorkflowStatusContainsFold applies the ContainsFold predicate on the "workflow_status" field.
func WorkflowStatusContainsFold(v string) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.FieldContainsFold(FieldWorkflowStatus, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MetricSnapshot) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MetricSnapshot) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MetricSnapshot) predicate.MetricSnapshot {
	return predicate.MetricSnapshot(sql.NotPredicates(p))
}
