// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gitlens/ent/adminconfig"
	"gitlens/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdminConfigUpdate is the builder for updating AdminConfig entities.
type AdminConfigUpdate struct {
	config
	hooks    []Hook
	mutation *AdminConfigMutation
}

// Where appends a list predicates to the AdminConfigUpdate builder.
func (_u *AdminConfigUpdate) Where(ps ...predicate.AdminConfig) *AdminConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOtelEndpoint sets the "otel_endpoint" field.
func (_u *AdminConfigUpdate) SetOtelEndpoint(v string) *AdminConfigUpdate {
	_u.mutation.SetOtelEndpoint(v)
	return _u
}

// SetNillableOtelEndpoint sets the "otel_endpoint" field if the given value is not nil.
func (_u *AdminConfigUpdate) SetNillableOtelEndpoint(v *string) *AdminConfigUpdate {
	if v != nil {
		_u.SetOtelEndpoint(*v)
	}
	return _u
}

// ClearOtelEndpoint clears the value of the "otel_endpoint" field.
func (_u *AdminConfigUpdate) ClearOtelEndpoint() *AdminConfigUpdate {
	_u.mutation.ClearOtelEndpoint()
	return _u
}

// SetTracesEnabled sets the "traces_enabled" field.
func (_u *AdminConfigUpdate) SetTracesEnabled(v bool) *AdminConfigUpdate {
	_u.mutation.SetTracesEnabled(v)
	return _u
}

// SetNillableTracesEnabled sets the "traces_enabled" field if the given value is not nil.
func (_u *AdminConfigUpdate) SetNillableTracesEnabled(v *bool) *AdminConfigUpdate {
	if v != nil {
		_u.SetTracesEnabled(*v)
	}
	return _u
}

// SetMetricsEnabled sets the "metrics_enabled" field.
func (_u *AdminConfigUpdate) SetMetricsEnabled(v bool) *AdminConfigUpdate {
	_u.mutation.SetMetricsEnabled(v)
	return _u
}

// SetNillableMetricsEnabled sets the "metrics_enabled" field if the given value is not nil.
func (_u *AdminConfigUpdate) SetNillableMetricsEnabled(v *bool) *AdminConfigUpdate {
	if v != nil {
		_u.SetMetricsEnabled(*v)
	}
	return _u
}

// SetLogsEnabled sets the "logs_enabled" field.
func (_u *AdminConfigUpdate) SetLogsEnabled(v bool) *AdminConfigUpdate {
	_u.mutation.SetLogsEnabled(v)
	return _u
}

// SetNillableLogsEnabled sets the "logs_enabled" field if the given value is not nil.
func (_u *AdminConfigUpdate) SetNillableLogsEnabled(v *bool) *AdminConfigUpdate {
	if v != nil {
		_u.SetLogsEnabled(*v)
	}
	return _u
}

// SetLogSeverity sets the "log_severity" field.
func (_u *AdminConfigUpdate) SetLogSeverity(v string) *AdminConfigUpdate {
	_u.mutation.SetLogSeverity(v)
	return _u
}

// SetNillableLogSeverity sets the "log_severity" field if the given value is not nil.
func (_u *AdminConfigUpdate) SetNillableLogSeverity(v *string) *AdminConfigUpdate {
	if v != nil {
		_u.SetLogSeverity(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminConfigUpdate) SetUpdatedAt(v time.Time) *AdminConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AdminConfigMutation object of the builder.
func (_u *AdminConfigUpdate) Mutation() *AdminConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adminconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AdminConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(adminconfig.Table, adminconfig.Columns, sqlgraph.NewFieldSpec(adminconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OtelEndpoint(); ok {
		_spec.SetField(adminconfig.FieldOtelEndpoint, field.TypeString, value)
	}
	if _u.mutation.OtelEndpointCleared() {
		_spec.ClearField(adminconfig.FieldOtelEndpoint, field.TypeString)
	}
	if value, ok := _u.mutation.TracesEnabled(); ok {
		_spec.SetField(adminconfig.FieldTracesEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MetricsEnabled(); ok {
		_spec.SetField(adminconfig.FieldMetricsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LogsEnabled(); ok {
		_spec.SetField(adminconfig.FieldLogsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LogSeverity(); ok {
		_spec.SetField(adminconfig.FieldLogSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminConfigUpdateOne is the builder for updating a single AdminConfig entity.
type AdminConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminConfigMutation
}

// SetOtelEndpoint sets the "otel_endpoint" field.
func (_u *AdminConfigUpdateOne) SetOtelEndpoint(v string) *AdminConfigUpdateOne {
	_u.mutation.SetOtelEndpoint(v)
	return _u
}

// SetNillableOtelEndpoint sets the "otel_endpoint" field if the given value is not nil.
func (_u *AdminConfigUpdateOne) SetNillableOtelEndpoint(v *string) *AdminConfigUpdateOne {
	if v != nil {
		_u.SetOtelEndpoint(*v)
	}
	return _u
}

// ClearOtelEndpoint clears the value of the "otel_endpoint" field.
func (_u *AdminConfigUpdateOne) ClearOtelEndpoint() *AdminConfigUpdateOne {
	_u.mutation.ClearOtelEndpoint()
	return _u
}

// SetTracesEnabled sets the "traces_enabled" field.
func (_u *AdminConfigUpdateOne) SetTracesEnabled(v bool) *AdminConfigUpdateOne {
	_u.mutation.SetTracesEnabled(v)
	return _u
}

// SetNillableTracesEnabled sets the "traces_enabled" field if the given value is not nil.
func (_u *AdminConfigUpdateOne) SetNillableTracesEnabled(v *bool) *AdminConfigUpdateOne {
	if v != nil {
		_u.SetTracesEnabled(*v)
	}
	return _u
}

// SetMetricsEnabled sets the "metrics_enabled" field.
func (_u *AdminConfigUpdateOne) SetMetricsEnabled(v bool) *AdminConfigUpdateOne {
	_u.mutation.SetMetricsEnabled(v)
	return _u
}

// SetNillableMetricsEnabled sets the "metrics_enabled" field if the given value is not nil.
func (_u *AdminConfigUpdateOne) SetNillableMetricsEnabled(v *bool) *AdminConfigUpdateOne {
	if v != nil {
		_u.SetMetricsEnabled(*v)
	}
	return _u
}

// SetLogsEnabled sets the "logs_enabled" field.
func (_u *AdminConfigUpdateOne) SetLogsEnabled(v bool) *AdminConfigUpdateOne {
	_u.mutation.SetLogsEnabled(v)
	return _u
}

// SetNillableLogsEnabled sets the "logs_enabled" field if the given value is not nil.
func (_u *AdminConfigUpdateOne) SetNillableLogsEnabled(v *bool) *AdminConfigUpdateOne {
	if v != nil {
		_u.SetLogsEnabled(*v)
	}
	return _u
}

// SetLogSeverity sets the "log_severity" field.
func (_u *AdminConfigUpdateOne) SetLogSeverity(v string) *AdminConfigUpdateOne {
	_u.mutation.SetLogSeverity(v)
	return _u
}

// SetNillableLogSeverity sets the "log_severity" field if the given value is not nil.
func (_u *AdminConfigUpdateOne) SetNillableLogSeverity(v *string) *AdminConfigUpdateOne {
	if v != nil {
		_u.SetLogSeverity(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminConfigUpdateOne) SetUpdatedAt(v time.Time) *AdminConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AdminConfigMutation object of the builder.
func (_u *AdminConfigUpdateOne) Mutation() *AdminConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the AdminConfigUpdate builder.
func (_u *AdminConfigUpdateOne) Where(ps ...predicate.AdminConfig) *AdminConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminConfigUpdateOne) Select(field string, fields ...string) *AdminConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminConfig entity.
func (_u *AdminConfigUpdateOne) Save(ctx context.Context) (*AdminConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminConfigUpdateOne) SaveX(ctx context.Context) *AdminConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adminconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AdminConfigUpdateOne) sqlSave(ctx context.Context) (_node *AdminConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(adminconfig.Table, adminconfig.Columns, sqlgraph.NewFieldSpec(adminconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminconfig.FieldID)
		for _, f := range fields {
			if !adminconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OtelEndpoint(); ok {
		_spec.SetField(adminconfig.FieldOtelEndpoint, field.TypeString, value)
	}
	if _u.mutation.OtelEndpointCleared() {
		_spec.ClearField(adminconfig.FieldOtelEndpoint, field.TypeString)
	}
	if value, ok := _u.mutation.TracesEnabled(); ok {
		_spec.SetField(adminconfig.FieldTracesEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MetricsEnabled(); ok {
		_spec.SetField(adminconfig.FieldMetricsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LogsEnabled(); ok {
		_spec.SetField(adminconfig.FieldLogsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LogSeverity(); ok {
		_spec.SetField(adminconfig.FieldLogSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AdminConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
