// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gitlens/ent/commitactivity"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CommitActivityCreate is the builder for creating a CommitActivity entity.
type CommitActivityCreate struct {
	config
	mutation *CommitActivityMutation
	hooks    []Hook
}

// SetRepoID sets the "repo_id" field.
func (_c *CommitActivityCreate) SetRepoID(v int) *CommitActivityCreate {
	_c.mutation.SetRepoID(v)
	return _c
}

// SetDate sets the "date" field.
func (_c *CommitActivityCreate) SetDate(v time.Time) *CommitActivityCreate {
	_c.mutation.SetDate(v)
	return _c
}

// SetCommitCount sets the "commit_count" field.
func (_c *CommitActivityCreate) SetCommitCount(v int) *CommitActivityCreate {
	_c.mutation.SetCommitCount(v)
	return _c
}

// Mutation returns the CommitActivityMutation object of the builder.
func (_c *CommitActivityCreate) Mutation() *CommitActivityMutation {
	return _c.mutation
}

// Save creates the CommitActivity in the database.
func (_c *CommitActivityCreate) Save(ctx context.Context) (*CommitActivity, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CommitActivityCreate) SaveX(ctx context.Context) *CommitActivity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CommitActivityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CommitActivityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CommitActivityCreate) check() error {
	if _, ok := _c.mutation.RepoID(); !ok {
		return &ValidationError{Name: "repo_id", err: errors.New(`ent: missing required field "CommitActivity.repo_id"`)}
	}
	if _, ok := _c.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "CommitActivity.date"`)}
	}
	if _, ok := _c.mutation.CommitCount(); !ok {
		return &ValidationError{Name: "commit_count", err: errors.New(`ent: missing required field "CommitActivity.commit_count"`)}
	}
	return nil
}

func (_c *CommitActivityCreate) sqlSave(ctx context.Context) (*CommitActivity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CommitActivityCreate) createSpec() (*CommitActivity, *sqlgraph.CreateSpec) {
	var (
		_node = &CommitActivity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(commitactivity.Table, sqlgraph.NewFieldSpec(commitactivity.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.RepoID(); ok {
		_spec.SetField(commitactivity.FieldRepoID, field.TypeInt, value)
		_node.RepoID = value
	}
	if value, ok := _c.mutation.Date(); ok {
		_spec.SetField(commitactivity.FieldDate, field.TypeTime, value)
		_node.Date = value
	}
	if value, ok := _c.mutation.CommitCount(); ok {
		_spec.SetField(commitactivity.FieldCommitCount, field.TypeInt, value)
		_node.CommitCount = value
	}
	return _node, _spec
}

// CommitActivityCreateBulk is the builder for creating many CommitActivity entities in bulk.
type CommitActivityCreateBulk struct {
	config
	err      error
	builders []*CommitActivityCreate
}

// Save creates the CommitActivity entities in the database.
func (_c *CommitActivityCreateBulk) Save(ctx context.Context) ([]*CommitActivity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CommitActivity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CommitActivityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CommitActivityCreateBulk) SaveX(ctx context.Context) []*CommitActivity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CommitActivityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CommitActivityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
