// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gitlens/ent/commitactivity"
	"gitlens/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CommitActivityUpdate is the builder for updating CommitActivity entities.
type CommitActivityUpdate struct {
	config
	hooks    []Hook
	mutation *CommitActivityMutation
}

// Where appends a list predicates to the CommitActivityUpdate builder.
func (_u *CommitActivityUpdate) Where(ps ...predicate.CommitActivity) *CommitActivityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRepoID sets the "repo_id" field.
func (_u *CommitActivityUpdate) SetRepoID(v int) *CommitActivityUpdate {
	_u.mutation.ResetRepoID()
	_u.mutation.SetRepoID(v)
	return _u
}

// SetNillableRepoID sets the "repo_id" field if the given value is not nil.
func (_u *CommitActivityUpdate) SetNillableRepoID(v *int) *CommitActivityUpdate {
	if v != nil {
		_u.SetRepoID(*v)
	}
	return _u
}

// AddRepoID adds value to the "repo_id" field.
func (_u *CommitActivityUpdate) AddRepoID(v int) *CommitActivityUpdate {
	_u.mutation.AddRepoID(v)
	return _u
}

// SetDate sets the "date" field.
func (_u *CommitActivityUpdate) SetDate(v time.Time) *CommitActivityUpdate {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *CommitActivityUpdate) SetNillableDate(v *time.Time) *CommitActivityUpdate {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetCommitCount sets the "commit_count" field.
func (_u *CommitActivityUpdate) SetCommitCount(v int) *CommitActivityUpdate {
	_u.mutation.ResetCommitCount()
	_u.mutation.SetCommitCount(v)
	return _u
}

// SetNillableCommitCount sets the "commit_count" field if the given value is not nil.
func (_u *CommitActivityUpdate) SetNillableCommitCount(v *int) *CommitActivityUpdate {
	if v != nil {
		_u.SetCommitCount(*v)
	}
	return _u
}

// AddCommitCount adds value to the "commit_count" field.
func (_u *CommitActivityUpdate) AddCommitCount(v int) *CommitActivityUpdate {
	_u.mutation.AddCommitCount(v)
	return _u
}

// Mutation returns the CommitActivityMutation object of the builder.
func (_u *CommitActivityUpdate) Mutation() *CommitActivityMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CommitActivityUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommitActivityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CommitActivityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommitActivityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CommitActivityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(commitactivity.Table, commitactivity.Columns, sqlgraph.NewFieldSpec(commitactivity.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RepoID(); ok {
		_spec.SetField(commitactivity.FieldRepoID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRepoID(); ok {
		_spec.AddField(commitactivity.FieldRepoID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(commitactivity.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CommitCount(); ok {
		_spec.SetField(commitactivity.FieldCommitCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommitCount(); ok {
		_spec.AddField(commitactivity.FieldCommitCount, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commitactivity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CommitActivityUpdateOne is the builder for updating a single CommitActivity entity.
type CommitActivityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommitActivityMutation
}

// SetRepoID sets the "repo_id" field.
func (_u *CommitActivityUpdateOne) SetRepoID(v int) *CommitActivityUpdateOne {
	_u.mutation.ResetRepoID()
	_u.mutation.SetRepoID(v)
	return _u
}

// SetNillableRepoID sets the "repo_id" field if the given value is not nil.
func (_u *CommitActivityUpdateOne) SetNillableRepoID(v *int) *CommitActivityUpdateOne {
	if v != nil {
		_u.SetRepoID(*v)
	}
	return _u
}

// AddRepoID adds value to the "repo_id" field.
func (_u *CommitActivityUpdateOne) AddRepoID(v int) *CommitActivityUpdateOne {
	_u.mutation.AddRepoID(v)
	return _u
}

// SetDate sets the "date" field.
func (_u *CommitActivityUpdateOne) SetDate(v time.Time) *CommitActivityUpdateOne {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *CommitActivityUpdateOne) SetNillableDate(v *time.Time) *CommitActivityUpdateOne {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetCommitCount sets the "commit_count" field.
func (_u *CommitActivityUpdateOne) SetCommitCount(v int) *CommitActivityUpdateOne {
	_u.mutation.ResetCommitCount()
	_u.mutation.SetCommitCount(v)
	return _u
}

// SetNillableCommitCount sets the "commit_count" field if the given value is not nil.
func (_u *CommitActivityUpdateOne) SetNillableCommitCount(v *int) *CommitActivityUpdateOne {
	if v != nil {
		_u.SetCommitCount(*v)
	}
	return _u
}

// AddCommitCount adds value to the "commit_count" field.
func (_u *CommitActivityUpdateOne) AddCommitCount(v int) *CommitActivityUpdateOne {
	_u.mutation.AddCommitCount(v)
	return _u
}

// Mutation returns the CommitActivityMutation object of the builder.
func (_u *CommitActivityUpdateOne) Mutation() *CommitActivityMutation {
	return _u.mutation
}

// Where appends a list predicates to the CommitActivityUpdate builder.
func (_u *CommitActivityUpdateOne) Where(ps ...predicate.CommitActivity) *CommitActivityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CommitActivityUpdateOne) Select(field string, fields ...string) *CommitActivityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CommitActivity entity.
func (_u *CommitActivityUpdateOne) Save(ctx context.Context) (*CommitActivity, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommitActivityUpdateOne) SaveX(ctx context.Context) *CommitActivity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CommitActivityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommitActivityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CommitActivityUpdateOne) sqlSave(ctx context.Context) (_node *CommitActivity, err error) {
	_spec := sqlgraph.NewUpdateSpec(commitactivity.Table, commitactivity.Columns, sqlgraph.NewFieldSpec(commitactivity.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CommitActivity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, commitactivity.FieldID)
		for _, f := range fields {
			if !commitactivity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != commitactivity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RepoID(); ok {
		_spec.SetField(commitactivity.FieldRepoID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRepoID(); ok {
		_spec.AddField(commitactivity.FieldRepoID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(commitactivity.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CommitCount(); ok {
		_spec.SetField(commitactivity.FieldCommitCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommitCount(); ok {
		_spec.AddField(commitactivity.FieldCommitCount, field.TypeInt, value)
	}
	_node = &CommitActivity{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commitactivity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
