// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gitlens/ent/metricsnapshot"
	"gitlens/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MetricSnapshotUpdate is the builder for updating MetricSnapshot entities.
type MetricSnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *MetricSnapshotMutation
}

// Where appends a list predicates to the MetricSnapshotUpdate builder.
func (_u *MetricSnapshotUpdate) Where(ps ...predicate.MetricSnapshot) *MetricSnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRepoID sets the "repo_id" field.
func (_u *MetricSnapshotUpdate) SetRepoID(v int) *MetricSnapshotUpdate {
	_u.mutation.ResetRepoID()
	_u.mutation.SetRepoID(v)
	return _u
}

// SetNillableRepoID sets the "repo_id" field if the given value is not nil.
func (_u *MetricSnapshotUpdate) SetNillableRepoID(v *int) *MetricSnapshotUpdate {
	if v != nil {
		_u.SetRepoID(*v)
	}
	return _u
}

// AddRepoID adds value to the "repo_id" field.
func (_u *MetricSnapshotUpdate) AddRepoID(v int) *MetricSnapshotUpdate {
	_u.mutation.AddRepoID(v)
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *MetricSnapshotUpdate) SetTimestamp(v time.Time) *MetricSnapshotUpdate {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *MetricSnapshotUpdate) SetNillableTimestamp(v *time.Time) *MetricSnapshotUpdate {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetFeatCount sets the "feat_count" field.
func (_u *MetricSnapshotUpdate) SetFeatCount(v int) *MetricSnapshotUpdate {
	_u.mutation.ResetFeatCount()
	_u.mutation.SetFeatCount(v)
	return _u
}

// SetNillableFeatCount sets the "feat_count" field if the given value is not nil.
func (_u *MetricSnapshotUpdate) SetNillableFeatCount(v *int) *MetricSnapshotUpdate {
	if v != nil {
		_u.SetFeatCount(*v)
	}
	return _u
}

// AddFeatCount adds value to the "feat_count" field.
func (_u *MetricSnapshotUpdate) AddFeatCount(v int) *MetricSnapshotUpdate {
	_u.mutation.AddFeatCount(v)
	return _u
}

// ClearFeatCount clears the value of the "feat_count" field.
func (_u *MetricSnapshotUpdate) ClearFeatCount() *MetricSnapshotUpdate {
	_u.mutation.ClearFeatCount()
	return _u
}

// SetFixCount sets the "fix_count" field.
func (_u *MetricSnapshotUpdate) SetFixCount(v int) *MetricSnapshotUpdate {
	_u.mutation.ResetFixCount()
	_u.mutation.SetFixCount(v)
	return _u
}

// SetNillableFixCount sets the "fix_count" field if the given value is not nil.
func (_u *MetricSnapshotUpdate) SetNillableFixCount(v *int) *MetricSnapshotUpdate {
	if v != nil {
		_u.SetFixCount(*v)
	}
	return _u
}

// AddFixCount adds value to the "fix_count" field.
func (_u *MetricSnapshotUpdate) AddFixCount(v int) *MetricSnapshotUpdate {
	_u.mutation.AddFixCount(v)
	return _u
}

// ClearFixCount clears the value of the "fix_count" field.
func (_u *MetricSnapshotUpdate) ClearFixCount() *MetricSnapshotUpdate {
	_u.mutation.ClearFixCount()
	return _u
}

// SetDocsCount sets the "docs_count" field.
func (_u *MetricSnapshotUpdate) SetDocsCount(v int) *MetricSnapshotUpdate {
	_u.mutation.ResetDocsCount()
	_u.mutation.SetDocsCount(v)
	return _u
}

// SetNillableDocsCount sets the "docs_count" field if the given value is not nil.
func (_u *MetricSnapshotUpdate) SetNillableDocsCount(v *int) *MetricSnapshotUpdate {
	if v != nil {
		_u.SetDocsCount(*v)
	}
	return _u
}

// AddDocsCount adds value to the "docs_count" field.
func (_u *MetricSnapshotUpdate) AddDocsCount(v int) *MetricSnapshotUpdate {
	_u.mutation.AddDocsCount(v)
	return _u
}

// ClearDocsCount clears the value of the "docs_count" field.
func (_u *MetricSnapshotUpdate) ClearDocsCount() *MetricSnapshotUpdate {
	_u.mutation.ClearDocsCount()
	return _u
}

// SetChoreCount sets the "chore_count" field.
func (_u *MetricSnapshotUpdate) SetChoreCount(v int) *MetricSnapshotUpdate {
	_u.mutation.ResetChoreCount()
	_u.mutation.SetChoreCount(v)
	return _u
}

// SetNillableChoreCount sets the "chore_count" field if the given value is not nil.
func (_u *MetricSnapshotUpdate) SetNillableChoreCount(v *int) *MetricSnapshotUpdate {
	if v != nil {
		_u.SetChoreCount(*v)
	}
	return _u
}

// AddChoreCount adds value to the "chore_count" field.
func (_u *MetricSnapshotUpdate) AddChoreCount(v int) *MetricSnapshotUpdate {
	_u.mutation.AddChoreCount(v)
	return _u
}

// ClearChoreCount clears the value of the "chore_count" field.
func (_u *MetricSnapshotUpdate) ClearChoreCount() *MetricSnapshotUpdate {
	_u.mutation.ClearChoreCount()
	return _u
}

// SetOtherCommitCount sets the "other_commit_count" field.
func (_u *MetricSnapshotUpdate) SetOtherCommitCount(v int) *MetricSnapshotUpdate {
	_u.mutation.ResetOtherCommitCount()
	_u.mutation.SetOtherCommitCount(v)
	return _u
}

// SetNillableOtherCommitCount sets the "other_commit_count" field if the given value is not nil.
func (_u *MetricSnapshotUpdate) SetNillableOtherCommitCount(v *int) *MetricSnapshotUpdate {
	if v != nil {
		_u.SetOtherCommitCount(*v)
	}
	return _u
}

// AddOtherCommitCount adds value to the "other_commit_count" field.
func (_u *MetricSnapshotUpdate) AddOtherCommitCount(v int) *MetricSnapshotUpdate {
	_u.mutation.AddOtherCommitCount(v)
	return _u
}

// ClearOtherCommitCount clears the value of the "other_commit_count" field.
func (_u *MetricSnapshotUpdate) ClearOtherCommitCount() *MetricSnapshotUpdate {
	_u.mutation.ClearOtherCommitCount()
	return _u
}

// SetTotalCommitsFetched sets the "total_commits_fetched" field.
func (_u *MetricSnapshotUpdate) SetTotalCommitsFetched(v int) *MetricSnapshotUpdate {
	_u.mutation.ResetTotalCommitsFetched()
	_u.mutation.SetTotalCommitsFetched(v)
	return _u
}

// SetNillableTotalCommitsFetched sets the "total_commits_fetched" field if the given value is not nil.
func (_u *MetricSnapshotUpdate) SetNillableTotalCommitsFetched(v *int) *MetricSnapshotUpdate {
	if v != nil {
		_u.SetTotalCommitsFetched(*v)
	}
	return _u
}

// AddTotalCommitsFetched adds value to the "total_commits_fetched" field.
func (_u *MetricSnapshotUpdate) AddTotalCommitsFetched(v int) *MetricSnapshotUpdate {
	_u.mutation.AddTotalCommitsFetched(v)
	return _u
}

// ClearTotalCommitsFetched clears the value of the "total_commits_fetched" field.
func (_u *MetricSnapshotUpdate) ClearTotalCommitsFetched() *MetricSnapshotUpdate {
	_u.mutation.ClearTotalCommitsFetched()
	return _u
}

// SetReleaseCount sets the "release_count" field.
func (_u *MetricSnapshotUpdate) SetReleaseCount(v int) *MetricSnapshotUpdate {
	_u.mutation.ResetReleaseCount()
	_u.mutation.SetReleaseCount(v)
	return _u
}

// SetNillableReleaseCount sets the "release_count" field if the given value is not nil.
func (_u *MetricSnapshotUpdate) SetNillableReleaseCount(v *int) *MetricSnapshotUpdate {
	if v != nil {
		_u.SetReleaseCount(*v)
	}
	return _u
}

// AddReleaseCount adds value to the "release_count" field.
func (_u *MetricSnapshotUpdate) AddReleaseCount(v int) *MetricSnapshotUpdate {
	_u.mutation.AddReleaseCount(v)
	return _u
}

// ClearReleaseCount clears the value of the "release_count" field.
func (_u *MetricSnapshotUpdate) ClearReleaseCount() *MetricSnapshotUpdate {
	_u.mutation.ClearReleaseCount()
	return _u
}

// SetAvgLeadTimeHours sets the "avg_lead_time_hours" field.
func (_u *MetricSnapshotUpdate) SetAvgLeadTimeHours(v float64) *MetricSnapshotUpdate {
	_u.mutation.ResetAvgLeadTimeHours()
	_u.mutation.SetAvgLeadTimeHours(v)
	return _u
}

// SetNillableAvgLeadTimeHours sets the "avg_lead_time_hours" field if the given value is not nil.
func (_u *MetricSnapshotUpdate) SetNillableAvgLeadTimeHours(v *float64) *MetricSnapshotUpdate {
	if v != nil {
		_u.SetAvgLeadTimeHours(*v)
	}
	return _u
}

// AddAvgLeadTimeHours adds value to the "avg_lead_time_hours" field.
func (_u *MetricSnapshotUpdate) AddAvgLeadTimeHours(v float64) *MetricSnapshotUpdate {
	_u.mutation.AddAvgLeadTimeHours(v)
	return _u
}

// ClearAvgLeadTimeHours clears the value of the "avg_lead_time_hours" field.
func (_u *MetricSnapshotUpdate) ClearAvgLeadTimeHours() *MetricSnapshotUpdate {
	_u.mutation.ClearAvgLeadTimeHours()
	return _u
}

// SetWorkflowSuccessCount sets the "workflow_success_count" field.
func (_u *MetricSnapshotUpdate) SetWorkflowSuccessCount(v int) *MetricSnapshotUpdate {
	_u.mutation.ResetWorkflowSuccessCount()
	_u.mutation.SetWorkflowSuccessCount(v)
	return _u
}

// SetNillableWorkflowSuccessCount sets the "workflow_success_count" field if the given value is not nil.
func (_u *MetricSnapshotUpdate) SetNillableWorkflowSuccessCount(v *int) *MetricSnapshotUpdate {
	if v != nil {
		_u.SetWorkflowSuccessCount(*v)
	}
	return _u
}

// AddWorkflowSuccessCount adds value to the "workflow_success_count" field.
func (_u *MetricSnapshotUpdate) AddWorkflowSuccessCount(v int) *MetricSnapshotUpdate {
	_u.mutation.AddWorkflowSuccessCount(v)
	return _u
}

// ClearWorkflowSuccessCount clears the value of the "workflow_success_count" field.
func (_u *MetricSnapshotUpdate) ClearWorkflowSuccessCount() *MetricSnapshotUpdate {
	_u.mutation.ClearWorkflowSuccessCount()
	return _u
}

// SetWorkflowFailureCount sets the "workflow_failure_count" field.
func (_u *MetricSnapshotUpdate) SetWorkflowFailureCount(v int) *MetricSnapshotUpdate {
	_u.mutation.ResetWorkflowFailureCount()
	_u.mutation.SetWorkflowFailureCount(v)
	return _u
}

// SetNillableWorkflowFailureCount sets the "workflow_failure_count" field if the given value is not nil.
func (_u *MetricSnapshotUpdate) SetNillableWorkflowFailureCount(v *int) *MetricSnapshotUpdate {
	if v != nil {
		_u.SetWorkflowFailureCount(*v)
	}
	return _u
}

// AddWorkflowFailureCount adds value to the "workflow_failure_count" field.
func (_u *MetricSnapshotUpdate) AddWorkflowFailureCount(v int) *MetricSnapshotUpdate {
	_u.mutation.AddWorkflowFailureCount(v)
	return _u
}

// ClearWorkflowFailureCount clears the value of the "workflow_failure_count" field.
func (_u *MetricSnapshotUpdate) ClearWorkflowFailureCount() *MetricSnapshotUpdate {
	_u.mutation.ClearWorkflowFailureCount()
	return _u
}

// SetWorkflowStatus sets the "workflow_status" field.
func (_u *MetricSnapshotUpdate) SetWorkflowStatus(v string) *MetricSnapshotUpdate {
	_u.mutation.SetWorkflowStatus(v)
	return _u
}

// SetNillableWorkflowStatus sets the "workflow_status" field if the given value is not nil.
func (_u *MetricSnapshotUpdate) SetNillableWorkflowStatus(v *string) *MetricSnapshotUpdate {
	if v != nil {
		_u.SetWorkflowStatus(*v)
	}
	return _u
}

// ClearWorkflowStatus clears the value of the "workflow_status" field.
func (_u *MetricSnapshotUpdate) ClearWorkflowStatus() *MetricSnapshotUpdate {
	_u.mutation.ClearWorkflowStatus()
	return _u
}

// Mutation returns the MetricSnapshotMutation object of the builder.
func (_u *MetricSnapshotUpdate) Mutation() *MetricSnapshotMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MetricSnapshotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MetricSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MetricSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MetricSnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MetricSnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(metricsnapshot.Table, metricsnapshot.Columns, sqlgraph.NewFieldSpec(metricsnapshot.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RepoID(); ok {
		_spec.SetField(metricsnapshot.FieldRepoID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRepoID(); ok {
		_spec.AddField(metricsnapshot.FieldRepoID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(metricsnapshot.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FeatCount(); ok {
		_spec.SetField(metricsnapshot.FieldFeatCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFeatCount(); ok {
		_spec.AddField(metricsnapshot.FieldFeatCount, field.TypeInt, value)
	}
	if _u.mutation.FeatCountCleared() {
		_spec.ClearField(metricsnapshot.FieldFeatCount, field.TypeInt)
	}
	if value, ok := _u.mutation.FixCount(); ok {
		_spec.SetField(metricsnapshot.FieldFixCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFixCount(); ok {
		_spec.AddField(metricsnapshot.FieldFixCount, field.TypeInt, value)
	}
	if _u.mutation.FixCountCleared() {
		_spec.ClearField(metricsnapshot.FieldFixCount, field.TypeInt)
	}
	if value, ok := _u.mutation.DocsCount(); ok {
		_spec.SetField(metricsnapshot.FieldDocsCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDocsCount(); ok {
		_spec.AddField(metricsnapshot.FieldDocsCount, field.TypeInt, value)
	}
	if _u.mutation.DocsCountCleared() {
		_spec.ClearField(metricsnapshot.FieldDocsCount, field.TypeInt)
	}
	if value, ok := _u.mutation.ChoreCount(); ok {
		_spec.SetField(metricsnapshot.FieldChoreCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChoreCount(); ok {
		_spec.AddField(metricsnapshot.FieldChoreCount, field.TypeInt, value)
	}
	if _u.mutation.ChoreCountCleared() {
		_spec.ClearField(metricsnapshot.FieldChoreCount, field.TypeInt)
	}
	if value, ok := _u.mutation.OtherCommitCount(); ok {
		_spec.SetField(metricsnapshot.FieldOtherCommitCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOtherCommitCount(); ok {
		_spec.AddField(metricsnapshot.FieldOtherCommitCount, field.TypeInt, value)
	}
	if _u.mutation.OtherCommitCountCleared() {
		_spec.ClearField(metricsnapshot.FieldOtherCommitCount, field.TypeInt)
	}
	if value, ok := _u.mutation.TotalCommitsFetched(); ok {
		_spec.SetField(metricsnapshot.FieldTotalCommitsFetched, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalCommitsFetched(); ok {
		_spec.AddField(metricsnapshot.FieldTotalCommitsFetched, field.TypeInt, value)
	}
	if _u.mutation.TotalCommitsFetchedCleared() {
		_spec.ClearField(metricsnapshot.FieldTotalCommitsFetched, field.TypeInt)
	}
	if value, ok := _u.mutation.ReleaseCount(); ok {
		_spec.SetField(metricsnapshot.FieldReleaseCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReleaseCount(); ok {
		_spec.AddField(metricsnapshot.FieldReleaseCount, field.TypeInt, value)
	}
	if _u.mutation.ReleaseCountCleared() {
		_spec.ClearField(metricsnapshot.FieldReleaseCount, field.TypeInt)
	}
	if value, ok := _u.mutation.AvgLeadTimeHours(); ok {
		_spec.SetField(metricsnapshot.FieldAvgLeadTimeHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAvgLeadTimeHours(); ok {
		_spec.AddField(metricsnapshot.FieldAvgLeadTimeHours, field.TypeFloat64, value)
	}
	if _u.mutation.AvgLeadTimeHoursCleared() {
		_spec.ClearField(metricsnapshot.FieldAvgLeadTimeHours, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WorkflowSuccessCount(); ok {
		_spec.SetField(metricsnapshot.FieldWorkflowSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWorkflowSuccessCount(); ok {
		_spec.AddField(metricsnapshot.FieldWorkflowSuccessCount, field.TypeInt, value)
	}
	if _u.mutation.WorkflowSuccessCountCleared() {
		_spec.ClearField(metricsnapshot.FieldWorkflowSuccessCount, field.TypeInt)
	}
	if value, ok := _u.mutation.WorkflowFailureCount(); ok {
		_spec.SetField(metricsnapshot.FieldWorkflowFailureCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWorkflowFailureCount(); ok {
		_spec.AddField(metricsnapshot.FieldWorkflowFailureCount, field.TypeInt, value)
	}
	if _u.mutation.WorkflowFailureCountCleared() {
		_spec.ClearField(metricsnapshot.FieldWorkflowFailureCount, field.TypeInt)
	}
	if value, ok := _u.mutation.WorkflowStatus(); ok {
		_spec.SetField(metricsnapshot.FieldWorkflowStatus, field.TypeString, value)
	}
	if _u.mutation.WorkflowStatusCleared() {
		_spec.ClearField(metricsnapshot.FieldWorkflowStatus, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{metricsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MetricSnapshotUpdateOne is the builder for updating a single MetricSnapshot entity.
type MetricSnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MetricSnapshotMutation
}

// SetRepoID sets the "repo_id" field.
func (_u *MetricSnapshotUpdateOne) SetRepoID(v int) *MetricSnapshotUpdateOne {
	_u.mutation.ResetRepoID()
	_u.mutation.SetRepoID(v)
	return _u
}

// SetNillableRepoID sets the "repo_id" field if the given value is not nil.
func (_u *MetricSnapshotUpdateOne) SetNillableRepoID(v *int) *MetricSnapshotUpdateOne {
	if v != nil {
		_u.SetRepoID(*v)
	}
	return _u
}

// AddRepoID adds value to the "repo_id" field.
func (_u *MetricSnapshotUpdateOne) AddRepoID(v int) *MetricSnapshotUpdateOne {
	_u.mutation.AddRepoID(v)
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *MetricSnapshotUpdateOne) SetTimestamp(v time.Time) *MetricSnapshotUpdateOne {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *MetricSnapshotUpdateOne) SetNillableTimestamp(v *time.Time) *MetricSnapshotUpdateOne {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetFeatCount sets the "feat_count" field.
func (_u *MetricSnapshotUpdateOne) SetFeatCount(v int) *MetricSnapshotUpdateOne {
	_u.mutation.ResetFeatCount()
	_u.mutation.SetFeatCount(v)
	return _u
}

// SetNillableFeatCount sets the "feat_count" field if the given value is not nil.
func (_u *MetricSnapshotUpdateOne) SetNillableFeatCount(v *int) *MetricSnapshotUpdateOne {
	if v != nil {
		_u.SetFeatCount(*v)
	}
	return _u
}

// AddFeatCount adds value to the "feat_count" field.
func (_u *MetricSnapshotUpdateOne) AddFeatCount(v int) *MetricSnapshotUpdateOne {
	_u.mutation.AddFeatCount(v)
	return _u
}

// ClearFeatCount clears the value of the "feat_count" field.
func (_u *MetricSnapshotUpdateOne) ClearFeatCount() *MetricSnapshotUpdateOne {
	_u.mutation.ClearFeatCount()
	return _u
}

// SetFixCount sets the "fix_count" field.
func (_u *MetricSnapshotUpdateOne) SetFixCount(v int) *MetricSnapshotUpdateOne {
	_u.mutation.ResetFixCount()
	_u.mutation.SetFixCount(v)
	return _u
}

// SetNillableFixCount sets the "fix_count" field if the given value is not nil.
func (_u *MetricSnapshotUpdateOne) SetNillableFixCount(v *int) *MetricSnapshotUpdateOne {
	if v != nil {
		_u.SetFixCount(*v)
	}
	return _u
}

// AddFixCount adds value to the "fix_count" field.
func (_u *MetricSnapshotUpdateOne) AddFixCount(v int) *MetricSnapshotUpdateOne {
	_u.mutation.AddFixCount(v)
	return _u
}

// ClearFixCount clears the value of the "fix_count" field.
func (_u *MetricSnapshotUpdateOne) ClearFixCount() *MetricSnapshotUpdateOne {
	_u.mutation.ClearFixCount()
	return _u
}

// SetDocsCount sets the "docs_count" field.
func (_u *MetricSnapshotUpdateOne) SetDocsCount(v int) *MetricSnapshotUpdateOne {
	_u.mutation.ResetDocsCount()
	_u.mutation.SetDocsCount(v)
	return _u
}

// SetNillableDocsCount sets the "docs_count" field if the given value is not nil.
func (_u *MetricSnapshotUpdateOne) SetNillableDocsCount(v *int) *MetricSnapshotUpdateOne {
	if v != nil {
		_u.SetDocsCount(*v)
	}
	return _u
}

// AddDocsCount adds value to the "docs_count" field.
func (_u *MetricSnapshotUpdateOne) AddDocsCount(v int) *MetricSnapshotUpdateOne {
	_u.mutation.AddDocsCount(v)
	return _u
}

// ClearDocsCount clears the value of the "docs_count" field.
func (_u *MetricSnapshotUpdateOne) ClearDocsCount() *MetricSnapshotUpdateOne {
	_u.mutation.ClearDocsCount()
	return _u
}

// SetChoreCount sets the "chore_count" field.
func (_u *MetricSnapshotUpdateOne) SetChoreCount(v int) *MetricSnapshotUpdateOne {
	_u.mutation.ResetChoreCount()
	_u.mutation.SetChoreCount(v)
	return _u
}

// SetNillableChoreCount sets the "chore_count" field if the given value is not nil.
func (_u *MetricSnapshotUpdateOne) SetNillableChoreCount(v *int) *MetricSnapshotUpdateOne {
	if v != nil {
		_u.SetChoreCount(*v)
	}
	return _u
}

// AddChoreCount adds value to the "chore_count" field.
func (_u *MetricSnapshotUpdateOne) AddChoreCount(v int) *MetricSnapshotUpdateOne {
	_u.mutation.AddChoreCount(v)
	return _u
}

// ClearChoreCount clears the value of the "chore_count" field.
func (_u *MetricSnapshotUpdateOne) ClearChoreCount() *MetricSnapshotUpdateOne {
	_u.mutation.ClearChoreCount()
	return _u
}

// SetOtherCommitCount sets the "other_commit_count" field.
func (_u *MetricSnapshotUpdateOne) SetOtherCommitCount(v int) *MetricSnapshotUpdateOne {
	_u.mutation.ResetOtherCommitCount()
	_u.mutation.SetOtherCommitCount(v)
	return _u
}

// SetNillableOtherCommitCount sets the "other_commit_count" field if the given value is not nil.
func (_u *MetricSnapshotUpdateOne) SetNillableOtherCommitCount(v *int) *MetricSnapshotUpdateOne {
	if v != nil {
		_u.SetOtherCommitCount(*v)
	}
	return _u
}

// AddOtherCommitCount adds value to the "other_commit_count" field.
func (_u *MetricSnapshotUpdateOne) AddOtherCommitCount(v int) *MetricSnapshotUpdateOne {
	_u.mutation.AddOtherCommitCount(v)
	return _u
}

// ClearOtherCommitCount clears the value of the "other_commit_count" field.
func (_u *MetricSnapshotUpdateOne) ClearOtherCommitCount() *MetricSnapshotUpdateOne {
	_u.mutation.ClearOtherCommitCount()
	return _u
}

// SetTotalCommitsFetched sets the "total_commits_fetched" field.
func (_u *MetricSnapshotUpdateOne) SetTotalCommitsFetched(v int) *MetricSnapshotUpdateOne {
	_u.mutation.ResetTotalCommitsFetched()
	_u.mutation.SetTotalCommitsFetched(v)
	return _u
}

// SetNillableTotalCommitsFetched sets the "total_commits_fetched" field if the given value is not nil.
func (_u *MetricSnapshotUpdateOne) SetNillableTotalCommitsFetched(v *int) *MetricSnapshotUpdateOne {
	if v != nil {
		_u.SetTotalCommitsFetched(*v)
	}
	return _u
}

// AddTotalCommitsFetched adds value to the "total_commits_fetched" field.
func (_u *MetricSnapshotUpdateOne) AddTotalCommitsFetched(v int) *MetricSnapshotUpdateOne {
	_u.mutation.AddTotalCommitsFetched(v)
	return _u
}

// ClearTotalCommitsFetched clears the value of the "total_commits_fetched" field.
func (_u *MetricSnapshotUpdateOne) ClearTotalCommitsFetched() *MetricSnapshotUpdateOne {
	_u.mutation.ClearTotalCommitsFetched()
	return _u
}

// SetReleaseCount sets the "release_count" field.
func (_u *MetricSnapshotUpdateOne) SetReleaseCount(v int) *MetricSnapshotUpdateOne {
	_u.mutation.ResetReleaseCount()
	_u.mutation.SetReleaseCount(v)
	return _u
}

// SetNillableReleaseCount sets the "release_count" field if the given value is not nil.
func (_u *MetricSnapshotUpdateOne) SetNillableReleaseCount(v *int) *MetricSnapshotUpdateOne {
	if v != nil {
		_u.SetReleaseCount(*v)
	}
	return _u
}

// AddReleaseCount adds value to the "release_count" field.
func (_u *MetricSnapshotUpdateOne) AddReleaseCount(v int) *MetricSnapshotUpdateOne {
	_u.mutation.AddReleaseCount(v)
	return _u
}

// ClearReleaseCount clears the value of the "release_count" field.
func (_u *MetricSnapshotUpdateOne) ClearReleaseCount() *MetricSnapshotUpdateOne {
	_u.mutation.ClearReleaseCount()
	return _u
}

// SetAvgLeadTimeHours sets the "avg_lead_time_hours" field.
func (_u *MetricSnapshotUpdateOne) SetAvgLeadTimeHours(v float64) *MetricSnapshotUpdateOne {
	_u.mutation.ResetAvgLeadTimeHours()
	_u.mutation.SetAvgLeadTimeHours(v)
	return _u
}

// SetNillableAvgLeadTimeHours sets the "avg_lead_time_hours" field if the given value is not nil.
func (_u *MetricSnapshotUpdateOne) SetNillableAvgLeadTimeHours(v *float64) *MetricSnapshotUpdateOne {
	if v != nil {
		_u.SetAvgLeadTimeHours(*v)
	}
	return _u
}

// AddAvgLeadTimeHours adds value to the "avg_lead_time_hours" field.
func (_u *MetricSnapshotUpdateOne) AddAvgLeadTimeHours(v float64) *MetricSnapshotUpdateOne {
	_u.mutation.AddAvgLeadTimeHours(v)
	return _u
}

// ClearAvgLeadTimeHours clears the value of the "avg_lead_time_hours" field.
func (_u *MetricSnapshotUpdateOne) ClearAvgLeadTimeHours() *MetricSnapshotUpdateOne {
	_u.mutation.ClearAvgLeadTimeHours()
	return _u
}

// SetWorkflowSuccessCount sets the "workflow_success_count" field.
func (_u *MetricSnapshotUpdateOne) SetWorkflowSuccessCount(v int) *MetricSnapshotUpdateOne {
	_u.mutation.ResetWorkflowSuccessCount()
	_u.mutation.SetWorkflowSuccessCount(v)
	return _u
}

// SetNillableWorkflowSuccessCount sets the "workflow_success_count" field if the given value is not nil.
func (_u *MetricSnapshotUpdateOne) SetNillableWorkflowSuccessCount(v *int) *MetricSnapshotUpdateOne {
	if v != nil {
		_u.SetWorkflowSuccessCount(*v)
	}
	return _u
}

// AddWorkflowSuccessCount adds value to the "workflow_success_count" field.
func (_u *MetricSnapshotUpdateOne) AddWorkflowSuccessCount(v int) *MetricSnapshotUpdateOne {
	_u.mutation.AddWorkflowSuccessCount(v)
	return _u
}

// ClearWorkflowSuccessCount clears the value of the "workflow_success_count" field.
func (_u *MetricSnapshotUpdateOne) ClearWorkflowSuccessCount() *MetricSnapshotUpdateOne {
	_u.mutation.ClearWorkflowSuccessCount()
	return _u
}

// SetWorkflowFailureCount sets the "workflow_failure_count" field.
func (_u *MetricSnapshotUpdateOne) SetWorkflowFailureCount(v int) *MetricSnapshotUpdateOne {
	_u.mutation.ResetWorkflowFailureCount()
	_u.mutation.SetWorkflowFailureCount(v)
	return _u
}

// SetNillableWorkflowFailureCount sets the "workflow_failure_count" field if the given value is not nil.
func (_u *MetricSnapshotUpdateOne) SetNillableWorkflowFailureCount(v *int) *MetricSnapshotUpdateOne {
	if v != nil {
		_u.SetWorkflowFailureCount(*v)
	}
	return _u
}

// AddWorkflowFailureCount adds value to the "workflow_failure_count" field.
func (_u *MetricSnapshotUpdateOne) AddWorkflowFailureCount(v int) *MetricSnapshotUpdateOne {
	_u.mutation.AddWorkflowFailureCount(v)
	return _u
}

// ClearWorkflowFailureCount clears the value of the "workflow_failure_count" field.
func (_u *MetricSnapshotUpdateOne) ClearWorkflowFailureCount() *MetricSnapshotUpdateOne {
	_u.mutation.ClearWorkflowFailureCount()
	return _u
}

// SetWorkflowStatus sets the "workflow_status" field.
func (_u *MetricSnapshotUpdateOne) SetWorkflowStatus(v string) *MetricSnapshotUpdateOne {
	_u.mutation.SetWorkflowStatus(v)
	return _u
}

// SetNillableWorkflowStatus sets the "workflow_status" field if the given value is not nil.
func (_u *MetricSnapshotUpdateOne) SetNillableWorkflowStatus(v *string) *MetricSnapshotUpdateOne {
	if v != nil {
		_u.SetWorkflowStatus(*v)
	}
	return _u
}

// ClearWorkflowStatus clears the value of the "workflow_status" field.
func (_u *MetricSnapshotUpdateOne) ClearWorkflowStatus() *MetricSnapshotUpdateOne {
	_u.mutation.ClearWorkflowStatus()
	return _u
}

// Mutation returns the MetricSnapshotMutation object of the builder.
func (_u *MetricSnapshotUpdateOne) Mutation() *MetricSnapshotMutation {
	return _u.mutation
}

// Where appends a list predicates to the MetricSnapshotUpdate builder.
func (_u *MetricSnapshotUpdateOne) Where(ps ...predicate.MetricSnapshot) *MetricSnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MetricSnapshotUpdateOne) Select(field string, fields ...string) *MetricSnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MetricSnapshot entity.
func (_u *MetricSnapshotUpdateOne) Save(ctx context.Context) (*MetricSnapshot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MetricSnapshotUpdateOne) SaveX(ctx context.Context) *MetricSnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MetricSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MetricSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MetricSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *MetricSnapshot, err error) {
	_spec := sqlgraph.NewUpdateSpec(metricsnapshot.Table, metricsnapshot.Columns, sqlgraph.NewFieldSpec(metricsnapshot.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MetricSnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, metricsnapshot.FieldID)
		for _, f := range fields {
			if !metricsnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != metricsnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RepoID(); ok {
		_spec.SetField(metricsnapshot.FieldRepoID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRepoID(); ok {
		_spec.AddField(metricsnapshot.FieldRepoID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(metricsnapshot.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FeatCount(); ok {
		_spec.SetField(metricsnapshot.FieldFeatCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFeatCount(); ok {
		_spec.AddField(metricsnapshot.FieldFeatCount, field.TypeInt, value)
	}
	if _u.mutation.FeatCountCleared() {
		_spec.ClearField(metricsnapshot.FieldFeatCount, field.TypeInt)
	}
	if value, ok := _u.mutation.FixCount(); ok {
		_spec.SetField(metricsnapshot.FieldFixCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFixCount(); ok {
		_spec.AddField(metricsnapshot.FieldFixCount, field.TypeInt, value)
	}
	if _u.mutation.FixCountCleared() {
		_spec.ClearField(metricsnapshot.FieldFixCount, field.TypeInt)
	}
	if value, ok := _u.mutation.DocsCount(); ok {
		_spec.SetField(metricsnapshot.FieldDocsCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDocsCount(); ok {
		_spec.AddField(metricsnapshot.FieldDocsCount, field.TypeInt, value)
	}
	if _u.mutation.DocsCountCleared() {
		_spec.ClearField(metricsnapshot.FieldDocsCount, field.TypeInt)
	}
	if value, ok := _u.mutation.ChoreCount(); ok {
		_spec.SetField(metricsnapshot.FieldChoreCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChoreCount(); ok {
		_spec.AddField(metricsnapshot.FieldChoreCount, field.TypeInt, value)
	}
	if _u.mutation.ChoreCountCleared() {
		_spec.ClearField(metricsnapshot.FieldChoreCount, field.TypeInt)
	}
	if value, ok := _u.mutation.OtherCommitCount(); ok {
		_spec.SetField(metricsnapshot.FieldOtherCommitCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOtherCommitCount(); ok {
		_spec.AddField(metricsnapshot.FieldOtherCommitCount, field.TypeInt, value)
	}
	if _u.mutation.OtherCommitCountCleared() {
		_spec.ClearField(metricsnapshot.FieldOtherCommitCount, field.TypeInt)
	}
	if value, ok := _u.mutation.TotalCommitsFetched(); ok {
		_spec.SetField(metricsnapshot.FieldTotalCommitsFetched, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalCommitsFetched(); ok {
		_spec.AddField(metricsnapshot.FieldTotalCommitsFetched, field.TypeInt, value)
	}
	if _u.mutation.TotalCommitsFetchedCleared() {
		_spec.ClearField(metricsnapshot.FieldTotalCommitsFetched, field.TypeInt)
	}
	if value, ok := _u.mutation.ReleaseCount(); ok {
		_spec.SetField(metricsnapshot.FieldReleaseCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReleaseCount(); ok {
		_spec.AddField(metricsnapshot.FieldReleaseCount, field.TypeInt, value)
	}
	if _u.mutation.ReleaseCountCleared() {
		_spec.ClearField(metricsnapshot.FieldReleaseCount, field.TypeInt)
	}
	if value, ok := _u.mutation.AvgLeadTimeHours(); ok {
		_spec.SetField(metricsnapshot.FieldAvgLeadTimeHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAvgLeadTimeHours(); ok {
		_spec.AddField(metricsnapshot.FieldAvgLeadTimeHours, field.TypeFloat64, value)
	}
	if _u.mutation.AvgLeadTimeHoursCleared() {
		_spec.ClearField(metricsnapshot.FieldAvgLeadTimeHours, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WorkflowSuccessCount(); ok {
		_spec.SetField(metricsnapshot.FieldWorkflowSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWorkflowSuccessCount(); ok {
		_spec.AddField(metricsnapshot.FieldWorkflowSuccessCount, field.TypeInt, value)
	}
	if _u.mutation.WorkflowSuccessCountCleared() {
		_spec.ClearField(metricsnapshot.FieldWorkflowSuccessCount, field.TypeInt)
	}
	if value, ok := _u.mutation.WorkflowFailureCount(); ok {
		_spec.SetField(metricsnapshot.FieldWorkflowFailureCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWorkflowFailureCount(); ok {
		_spec.AddField(metricsnapshot.FieldWorkflowFailureCount, field.TypeInt, value)
	}
	if _u.mutation.WorkflowFailureCountCleared() {
		_spec.ClearField(metricsnapshot.FieldWorkflowFailureCount, field.TypeInt)
	}
	if value, ok := _u.mutation.WorkflowStatus(); ok {
		_spec.SetField(metricsnapshot.FieldWorkflowStatus, field.TypeString, value)
	}
	if _u.mutation.WorkflowStatusCleared() {
		_spec.ClearField(metricsnapshot.FieldWorkflowStatus, field.TypeString)
	}
	_node = &MetricSnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{metricsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
