// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"gitlens/ent/metricsnapshot"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// MetricSnapshot is the model entity for the MetricSnapshot schema.
type MetricSnapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RepoID holds the value of the "repo_id" field.
	RepoID int `json:"repo_id,omitempty"`
	// Timestamp holds the value of the "timestamp" field.
	Timestamp time.Time `json:"timestamp,omitempty"`
	// FeatCount holds the value of the "feat_count" field.
	FeatCount int `json:"feat_count,omitempty"`
	// FixCount holds the value of the "fix_count" field.
	FixCount int `json:"fix_count,omitempty"`
	// DocsCount holds the value of the "docs_count" field.
	DocsCount int `json:"docs_count,omitempty"`
	// ChoreCount holds the value of the "chore_count" field.
	ChoreCount int `json:"chore_count,omitempty"`
	// OtherCommitCount holds the value of the "other_commit_count" field.
	OtherCommitCount int `json:"other_commit_count,omitempty"`
	// TotalCommitsFetched holds the value of the "total_commits_fetched" field.
	TotalCommitsFetched int `json:"total_commits_fetched,omitempty"`
	// ReleaseCount holds the value of the "release_count" field.
	ReleaseCount int `json:"release_count,omitempty"`
	// AvgLeadTimeHours holds the value of the "avg_lead_time_hours" field.
	AvgLeadTimeHours float64 `json:"avg_lead_time_hours,omitempty"`
	// WorkflowSuccessCount holds the value of the "workflow_success_count" field.
	WorkflowSuccessCount int `json:"workflow_success_count,omitempty"`
	// WorkflowFailureCount holds the value of the "workflow_failure_count" field.
	WorkflowFailureCount int `json:"workflow_failure_count,omitempty"`
	// WorkflowStatus holds the value of the "workflow_status" field.
	WorkflowStatus string `json:"workflow_status,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MetricSnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case metricsnapshot.FieldAvgLeadTimeHours:
			values[i] = new(sql.NullFloat64)
		case metricsnapshot.FieldID, metricsnapshot.FieldRepoID, metricsnapshot.FieldFeatCount, metricsnapshot.FieldFixCount, metricsnapshot.FieldDocsCount, metricsnapshot.FieldChoreCount, metricsnapshot.FieldOtherCommitCount, metricsnapshot.FieldTotalCommitsFetched, metricsnapshot.FieldReleaseCount, metricsnapshot.FieldWorkflowSuccessCount, metricsnapshot.FieldWorkflowFailureCount:
			values[i] = new(sql.NullInt64)
		case metricsnapshot.FieldWorkflowStatus:
			values[i] = new(sql.NullString)
		case metricsnapshot.FieldTimestamp:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MetricSnapshot fields.
func (_m *MetricSnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case metricsnapshot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case metricsnapshot.FieldRepoID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field repo_id", values[i])
			} else if value.Valid {
				_m.RepoID = int(value.Int64)
			}
		case metricsnapshot.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.Time
			}
		case metricsnapshot.FieldFeatCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field feat_count", values[i])
			} else if value.Valid {
				_m.FeatCount = int(value.Int64)
			}
		case metricsnapshot.FieldFixCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field fix_count", values[i])
			} else if value.Valid {
				_m.FixCount = int(value.Int64)
			}
		case metricsnapshot.FieldDocsCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field docs_count", values[i])
			} else if value.Valid {
				_m.DocsCount = int(value.Int64)
			}
		case metricsnapshot.FieldChoreCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chore_count", values[i])
			} else if value.Valid {
				_m.ChoreCount = int(value.Int64)
			}
		case metricsnapshot.FieldOtherCommitCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field other_commit_count", values[i])
			} else if value.Valid {
				_m.OtherCommitCount = int(value.Int64)
			}
		case metricsnapshot.FieldTotalCommitsFetched:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_commits_fetched", values[i])
			} else if value.Valid {
				_m.TotalCommitsFetched = int(value.Int64)
			}
		case metricsnapshot.FieldReleaseCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field release_count", values[i])
			} else if value.Valid {
				_m.ReleaseCount = int(value.Int64)
			}
		case metricsnapshot.FieldAvgLeadTimeHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field avg_lead_time_hours", values[i])
			} else if value.Valid {
				_m.AvgLeadTimeHours = value.Float64
			}
		case metricsnapshot.FieldWorkflowSuccessCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_success_count", values[i])
			} else if value.Valid {
				_m.WorkflowSuccessCount = int(value.Int64)
			}
		case metricsnapshot.FieldWorkflowFailureCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_failure_count", values[i])
			} else if value.Valid {
				_m.WorkflowFailureCount = int(value.Int64)
			}
		case metricsnapshot.FieldWorkflowStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_status", values[i])
			} else if value.Valid {
				_m.WorkflowStatus = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MetricSnapshot.
// This includes values selected through modifiers, order, etc.
func (_m *MetricSnapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MetricSnapshot.
// Note that you need to call MetricSnapshot.Unwrap() before calling this method if this MetricSnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MetricSnapshot) Update() *MetricSnapshotUpdateOne {
	return NewMetricSnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MetricSnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MetricSnapshot) Unwrap() *MetricSnapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MetricSnapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MetricSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("MetricSnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("repo_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RepoID))
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(_m.Timestamp.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("feat_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.FeatCount))
	builder.WriteString(", ")
	builder.WriteString("fix_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.FixCount))
	builder.WriteString(", ")
	builder.WriteString("docs_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.DocsCount))
	builder.WriteString(", ")
	builder.WriteString("chore_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChoreCount))
	builder.WriteString(", ")
	builder.WriteString("other_commit_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.OtherCommitCount))
	builder.WriteString(", ")
	builder.WriteString("total_commits_fetched=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalCommitsFetched))
	builder.WriteString(", ")
	builder.WriteString("release_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReleaseCount))
	builder.WriteString(", ")
	builder.WriteString("avg_lead_time_hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvgLeadTimeHours))
	builder.WriteString(", ")
	builder.WriteString("workflow_success_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.WorkflowSuccessCount))
	builder.WriteString(", ")
	builder.WriteString("workflow_failure_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.WorkflowFailureCount))
	builder.WriteString(", ")
	builder.WriteString("workflow_status=")
	builder.WriteString(_m.WorkflowStatus)
	builder.WriteByte(')')
	return builder.String()
}

// MetricSnapshots is a parsable slice of MetricSnapshot.
type MetricSnapshots []*MetricSnapshot
