// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gitlens/ent/predicate"
	"gitlens/ent/repository"
	"gitlens/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RepositoryUpdate is the builder for updating Repository entities.
type RepositoryUpdate struct {
	config
	hooks    []Hook
	mutation *RepositoryMutation
}

// Where appends a list predicates to the RepositoryUpdate builder.
func (_u *RepositoryUpdate) Where(ps ...predicate.Repository) *RepositoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGithubID sets the "github_id" field.
func (_u *RepositoryUpdate) SetGithubID(v int64) *RepositoryUpdate {
	_u.mutation.ResetGithubID()
	_u.mutation.SetGithubID(v)
	return _u
}

// SetNillableGithubID sets the "github_id" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableGithubID(v *int64) *RepositoryUpdate {
	if v != nil {
		_u.SetGithubID(*v)
	}
	return _u
}

// AddGithubID adds value to the "github_id" field.
func (_u *RepositoryUpdate) AddGithubID(v int64) *RepositoryUpdate {
	_u.mutation.AddGithubID(v)
	return _u
}

// SetOwner sets the "owner" field.
func (_u *RepositoryUpdate) SetOwner(v string) *RepositoryUpdate {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableOwner(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RepositoryUpdate) SetName(v string) *RepositoryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableName(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFullName sets the "full_name" field.
func (_u *RepositoryUpdate) SetFullName(v string) *RepositoryUpdate {
	_u.mutation.SetFullName(v)
	return _u
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableFullName(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetFullName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RepositoryUpdate) SetDescription(v string) *RepositoryUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableDescription(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RepositoryUpdate) ClearDescription() *RepositoryUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetHTMLURL sets the "html_url" field.
func (_u *RepositoryUpdate) SetHTMLURL(v string) *RepositoryUpdate {
	_u.mutation.SetHTMLURL(v)
	return _u
}

// SetNillableHTMLURL sets the "html_url" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableHTMLURL(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetHTMLURL(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *RepositoryUpdate) SetLanguage(v string) *RepositoryUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableLanguage(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// ClearLanguage clears the value of the "language" field.
func (_u *RepositoryUpdate) ClearLanguage() *RepositoryUpdate {
	_u.mutation.ClearLanguage()
	return _u
}

// SetDefaultBranch sets the "default_branch" field.
func (_u *RepositoryUpdate) SetDefaultBranch(v string) *RepositoryUpdate {
	_u.mutation.SetDefaultBranch(v)
	return _u
}

// SetNillableDefaultBranch sets the "default_branch" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableDefaultBranch(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetDefaultBranch(*v)
	}
	return _u
}

// SetLatestCommitSha sets the "latest_commit_sha" field.
func (_u *RepositoryUpdate) SetLatestCommitSha(v string) *RepositoryUpdate {
	_u.mutation.SetLatestCommitSha(v)
	return _u
}

// SetNillableLatestCommitSha sets the "latest_commit_sha" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableLatestCommitSha(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetLatestCommitSha(*v)
	}
	return _u
}

// ClearLatestCommitSha clears the value of the "latest_commit_sha" field.
func (_u *RepositoryUpdate) ClearLatestCommitSha() *RepositoryUpdate {
	_u.mutation.ClearLatestCommitSha()
	return _u
}

// SetLatestCommitMessage sets the "latest_commit_message" field.
func (_u *RepositoryUpdate) SetLatestCommitMessage(v string) *RepositoryUpdate {
	_u.mutation.SetLatestCommitMessage(v)
	return _u
}

// SetNillableLatestCommitMessage sets the "latest_commit_message" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableLatestCommitMessage(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetLatestCommitMessage(*v)
	}
	return _u
}

// ClearLatestCommitMessage clears the value of the "latest_commit_message" field.
func (_u *RepositoryUpdate) ClearLatestCommitMessage() *RepositoryUpdate {
	_u.mutation.ClearLatestCommitMessage()
	return _u
}

// SetLatestCommitDate sets the "latest_commit_date" field.
func (_u *RepositoryUpdate) SetLatestCommitDate(v time.Time) *RepositoryUpdate {
	_u.mutation.SetLatestCommitDate(v)
	return _u
}

// SetNillableLatestCommitDate sets the "latest_commit_date" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableLatestCommitDate(v *time.Time) *RepositoryUpdate {
	if v != nil {
		_u.SetLatestCommitDate(*v)
	}
	return _u
}

// ClearLatestCommitDate clears the value of the "latest_commit_date" field.
func (_u *RepositoryUpdate) ClearLatestCommitDate() *RepositoryUpdate {
	_u.mutation.ClearLatestCommitDate()
	return _u
}

// SetLatestReleaseTag sets the "latest_release_tag" field.
func (_u *RepositoryUpdate) SetLatestReleaseTag(v string) *RepositoryUpdate {
	_u.mutation.SetLatestReleaseTag(v)
	return _u
}

// SetNillableLatestReleaseTag sets the "latest_release_tag" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableLatestReleaseTag(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetLatestReleaseTag(*v)
	}
	return _u
}

// ClearLatestReleaseTag clears the value of the "latest_release_tag" field.
func (_u *RepositoryUpdate) ClearLatestReleaseTag() *RepositoryUpdate {
	_u.mutation.ClearLatestReleaseTag()
	return _u
}

// SetLatestReleaseName sets the "latest_release_name" field.
func (_u *RepositoryUpdate) SetLatestReleaseName(v string) *RepositoryUpdate {
	_u.mutation.SetLatestReleaseName(v)
	return _u
}

// SetNillableLatestReleaseName sets the "latest_release_name" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableLatestReleaseName(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetLatestReleaseName(*v)
	}
	return _u
}

// ClearLatestReleaseName clears the value of the "latest_release_name" field.
func (_u *RepositoryUpdate) ClearLatestReleaseName() *RepositoryUpdate {
	_u.mutation.ClearLatestReleaseName()
	return _u
}

// SetLatestReleaseDate sets the "latest_release_date" field.
func (_u *RepositoryUpdate) SetLatestReleaseDate(v time.Time) *RepositoryUpdate {
	_u.mutation.SetLatestReleaseDate(v)
	return _u
}

// SetNillableLatestReleaseDate sets the "latest_release_date" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableLatestReleaseDate(v *time.Time) *RepositoryUpdate {
	if v != nil {
		_u.SetLatestReleaseDate(*v)
	}
	return _u
}

// ClearLatestReleaseDate clears the value of the "latest_release_date" field.
func (_u *RepositoryUpdate) ClearLatestReleaseDate() *RepositoryUpdate {
	_u.mutation.ClearLatestReleaseDate()
	return _u
}

// SetWorkflowStatus sets the "workflow_status" field.
func (_u *RepositoryUpdate) SetWorkflowStatus(v string) *RepositoryUpdate {
	_u.mutation.SetWorkflowStatus(v)
	return _u
}

// SetNillableWorkflowStatus sets the "workflow_status" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableWorkflowStatus(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetWorkflowStatus(*v)
	}
	return _u
}

// ClearWorkflowStatus clears the value of the "workflow_status" field.
func (_u *RepositoryUpdate) ClearWorkflowStatus() *RepositoryUpdate {
	_u.mutation.ClearWorkflowStatus()
	return _u
}

// SetWorkflowRunID sets the "workflow_run_id" field.
func (_u *RepositoryUpdate) SetWorkflowRunID(v int64) *RepositoryUpdate {
	_u.mutation.ResetWorkflowRunID()
	_u.mutation.SetWorkflowRunID(v)
	return _u
}

// SetNillableWorkflowRunID sets the "workflow_run_id" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableWorkflowRunID(v *int64) *RepositoryUpdate {
	if v != nil {
		_u.SetWorkflowRunID(*v)
	}
	return _u
}

// AddWorkflowRunID adds value to the "workflow_run_id" field.
func (_u *RepositoryUpdate) AddWorkflowRunID(v int64) *RepositoryUpdate {
	_u.mutation.AddWorkflowRunID(v)
	return _u
}

// ClearWorkflowRunID clears the value of the "workflow_run_id" field.
func (_u *RepositoryUpdate) ClearWorkflowRunID() *RepositoryUpdate {
	_u.mutation.ClearWorkflowRunID()
	return _u
}

// SetTotalCommitsFetched sets the "total_commits_fetched" field.
func (_u *RepositoryUpdate) SetTotalCommitsFetched(v int) *RepositoryUpdate {
	_u.mutation.ResetTotalCommitsFetched()
	_u.mutation.SetTotalCommitsFetched(v)
	return _u
}

// SetNillableTotalCommitsFetched sets the "total_commits_fetched" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableTotalCommitsFetched(v *int) *RepositoryUpdate {
	if v != nil {
		_u.SetTotalCommitsFetched(*v)
	}
	return _u
}

// AddTotalCommitsFetched adds value to the "total_commits_fetched" field.
func (_u *RepositoryUpdate) AddTotalCommitsFetched(v int) *RepositoryUpdate {
	_u.mutation.AddTotalCommitsFetched(v)
	return _u
}

// ClearTotalCommitsFetched clears the value of the "total_commits_fetched" field.
func (_u *RepositoryUpdate) ClearTotalCommitsFetched() *RepositoryUpdate {
	_u.mutation.ClearTotalCommitsFetched()
	return _u
}

// SetFeatCount sets the "feat_count" field.
func (_u *RepositoryUpdate) SetFeatCount(v int) *RepositoryUpdate {
	_u.mutation.ResetFeatCount()
	_u.mutation.SetFeatCount(v)
	return _u
}

// SetNillableFeatCount sets the "feat_count" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableFeatCount(v *int) *RepositoryUpdate {
	if v != nil {
		_u.SetFeatCount(*v)
	}
	return _u
}

// AddFeatCount adds value to the "feat_count" field.
func (_u *RepositoryUpdate) AddFeatCount(v int) *RepositoryUpdate {
	_u.mutation.AddFeatCount(v)
	return _u
}

// ClearFeatCount clears the value of the "feat_count" field.
func (_u *RepositoryUpdate) ClearFeatCount() *RepositoryUpdate {
	_u.mutation.ClearFeatCount()
	return _u
}

// SetFixCount sets the "fix_count" field.
func (_u *RepositoryUpdate) SetFixCount(v int) *RepositoryUpdate {
	_u.mutation.ResetFixCount()
	_u.mutation.SetFixCount(v)
	return _u
}

// SetNillableFixCount sets the "fix_count" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableFixCount(v *int) *RepositoryUpdate {
	if v != nil {
		_u.SetFixCount(*v)
	}
	return _u
}

// AddFixCount adds value to the "fix_count" field.
func (_u *RepositoryUpdate) AddFixCount(v int) *RepositoryUpdate {
	_u.mutation.AddFixCount(v)
	return _u
}

// ClearFixCount clears the value of the "fix_count" field.
func (_u *RepositoryUpdate) ClearFixCount() *RepositoryUpdate {
	_u.mutation.ClearFixCount()
	return _u
}

// SetDocsCount sets the "docs_count" field.
func (_u *RepositoryUpdate) SetDocsCount(v int) *RepositoryUpdate {
	_u.mutation.ResetDocsCount()
	_u.mutation.SetDocsCount(v)
	return _u
}

// SetNillableDocsCount sets the "docs_count" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableDocsCount(v *int) *RepositoryUpdate {
	if v != nil {
		_u.SetDocsCount(*v)
	}
	return _u
}

// AddDocsCount adds value to the "docs_count" field.
func (_u *RepositoryUpdate) AddDocsCount(v int) *RepositoryUpdate {
	_u.mutation.AddDocsCount(v)
	return _u
}

// ClearDocsCount clears the value of the "docs_count" field.
func (_u *RepositoryUpdate) ClearDocsCount() *RepositoryUpdate {
	_u.mutation.ClearDocsCount()
	return _u
}

// SetChoreCount sets the "chore_count" field.
func (_u *RepositoryUpdate) SetChoreCount(v int) *RepositoryUpdate {
	_u.mutation.ResetChoreCount()
	_u.mutation.SetChoreCount(v)
	return _u
}

// SetNillableChoreCount sets the "chore_count" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableChoreCount(v *int) *RepositoryUpdate {
	if v != nil {
		_u.SetChoreCount(*v)
	}
	return _u
}

// AddChoreCount adds value to the "chore_count" field.
func (_u *RepositoryUpdate) AddChoreCount(v int) *RepositoryUpdate {
	_u.mutation.AddChoreCount(v)
	return _u
}

// ClearChoreCount clears the value of the "chore_count" field.
func (_u *RepositoryUpdate) ClearChoreCount() *RepositoryUpdate {
	_u.mutation.ClearChoreCount()
	return _u
}

// SetOtherCommitCount sets the "other_commit_count" field.
func (_u *RepositoryUpdate) SetOtherCommitCount(v int) *RepositoryUpdate {
	_u.mutation.ResetOtherCommitCount()
	_u.mutation.SetOtherCommitCount(v)
	return _u
}

// SetNillableOtherCommitCount sets the "other_commit_count" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableOtherCommitCount(v *int) *RepositoryUpdate {
	if v != nil {
		_u.SetOtherCommitCount(*v)
	}
	return _u
}

// AddOtherCommitCount adds value to the "other_commit_count" field.
func (_u *RepositoryUpdate) AddOtherCommitCount(v int) *RepositoryUpdate {
	_u.mutation.AddOtherCommitCount(v)
	return _u
}

// ClearOtherCommitCount clears the value of the "other_commit_count" field.
func (_u *RepositoryUpdate) ClearOtherCommitCount() *RepositoryUpdate {
	_u.mutation.ClearOtherCommitCount()
	return _u
}

// SetReleaseCount sets the "release_count" field.
func (_u *RepositoryUpdate) SetReleaseCount(v int) *RepositoryUpdate {
	_u.mutation.ResetReleaseCount()
	_u.mutation.SetReleaseCount(v)
	return _u
}

// SetNillableReleaseCount sets the "release_count" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableReleaseCount(v *int) *RepositoryUpdate {
	if v != nil {
		_u.SetReleaseCount(*v)
	}
	return _u
}

// AddReleaseCount adds value to the "release_count" field.
func (_u *RepositoryUpdate) AddReleaseCount(v int) *RepositoryUpdate {
	_u.mutation.AddReleaseCount(v)
	return _u
}

// ClearReleaseCount clears the value of the "release_count" field.
func (_u *RepositoryUpdate) ClearReleaseCount() *RepositoryUpdate {
	_u.mutation.ClearReleaseCount()
	return _u
}

// SetAvgLeadTimeHours sets the "avg_lead_time_hours" field.
func (_u *RepositoryUpdate) SetAvgLeadTimeHours(v float64) *RepositoryUpdate {
	_u.mutation.ResetAvgLeadTimeHours()
	_u.mutation.SetAvgLeadTimeHours(v)
	return _u
}

// SetNillableAvgLeadTimeHours sets the "avg_lead_time_hours" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableAvgLeadTimeHours(v *float64) *RepositoryUpdate {
	if v != nil {
		_u.SetAvgLeadTimeHours(*v)
	}
	return _u
}

// AddAvgLeadTimeHours adds value to the "avg_lead_time_hours" field.
func (_u *RepositoryUpdate) AddAvgLeadTimeHours(v float64) *RepositoryUpdate {
	_u.mutation.AddAvgLeadTimeHours(v)
	return _u
}

// ClearAvgLeadTimeHours clears the value of the "avg_lead_time_hours" field.
func (_u *RepositoryUpdate) ClearAvgLeadTimeHours() *RepositoryUpdate {
	_u.mutation.ClearAvgLeadTimeHours()
	return _u
}

// SetWorkflowSuccessCount sets the "workflow_success_count" field.
func (_u *RepositoryUpdate) SetWorkflowSuccessCount(v int) *RepositoryUpdate {
	_u.mutation.ResetWorkflowSuccessCount()
	_u.mutation.SetWorkflowSuccessCount(v)
	return _u
}

// SetNillableWorkflowSuccessCount sets the "workflow_success_count" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableWorkflowSuccessCount(v *int) *RepositoryUpdate {
	if v != nil {
		_u.SetWorkflowSuccessCount(*v)
	}
	return _u
}

// AddWorkflowSuccessCount adds value to the "workflow_success_count" field.
func (_u *RepositoryUpdate) AddWorkflowSuccessCount(v int) *RepositoryUpdate {
	_u.mutation.AddWorkflowSuccessCount(v)
	return _u
}

// ClearWorkflowSuccessCount clears the value of the "workflow_success_count" field.
func (_u *RepositoryUpdate) ClearWorkflowSuccessCount() *RepositoryUpdate {
	_u.mutation.ClearWorkflowSuccessCount()
	return _u
}

// SetWorkflowFailureCount sets the "workflow_failure_count" field.
func (_u *RepositoryUpdate) SetWorkflowFailureCount(v int) *RepositoryUpdate {
	_u.mutation.ResetWorkflowFailureCount()
	_u.mutation.SetWorkflowFailureCount(v)
	return _u
}

// SetNillableWorkflowFailureCount sets the "workflow_failure_count" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableWorkflowFailureCount(v *int) *RepositoryUpdate {
	if v != nil {
		_u.SetWorkflowFailureCount(*v)
	}
	return _u
}

// AddWorkflowFailureCount adds value to the "workflow_failure_count" field.
func (_u *RepositoryUpdate) AddWorkflowFailureCount(v int) *RepositoryUpdate {
	_u.mutation.AddWorkflowFailureCount(v)
	return _u
}

// ClearWorkflowFailureCount clears the value of the "workflow_failure_count" field.
func (_u *RepositoryUpdate) ClearWorkflowFailureCount() *RepositoryUpdate {
	_u.mutation.ClearWorkflowFailureCount()
	return _u
}

// SetOpenPrCount sets the "open_pr_count" field.
func (_u *RepositoryUpdate) SetOpenPrCount(v int) *RepositoryUpdate {
	_u.mutation.ResetOpenPrCount()
	_u.mutation.SetOpenPrCount(v)
	return _u
}

// SetNillableOpenPrCount sets the "open_pr_count" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableOpenPrCount(v *int) *RepositoryUpdate {
	if v != nil {
		_u.SetOpenPrCount(*v)
	}
	return _u
}

// AddOpenPrCount adds value to the "open_pr_count" field.
func (_u *RepositoryUpdate) AddOpenPrCount(v int) *RepositoryUpdate {
	_u.mutation.AddOpenPrCount(v)
	return _u
}

// ClearOpenPrCount clears the value of the "open_pr_count" field.
func (_u *RepositoryUpdate) ClearOpenPrCount() *RepositoryUpdate {
	_u.mutation.ClearOpenPrCount()
	return _u
}

// SetPullRequests sets the "pull_requests" field.
func (_u *RepositoryUpdate) SetPullRequests(v string) *RepositoryUpdate {
	_u.mutation.SetPullRequests(v)
	return _u
}

// SetNillablePullRequests sets the "pull_requests" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillablePullRequests(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetPullRequests(*v)
	}
	return _u
}

// ClearPullRequests clears the value of the "pull_requests" field.
func (_u *RepositoryUpdate) ClearPullRequests() *RepositoryUpdate {
	_u.mutation.ClearPullRequests()
	return _u
}

// SetLatestReleaseConclusion sets the "latest_release_conclusion" field.
func (_u *RepositoryUpdate) SetLatestReleaseConclusion(v string) *RepositoryUpdate {
	_u.mutation.SetLatestReleaseConclusion(v)
	return _u
}

// SetNillableLatestReleaseConclusion sets the "latest_release_conclusion" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableLatestReleaseConclusion(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetLatestReleaseConclusion(*v)
	}
	return _u
}

// ClearLatestReleaseConclusion clears the value of the "latest_release_conclusion" field.
func (_u *RepositoryUpdate) ClearLatestReleaseConclusion() *RepositoryUpdate {
	_u.mutation.ClearLatestReleaseConclusion()
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *RepositoryUpdate) SetSyncedAt(v time.Time) *RepositoryUpdate {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableSyncedAt(v *time.Time) *RepositoryUpdate {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (_u *RepositoryUpdate) ClearSyncedAt() *RepositoryUpdate {
	_u.mutation.ClearSyncedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RepositoryUpdate) SetCreatedAt(v time.Time) *RepositoryUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableCreatedAt(v *time.Time) *RepositoryUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RepositoryUpdate) SetUpdatedAt(v time.Time) *RepositoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *RepositoryUpdate) SetProvider(v string) *RepositoryUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableProvider(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetForgejoID sets the "forgejo_id" field.
func (_u *RepositoryUpdate) SetForgejoID(v int64) *RepositoryUpdate {
	_u.mutation.ResetForgejoID()
	_u.mutation.SetForgejoID(v)
	return _u
}

// SetNillableForgejoID sets the "forgejo_id" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableForgejoID(v *int64) *RepositoryUpdate {
	if v != nil {
		_u.SetForgejoID(*v)
	}
	return _u
}

// AddForgejoID adds value to the "forgejo_id" field.
func (_u *RepositoryUpdate) AddForgejoID(v int64) *RepositoryUpdate {
	_u.mutation.AddForgejoID(v)
	return _u
}

// ClearForgejoID clears the value of the "forgejo_id" field.
func (_u *RepositoryUpdate) ClearForgejoID() *RepositoryUpdate {
	_u.mutation.ClearForgejoID()
	return _u
}

// SetForgejoOwner sets the "forgejo_owner" field.
func (_u *RepositoryUpdate) SetForgejoOwner(v string) *RepositoryUpdate {
	_u.mutation.SetForgejoOwner(v)
	return _u
}

// SetNillableForgejoOwner sets the "forgejo_owner" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableForgejoOwner(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetForgejoOwner(*v)
	}
	return _u
}

// ClearForgejoOwner clears the value of the "forgejo_owner" field.
func (_u *RepositoryUpdate) ClearForgejoOwner() *RepositoryUpdate {
	_u.mutation.ClearForgejoOwner()
	return _u
}

// SetForgejoName sets the "forgejo_name" field.
func (_u *RepositoryUpdate) SetForgejoName(v string) *RepositoryUpdate {
	_u.mutation.SetForgejoName(v)
	return _u
}

// SetNillableForgejoName sets the "forgejo_name" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableForgejoName(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetForgejoName(*v)
	}
	return _u
}

// ClearForgejoName clears the value of the "forgejo_name" field.
func (_u *RepositoryUpdate) ClearForgejoName() *RepositoryUpdate {
	_u.mutation.ClearForgejoName()
	return _u
}

// SetForgejoFullName sets the "forgejo_full_name" field.
func (_u *RepositoryUpdate) SetForgejoFullName(v string) *RepositoryUpdate {
	_u.mutation.SetForgejoFullName(v)
	return _u
}

// SetNillableForgejoFullName sets the "forgejo_full_name" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableForgejoFullName(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetForgejoFullName(*v)
	}
	return _u
}

// ClearForgejoFullName clears the value of the "forgejo_full_name" field.
func (_u *RepositoryUpdate) ClearForgejoFullName() *RepositoryUpdate {
	_u.mutation.ClearForgejoFullName()
	return _u
}

// SetForgejoHTMLURL sets the "forgejo_html_url" field.
func (_u *RepositoryUpdate) SetForgejoHTMLURL(v string) *RepositoryUpdate {
	_u.mutation.SetForgejoHTMLURL(v)
	return _u
}

// SetNillableForgejoHTMLURL sets the "forgejo_html_url" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableForgejoHTMLURL(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetForgejoHTMLURL(*v)
	}
	return _u
}

// ClearForgejoHTMLURL clears the value of the "forgejo_html_url" field.
func (_u *RepositoryUpdate) ClearForgejoHTMLURL() *RepositoryUpdate {
	_u.mutation.ClearForgejoHTMLURL()
	return _u
}

// SetForgejoURL sets the "forgejo_url" field.
func (_u *RepositoryUpdate) SetForgejoURL(v string) *RepositoryUpdate {
	_u.mutation.SetForgejoURL(v)
	return _u
}

// SetNillableForgejoURL sets the "forgejo_url" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableForgejoURL(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetForgejoURL(*v)
	}
	return _u
}

// ClearForgejoURL clears the value of the "forgejo_url" field.
func (_u *RepositoryUpdate) ClearForgejoURL() *RepositoryUpdate {
	_u.mutation.ClearForgejoURL()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *RepositoryUpdate) SetUserID(id int) *RepositoryUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RepositoryUpdate) SetUser(v *User) *RepositoryUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the RepositoryMutation object of the builder.
func (_u *RepositoryUpdate) Mutation() *RepositoryMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RepositoryUpdate) ClearUser() *RepositoryUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RepositoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepositoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RepositoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepositoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RepositoryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := repository.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RepositoryUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Repository.user"`)
	}
	return nil
}

func (_u *RepositoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(repository.Table, repository.Columns, sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GithubID(); ok {
		_spec.SetField(repository.FieldGithubID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGithubID(); ok {
		_spec.AddField(repository.FieldGithubID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(repository.FieldOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(repository.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FullName(); ok {
		_spec.SetField(repository.FieldFullName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(repository.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(repository.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.HTMLURL(); ok {
		_spec.SetField(repository.FieldHTMLURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(repository.FieldLanguage, field.TypeString, value)
	}
	if _u.mutation.LanguageCleared() {
		_spec.ClearField(repository.FieldLanguage, field.TypeString)
	}
	if value, ok := _u.mutation.DefaultBranch(); ok {
		_spec.SetField(repository.FieldDefaultBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.LatestCommitSha(); ok {
		_spec.SetField(repository.FieldLatestCommitSha, field.TypeString, value)
	}
	if _u.mutation.LatestCommitShaCleared() {
		_spec.ClearField(repository.FieldLatestCommitSha, field.TypeString)
	}
	if value, ok := _u.mutation.LatestCommitMessage(); ok {
		_spec.SetField(repository.FieldLatestCommitMessage, field.TypeString, value)
	}
	if _u.mutation.LatestCommitMessageCleared() {
		_spec.ClearField(repository.FieldLatestCommitMessage, field.TypeString)
	}
	if value, ok := _u.mutation.LatestCommitDate(); ok {
		_spec.SetField(repository.FieldLatestCommitDate, field.TypeTime, value)
	}
	if _u.mutation.LatestCommitDateCleared() {
		_spec.ClearField(repository.FieldLatestCommitDate, field.TypeTime)
	}
	if value, ok := _u.mutation.LatestReleaseTag(); ok {
		_spec.SetField(repository.FieldLatestReleaseTag, field.TypeString, value)
	}
	if _u.mutation.LatestReleaseTagCleared() {
		_spec.ClearField(repository.FieldLatestReleaseTag, field.TypeString)
	}
	if value, ok := _u.mutation.LatestReleaseName(); ok {
		_spec.SetField(repository.FieldLatestReleaseName, field.TypeString, value)
	}
	if _u.mutation.LatestReleaseNameCleared() {
		_spec.ClearField(repository.FieldLatestReleaseName, field.TypeString)
	}
	if value, ok := _u.mutation.LatestReleaseDate(); ok {
		_spec.SetField(repository.FieldLatestReleaseDate, field.TypeTime, value)
	}
	if _u.mutation.LatestReleaseDateCleared() {
		_spec.ClearField(repository.FieldLatestReleaseDate, field.TypeTime)
	}
	if value, ok := _u.mutation.WorkflowStatus(); ok {
		_spec.SetField(repository.FieldWorkflowStatus, field.TypeString, value)
	}
	if _u.mutation.WorkflowStatusCleared() {
		_spec.ClearField(repository.FieldWorkflowStatus, field.TypeString)
	}
	if value, ok := _u.mutation.WorkflowRunID(); ok {
		_spec.SetField(repository.FieldWorkflowRunID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWorkflowRunID(); ok {
		_spec.AddField(repository.FieldWorkflowRunID, field.TypeInt64, value)
	}
	if _u.mutation.WorkflowRunIDCleared() {
		_spec.ClearField(repository.FieldWorkflowRunID, field.TypeInt64)
	}
	if value, ok := _u.mutation.TotalCommitsFetched(); ok {
		_spec.SetField(repository.FieldTotalCommitsFetched, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalCommitsFetched(); ok {
		_spec.AddField(repository.FieldTotalCommitsFetched, field.TypeInt, value)
	}
	if _u.mutation.TotalCommitsFetchedCleared() {
		_spec.ClearField(repository.FieldTotalCommitsFetched, field.TypeInt)
	}
	if value, ok := _u.mutation.FeatCount(); ok {
		_spec.SetField(repository.FieldFeatCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFeatCount(); ok {
		_spec.AddField(repository.FieldFeatCount, field.TypeInt, value)
	}
	if _u.mutation.FeatCountCleared() {
		_spec.ClearField(repository.FieldFeatCount, field.TypeInt)
	}
	if value, ok := _u.mutation.FixCount(); ok {
		_spec.SetField(repository.FieldFixCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFixCount(); ok {
		_spec.AddField(repository.FieldFixCount, field.TypeInt, value)
	}
	if _u.mutation.FixCountCleared() {
		_spec.ClearField(repository.FieldFixCount, field.TypeInt)
	}
	if value, ok := _u.mutation.DocsCount(); ok {
		_spec.SetField(repository.FieldDocsCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDocsCount(); ok {
		_spec.AddField(repository.FieldDocsCount, field.TypeInt, value)
	}
	if _u.mutation.DocsCountCleared() {
		_spec.ClearField(repository.FieldDocsCount, field.TypeInt)
	}
	if value, ok := _u.mutation.ChoreCount(); ok {
		_spec.SetField(repository.FieldChoreCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChoreCount(); ok {
		_spec.AddField(repository.FieldChoreCount, field.TypeInt, value)
	}
	if _u.mutation.ChoreCountCleared() {
		_spec.ClearField(repository.FieldChoreCount, field.TypeInt)
	}
	if value, ok := _u.mutation.OtherCommitCount(); ok {
		_spec.SetField(repository.FieldOtherCommitCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOtherCommitCount(); ok {
		_spec.AddField(repository.FieldOtherCommitCount, field.TypeInt, value)
	}
	if _u.mutation.OtherCommitCountCleared() {
		_spec.ClearField(repository.FieldOtherCommitCount, field.TypeInt)
	}
	if value, ok := _u.mutation.ReleaseCount(); ok {
		_spec.SetField(repository.FieldReleaseCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReleaseCount(); ok {
		_spec.AddField(repository.FieldReleaseCount, field.TypeInt, value)
	}
	if _u.mutation.ReleaseCountCleared() {
		_spec.ClearField(repository.FieldReleaseCount, field.TypeInt)
	}
	if value, ok := _u.mutation.AvgLeadTimeHours(); ok {
		_spec.SetField(repository.FieldAvgLeadTimeHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAvgLeadTimeHours(); ok {
		_spec.AddField(repository.FieldAvgLeadTimeHours, field.TypeFloat64, value)
	}
	if _u.mutation.AvgLeadTimeHoursCleared() {
		_spec.ClearField(repository.FieldAvgLeadTimeHours, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WorkflowSuccessCount(); ok {
		_spec.SetField(repository.FieldWorkflowSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWorkflowSuccessCount(); ok {
		_spec.AddField(repository.FieldWorkflowSuccessCount, field.TypeInt, value)
	}
	if _u.mutation.WorkflowSuccessCountCleared() {
		_spec.ClearField(repository.FieldWorkflowSuccessCount, field.TypeInt)
	}
	if value, ok := _u.mutation.WorkflowFailureCount(); ok {
		_spec.SetField(repository.FieldWorkflowFailureCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWorkflowFailureCount(); ok {
		_spec.AddField(repository.FieldWorkflowFailureCount, field.TypeInt, value)
	}
	if _u.mutation.WorkflowFailureCountCleared() {
		_spec.ClearField(repository.FieldWorkflowFailureCount, field.TypeInt)
	}
	if value, ok := _u.mutation.OpenPrCount(); ok {
		_spec.SetField(repository.FieldOpenPrCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOpenPrCount(); ok {
		_spec.AddField(repository.FieldOpenPrCount, field.TypeInt, value)
	}
	if _u.mutation.OpenPrCountCleared() {
		_spec.ClearField(repository.FieldOpenPrCount, field.TypeInt)
	}
	if value, ok := _u.mutation.PullRequests(); ok {
		_spec.SetField(repository.FieldPullRequests, field.TypeString, value)
	}
	if _u.mutation.PullRequestsCleared() {
		_spec.ClearField(repository.FieldPullRequests, field.TypeString)
	}
	if value, ok := _u.mutation.LatestReleaseConclusion(); ok {
		_spec.SetField(repository.FieldLatestReleaseConclusion, field.TypeString, value)
	}
	if _u.mutation.LatestReleaseConclusionCleared() {
		_spec.ClearField(repository.FieldLatestReleaseConclusion, field.TypeString)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(repository.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SyncedAtCleared() {
		_spec.ClearField(repository.FieldSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(repository.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(repository.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(repository.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ForgejoID(); ok {
		_spec.SetField(repository.FieldForgejoID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedForgejoID(); ok {
		_spec.AddField(repository.FieldForgejoID, field.TypeInt64, value)
	}
	if _u.mutation.ForgejoIDCleared() {
		_spec.ClearField(repository.FieldForgejoID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ForgejoOwner(); ok {
		_spec.SetField(repository.FieldForgejoOwner, field.TypeString, value)
	}
	if _u.mutation.ForgejoOwnerCleared() {
		_spec.ClearField(repository.FieldForgejoOwner, field.TypeString)
	}
	if value, ok := _u.mutation.ForgejoName(); ok {
		_spec.SetField(repository.FieldForgejoName, field.TypeString, value)
	}
	if _u.mutation.ForgejoNameCleared() {
		_spec.ClearField(repository.FieldForgejoName, field.TypeString)
	}
	if value, ok := _u.mutation.ForgejoFullName(); ok {
		_spec.SetField(repository.FieldForgejoFullName, field.TypeString, value)
	}
	if _u.mutation.ForgejoFullNameCleared() {
		_spec.ClearField(repository.FieldForgejoFullName, field.TypeString)
	}
	if value, ok := _u.mutation.ForgejoHTMLURL(); ok {
		_spec.SetField(repository.FieldForgejoHTMLURL, field.TypeString, value)
	}
	if _u.mutation.ForgejoHTMLURLCleared() {
		_spec.ClearField(repository.FieldForgejoHTMLURL, field.TypeString)
	}
	if value, ok := _u.mutation.ForgejoURL(); ok {
		_spec.SetField(repository.FieldForgejoURL, field.TypeString, value)
	}
	if _u.mutation.ForgejoURLCleared() {
		_spec.ClearField(repository.FieldForgejoURL, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   repository.UserTable,
			Columns: []string{repository.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   repository.UserTable,
			Columns: []string{repository.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repository.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RepositoryUpdateOne is the builder for updating a single Repository entity.
type RepositoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RepositoryMutation
}

// SetGithubID sets the "github_id" field.
func (_u *RepositoryUpdateOne) SetGithubID(v int64) *RepositoryUpdateOne {
	_u.mutation.ResetGithubID()
	_u.mutation.SetGithubID(v)
	return _u
}

// SetNillableGithubID sets the "github_id" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableGithubID(v *int64) *RepositoryUpdateOne {
	if v != nil {
		_u.SetGithubID(*v)
	}
	return _u
}

// AddGithubID adds value to the "github_id" field.
func (_u *RepositoryUpdateOne) AddGithubID(v int64) *RepositoryUpdateOne {
	_u.mutation.AddGithubID(v)
	return _u
}

// SetOwner sets the "owner" field.
func (_u *RepositoryUpdateOne) SetOwner(v string) *RepositoryUpdateOne {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableOwner(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RepositoryUpdateOne) SetName(v string) *RepositoryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableName(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFullName sets the "full_name" field.
func (_u *RepositoryUpdateOne) SetFullName(v string) *RepositoryUpdateOne {
	_u.mutation.SetFullName(v)
	return _u
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableFullName(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetFullName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RepositoryUpdateOne) SetDescription(v string) *RepositoryUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableDescription(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RepositoryUpdateOne) ClearDescription() *RepositoryUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetHTMLURL sets the "html_url" field.
func (_u *RepositoryUpdateOne) SetHTMLURL(v string) *RepositoryUpdateOne {
	_u.mutation.SetHTMLURL(v)
	return _u
}

// SetNillableHTMLURL sets the "html_url" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableHTMLURL(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetHTMLURL(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *RepositoryUpdateOne) SetLanguage(v string) *RepositoryUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableLanguage(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// ClearLanguage clears the value of the "language" field.
func (_u *RepositoryUpdateOne) ClearLanguage() *RepositoryUpdateOne {
	_u.mutation.ClearLanguage()
	return _u
}

// SetDefaultBranch sets the "default_branch" field.
func (_u *RepositoryUpdateOne) SetDefaultBranch(v string) *RepositoryUpdateOne {
	_u.mutation.SetDefaultBranch(v)
	return _u
}

// SetNillableDefaultBranch sets the "default_branch" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableDefaultBranch(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetDefaultBranch(*v)
	}
	return _u
}

// SetLatestCommitSha sets the "latest_commit_sha" field.
func (_u *RepositoryUpdateOne) SetLatestCommitSha(v string) *RepositoryUpdateOne {
	_u.mutation.SetLatestCommitSha(v)
	return _u
}

// SetNillableLatestCommitSha sets the "latest_commit_sha" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableLatestCommitSha(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetLatestCommitSha(*v)
	}
	return _u
}

// ClearLatestCommitSha clears the value of the "latest_commit_sha" field.
func (_u *RepositoryUpdateOne) ClearLatestCommitSha() *RepositoryUpdateOne {
	_u.mutation.ClearLatestCommitSha()
	return _u
}

// SetLatestCommitMessage sets the "latest_commit_message" field.
func (_u *RepositoryUpdateOne) SetLatestCommitMessage(v string) *RepositoryUpdateOne {
	_u.mutation.SetLatestCommitMessage(v)
	return _u
}

// SetNillableLatestCommitMessage sets the "latest_commit_message" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableLatestCommitMessage(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetLatestCommitMessage(*v)
	}
	return _u
}

// ClearLatestCommitMessage clears the value of the "latest_commit_message" field.
func (_u *RepositoryUpdateOne) ClearLatestCommitMessage() *RepositoryUpdateOne {
	_u.mutation.ClearLatestCommitMessage()
	return _u
}

// SetLatestCommitDate sets the "latest_commit_date" field.
func (_u *RepositoryUpdateOne) SetLatestCommitDate(v time.Time) *RepositoryUpdateOne {
	_u.mutation.SetLatestCommitDate(v)
	return _u
}

// SetNillableLatestCommitDate sets the "latest_commit_date" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableLatestCommitDate(v *time.Time) *RepositoryUpdateOne {
	if v != nil {
		_u.SetLatestCommitDate(*v)
	}
	return _u
}

// ClearLatestCommitDate clears the value of the "latest_commit_date" field.
func (_u *RepositoryUpdateOne) ClearLatestCommitDate() *RepositoryUpdateOne {
	_u.mutation.ClearLatestCommitDate()
	return _u
}

// SetLatestReleaseTag sets the "latest_release_tag" field.
func (_u *RepositoryUpdateOne) SetLatestReleaseTag(v string) *RepositoryUpdateOne {
	_u.mutation.SetLatestReleaseTag(v)
	return _u
}

// SetNillableLatestReleaseTag sets the "latest_release_tag" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableLatestReleaseTag(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetLatestReleaseTag(*v)
	}
	return _u
}

// ClearLatestReleaseTag clears the value of the "latest_release_tag" field.
func (_u *RepositoryUpdateOne) ClearLatestReleaseTag() *RepositoryUpdateOne {
	_u.mutation.ClearLatestReleaseTag()
	return _u
}

// SetLatestReleaseName sets the "latest_release_name" field.
func (_u *RepositoryUpdateOne) SetLatestReleaseName(v string) *RepositoryUpdateOne {
	_u.mutation.SetLatestReleaseName(v)
	return _u
}

// SetNillableLatestReleaseName sets the "latest_release_name" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableLatestReleaseName(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetLatestReleaseName(*v)
	}
	return _u
}

// ClearLatestReleaseName clears the value of the "latest_release_name" field.
func (_u *RepositoryUpdateOne) ClearLatestReleaseName() *RepositoryUpdateOne {
	_u.mutation.ClearLatestReleaseName()
	return _u
}

// SetLatestReleaseDate sets the "latest_release_date" field.
func (_u *RepositoryUpdateOne) SetLatestReleaseDate(v time.Time) *RepositoryUpdateOne {
	_u.mutation.SetLatestReleaseDate(v)
	return _u
}

// SetNillableLatestReleaseDate sets the "latest_release_date" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableLatestReleaseDate(v *time.Time) *RepositoryUpdateOne {
	if v != nil {
		_u.SetLatestReleaseDate(*v)
	}
	return _u
}

// ClearLatestReleaseDate clears the value of the "latest_release_date" field.
func (_u *RepositoryUpdateOne) ClearLatestReleaseDate() *RepositoryUpdateOne {
	_u.mutation.ClearLatestReleaseDate()
	return _u
}

// SetWorkflowStatus sets the "workflow_status" field.
func (_u *RepositoryUpdateOne) SetWorkflowStatus(v string) *RepositoryUpdateOne {
	_u.mutation.SetWorkflowStatus(v)
	return _u
}

// SetNillableWorkflowStatus sets the "workflow_status" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableWorkflowStatus(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetWorkflowStatus(*v)
	}
	return _u
}

// ClearWorkflowStatus clears the value of the "workflow_status" field.
func (_u *RepositoryUpdateOne) ClearWorkflowStatus() *RepositoryUpdateOne {
	_u.mutation.ClearWorkflowStatus()
	return _u
}

// SetWorkflowRunID sets the "workflow_run_id" field.
func (_u *RepositoryUpdateOne) SetWorkflowRunID(v int64) *RepositoryUpdateOne {
	_u.mutation.ResetWorkflowRunID()
	_u.mutation.SetWorkflowRunID(v)
	return _u
}

// SetNillableWorkflowRunID sets the "workflow_run_id" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableWorkflowRunID(v *int64) *RepositoryUpdateOne {
	if v != nil {
		_u.SetWorkflowRunID(*v)
	}
	return _u
}

// AddWorkflowRunID adds value to the "workflow_run_id" field.
func (_u *RepositoryUpdateOne) AddWorkflowRunID(v int64) *RepositoryUpdateOne {
	_u.mutation.AddWorkflowRunID(v)
	return _u
}

// ClearWorkflowRunID clears the value of the "workflow_run_id" field.
func (_u *RepositoryUpdateOne) ClearWorkflowRunID() *RepositoryUpdateOne {
	_u.mutation.ClearWorkflowRunID()
	return _u
}

// SetTotalCommitsFetched sets the "total_commits_fetched" field.
func (_u *RepositoryUpdateOne) SetTotalCommitsFetched(v int) *RepositoryUpdateOne {
	_u.mutation.ResetTotalCommitsFetched()
	_u.mutation.SetTotalCommitsFetched(v)
	return _u
}

// SetNillableTotalCommitsFetched sets the "total_commits_fetched" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableTotalCommitsFetched(v *int) *RepositoryUpdateOne {
	if v != nil {
		_u.SetTotalCommitsFetched(*v)
	}
	return _u
}

// AddTotalCommitsFetched adds value to the "total_commits_fetched" field.
func (_u *RepositoryUpdateOne) AddTotalCommitsFetched(v int) *RepositoryUpdateOne {
	_u.mutation.AddTotalCommitsFetched(v)
	return _u
}

// ClearTotalCommitsFetched clears the value of the "total_commits_fetched" field.
func (_u *RepositoryUpdateOne) ClearTotalCommitsFetched() *RepositoryUpdateOne {
	_u.mutation.ClearTotalCommitsFetched()
	return _u
}

// SetFeatCount sets the "feat_count" field.
func (_u *RepositoryUpdateOne) SetFeatCount(v int) *RepositoryUpdateOne {
	_u.mutation.ResetFeatCount()
	_u.mutation.SetFeatCount(v)
	return _u
}

// SetNillableFeatCount sets the "feat_count" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableFeatCount(v *int) *RepositoryUpdateOne {
	if v != nil {
		_u.SetFeatCount(*v)
	}
	return _u
}

// AddFeatCount adds value to the "feat_count" field.
func (_u *RepositoryUpdateOne) AddFeatCount(v int) *RepositoryUpdateOne {
	_u.mutation.AddFeatCount(v)
	return _u
}

// ClearFeatCount clears the value of the "feat_count" field.
func (_u *RepositoryUpdateOne) ClearFeatCount() *RepositoryUpdateOne {
	_u.mutation.ClearFeatCount()
	return _u
}

// SetFixCount sets the "fix_count" field.
func (_u *RepositoryUpdateOne) SetFixCount(v int) *RepositoryUpdateOne {
	_u.mutation.ResetFixCount()
	_u.mutation.SetFixCount(v)
	return _u
}

// SetNillableFixCount sets the "fix_count" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableFixCount(v *int) *RepositoryUpdateOne {
	if v != nil {
		_u.SetFixCount(*v)
	}
	return _u
}

// AddFixCount adds value to the "fix_count" field.
func (_u *RepositoryUpdateOne) AddFixCount(v int) *RepositoryUpdateOne {
	_u.mutation.AddFixCount(v)
	return _u
}

// ClearFixCount clears the value of the "fix_count" field.
func (_u *RepositoryUpdateOne) ClearFixCount() *RepositoryUpdateOne {
	_u.mutation.ClearFixCount()
	return _u
}

// SetDocsCount sets the "docs_count" field.
func (_u *RepositoryUpdateOne) SetDocsCount(v int) *RepositoryUpdateOne {
	_u.mutation.ResetDocsCount()
	_u.mutation.SetDocsCount(v)
	return _u
}

// SetNillableDocsCount sets the "docs_count" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableDocsCount(v *int) *RepositoryUpdateOne {
	if v != nil {
		_u.SetDocsCount(*v)
	}
	return _u
}

// AddDocsCount adds value to the "docs_count" field.
func (_u *RepositoryUpdateOne) AddDocsCount(v int) *RepositoryUpdateOne {
	_u.mutation.AddDocsCount(v)
	return _u
}

// ClearDocsCount clears the value of the "docs_count" field.
func (_u *RepositoryUpdateOne) ClearDocsCount() *RepositoryUpdateOne {
	_u.mutation.ClearDocsCount()
	return _u
}

// SetChoreCount sets the "chore_count" field.
func (_u *RepositoryUpdateOne) SetChoreCount(v int) *RepositoryUpdateOne {
	_u.mutation.ResetChoreCount()
	_u.mutation.SetChoreCount(v)
	return _u
}

// SetNillableChoreCount sets the "chore_count" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableChoreCount(v *int) *RepositoryUpdateOne {
	if v != nil {
		_u.SetChoreCount(*v)
	}
	return _u
}

// AddChoreCount adds value to the "chore_count" field.
func (_u *RepositoryUpdateOne) AddChoreCount(v int) *RepositoryUpdateOne {
	_u.mutation.AddChoreCount(v)
	return _u
}

// ClearChoreCount clears the value of the "chore_count" field.
func (_u *RepositoryUpdateOne) ClearChoreCount() *RepositoryUpdateOne {
	_u.mutation.ClearChoreCount()
	return _u
}

// SetOtherCommitCount sets the "other_commit_count" field.
func (_u *RepositoryUpdateOne) SetOtherCommitCount(v int) *RepositoryUpdateOne {
	_u.mutation.ResetOtherCommitCount()
	_u.mutation.SetOtherCommitCount(v)
	return _u
}

// SetNillableOtherCommitCount sets the "other_commit_count" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableOtherCommitCount(v *int) *RepositoryUpdateOne {
	if v != nil {
		_u.SetOtherCommitCount(*v)
	}
	return _u
}

// AddOtherCommitCount adds value to the "other_commit_count" field.
func (_u *RepositoryUpdateOne) AddOtherCommitCount(v int) *RepositoryUpdateOne {
	_u.mutation.AddOtherCommitCount(v)
	return _u
}

// ClearOtherCommitCount clears the value of the "other_commit_count" field.
func (_u *RepositoryUpdateOne) ClearOtherCommitCount() *RepositoryUpdateOne {
	_u.mutation.ClearOtherCommitCount()
	return _u
}

// SetReleaseCount sets the "release_count" field.
func (_u *RepositoryUpdateOne) SetReleaseCount(v int) *RepositoryUpdateOne {
	_u.mutation.ResetReleaseCount()
	_u.mutation.SetReleaseCount(v)
	return _u
}

// SetNillableReleaseCount sets the "release_count" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableReleaseCount(v *int) *RepositoryUpdateOne {
	if v != nil {
		_u.SetReleaseCount(*v)
	}
	return _u
}

// AddReleaseCount adds value to the "release_count" field.
func (_u *RepositoryUpdateOne) AddReleaseCount(v int) *RepositoryUpdateOne {
	_u.mutation.AddReleaseCount(v)
	return _u
}

// ClearReleaseCount clears the value of the "release_count" field.
func (_u *RepositoryUpdateOne) ClearReleaseCount() *RepositoryUpdateOne {
	_u.mutation.ClearReleaseCount()
	return _u
}

// SetAvgLeadTimeHours sets the "avg_lead_time_hours" field.
func (_u *RepositoryUpdateOne) SetAvgLeadTimeHours(v float64) *RepositoryUpdateOne {
	_u.mutation.ResetAvgLeadTimeHours()
	_u.mutation.SetAvgLeadTimeHours(v)
	return _u
}

// SetNillableAvgLeadTimeHours sets the "avg_lead_time_hours" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableAvgLeadTimeHours(v *float64) *RepositoryUpdateOne {
	if v != nil {
		_u.SetAvgLeadTimeHours(*v)
	}
	return _u
}

// AddAvgLeadTimeHours adds value to the "avg_lead_time_hours" field.
func (_u *RepositoryUpdateOne) AddAvgLeadTimeHours(v float64) *RepositoryUpdateOne {
	_u.mutation.AddAvgLeadTimeHours(v)
	return _u
}

// ClearAvgLeadTimeHours clears the value of the "avg_lead_time_hours" field.
func (_u *RepositoryUpdateOne) ClearAvgLeadTimeHours() *RepositoryUpdateOne {
	_u.mutation.ClearAvgLeadTimeHours()
	return _u
}

// SetWorkflowSuccessCount sets the "workflow_success_count" field.
func (_u *RepositoryUpdateOne) SetWorkflowSuccessCount(v int) *RepositoryUpdateOne {
	_u.mutation.ResetWorkflowSuccessCount()
	_u.mutation.SetWorkflowSuccessCount(v)
	return _u
}

// SetNillableWorkflowSuccessCount sets the "workflow_success_count" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableWorkflowSuccessCount(v *int) *RepositoryUpdateOne {
	if v != nil {
		_u.SetWorkflowSuccessCount(*v)
	}
	return _u
}

// AddWorkflowSuccessCount adds value to the "workflow_success_count" field.
func (_u *RepositoryUpdateOne) AddWorkflowSuccessCount(v int) *RepositoryUpdateOne {
	_u.mutation.AddWorkflowSuccessCount(v)
	return _u
}

// ClearWorkflowSuccessCount clears the value of the "workflow_success_count" field.
func (_u *RepositoryUpdateOne) ClearWorkflowSuccessCount() *RepositoryUpdateOne {
	_u.mutation.ClearWorkflowSuccessCount()
	return _u
}

// SetWorkflowFailureCount sets the "workflow_failure_count" field.
func (_u *RepositoryUpdateOne) SetWorkflowFailureCount(v int) *RepositoryUpdateOne {
	_u.mutation.ResetWorkflowFailureCount()
	_u.mutation.SetWorkflowFailureCount(v)
	return _u
}

// SetNillableWorkflowFailureCount sets the "workflow_failure_count" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableWorkflowFailureCount(v *int) *RepositoryUpdateOne {
	if v != nil {
		_u.SetWorkflowFailureCount(*v)
	}
	return _u
}

// AddWorkflowFailureCount adds value to the "workflow_failure_count" field.
func (_u *RepositoryUpdateOne) AddWorkflowFailureCount(v int) *RepositoryUpdateOne {
	_u.mutation.AddWorkflowFailureCount(v)
	return _u
}

// ClearWorkflowFailureCount clears the value of the "workflow_failure_count" field.
func (_u *RepositoryUpdateOne) ClearWorkflowFailureCount() *RepositoryUpdateOne {
	_u.mutation.ClearWorkflowFailureCount()
	return _u
}

// SetOpenPrCount sets the "open_pr_count" field.
func (_u *RepositoryUpdateOne) SetOpenPrCount(v int) *RepositoryUpdateOne {
	_u.mutation.ResetOpenPrCount()
	_u.mutation.SetOpenPrCount(v)
	return _u
}

// SetNillableOpenPrCount sets the "open_pr_count" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableOpenPrCount(v *int) *RepositoryUpdateOne {
	if v != nil {
		_u.SetOpenPrCount(*v)
	}
	return _u
}

// AddOpenPrCount adds value to the "open_pr_count" field.
func (_u *RepositoryUpdateOne) AddOpenPrCount(v int) *RepositoryUpdateOne {
	_u.mutation.AddOpenPrCount(v)
	return _u
}

// ClearOpenPrCount clears the value of the "open_pr_count" field.
func (_u *RepositoryUpdateOne) ClearOpenPrCount() *RepositoryUpdateOne {
	_u.mutation.ClearOpenPrCount()
	return _u
}

// SetPullRequests sets the "pull_requests" field.
func (_u *RepositoryUpdateOne) SetPullRequests(v string) *RepositoryUpdateOne {
	_u.mutation.SetPullRequests(v)
	return _u
}

// SetNillablePullRequests sets the "pull_requests" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillablePullRequests(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetPullRequests(*v)
	}
	return _u
}

// ClearPullRequests clears the value of the "pull_requests" field.
func (_u *RepositoryUpdateOne) ClearPullRequests() *RepositoryUpdateOne {
	_u.mutation.ClearPullRequests()
	return _u
}

// SetLatestReleaseConclusion sets the "latest_release_conclusion" field.
func (_u *RepositoryUpdateOne) SetLatestReleaseConclusion(v string) *RepositoryUpdateOne {
	_u.mutation.SetLatestReleaseConclusion(v)
	return _u
}

// SetNillableLatestReleaseConclusion sets the "latest_release_conclusion" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableLatestReleaseConclusion(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetLatestReleaseConclusion(*v)
	}
	return _u
}

// ClearLatestReleaseConclusion clears the value of the "latest_release_conclusion" field.
func (_u *RepositoryUpdateOne) ClearLatestReleaseConclusion() *RepositoryUpdateOne {
	_u.mutation.ClearLatestReleaseConclusion()
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *RepositoryUpdateOne) SetSyncedAt(v time.Time) *RepositoryUpdateOne {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableSyncedAt(v *time.Time) *RepositoryUpdateOne {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (_u *RepositoryUpdateOne) ClearSyncedAt() *RepositoryUpdateOne {
	_u.mutation.ClearSyncedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RepositoryUpdateOne) SetCreatedAt(v time.Time) *RepositoryUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableCreatedAt(v *time.Time) *RepositoryUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RepositoryUpdateOne) SetUpdatedAt(v time.Time) *RepositoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *RepositoryUpdateOne) SetProvider(v string) *RepositoryUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableProvider(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetForgejoID sets the "forgejo_id" field.
func (_u *RepositoryUpdateOne) SetForgejoID(v int64) *RepositoryUpdateOne {
	_u.mutation.ResetForgejoID()
	_u.mutation.SetForgejoID(v)
	return _u
}

// SetNillableForgejoID sets the "forgejo_id" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableForgejoID(v *int64) *RepositoryUpdateOne {
	if v != nil {
		_u.SetForgejoID(*v)
	}
	return _u
}

// AddForgejoID adds value to the "forgejo_id" field.
func (_u *RepositoryUpdateOne) AddForgejoID(v int64) *RepositoryUpdateOne {
	_u.mutation.AddForgejoID(v)
	return _u
}

// ClearForgejoID clears the value of the "forgejo_id" field.
func (_u *RepositoryUpdateOne) ClearForgejoID() *RepositoryUpdateOne {
	_u.mutation.ClearForgejoID()
	return _u
}

// SetForgejoOwner sets the "forgejo_owner" field.
func (_u *RepositoryUpdateOne) SetForgejoOwner(v string) *RepositoryUpdateOne {
	_u.mutation.SetForgejoOwner(v)
	return _u
}

// SetNillableForgejoOwner sets the "forgejo_owner" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableForgejoOwner(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetForgejoOwner(*v)
	}
	return _u
}

// ClearForgejoOwner clears the value of the "forgejo_owner" field.
func (_u *RepositoryUpdateOne) ClearForgejoOwner() *RepositoryUpdateOne {
	_u.mutation.ClearForgejoOwner()
	return _u
}

// SetForgejoName sets the "forgejo_name" field.
func (_u *RepositoryUpdateOne) SetForgejoName(v string) *RepositoryUpdateOne {
	_u.mutation.SetForgejoName(v)
	return _u
}

// SetNillableForgejoName sets the "forgejo_name" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableForgejoName(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetForgejoName(*v)
	}
	return _u
}

// ClearForgejoName clears the value of the "forgejo_name" field.
func (_u *RepositoryUpdateOne) ClearForgejoName() *RepositoryUpdateOne {
	_u.mutation.ClearForgejoName()
	return _u
}

// SetForgejoFullName sets the "forgejo_full_name" field.
func (_u *RepositoryUpdateOne) SetForgejoFullName(v string) *RepositoryUpdateOne {
	_u.mutation.SetForgejoFullName(v)
	return _u
}

// SetNillableForgejoFullName sets the "forgejo_full_name" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableForgejoFullName(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetForgejoFullName(*v)
	}
	return _u
}

// ClearForgejoFullName clears the value of the "forgejo_full_name" field.
func (_u *RepositoryUpdateOne) ClearForgejoFullName() *RepositoryUpdateOne {
	_u.mutation.ClearForgejoFullName()
	return _u
}

// SetForgejoHTMLURL sets the "forgejo_html_url" field.
func (_u *RepositoryUpdateOne) SetForgejoHTMLURL(v string) *RepositoryUpdateOne {
	_u.mutation.SetForgejoHTMLURL(v)
	return _u
}

// SetNillableForgejoHTMLURL sets the "forgejo_html_url" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableForgejoHTMLURL(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetForgejoHTMLURL(*v)
	}
	return _u
}

// ClearForgejoHTMLURL clears the value of the "forgejo_html_url" field.
func (_u *RepositoryUpdateOne) ClearForgejoHTMLURL() *RepositoryUpdateOne {
	_u.mutation.ClearForgejoHTMLURL()
	return _u
}

// SetForgejoURL sets the "forgejo_url" field.
func (_u *RepositoryUpdateOne) SetForgejoURL(v string) *RepositoryUpdateOne {
	_u.mutation.SetForgejoURL(v)
	return _u
}

// SetNillableForgejoURL sets the "forgejo_url" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableForgejoURL(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetForgejoURL(*v)
	}
	return _u
}

// ClearForgejoURL clears the value of the "forgejo_url" field.
func (_u *RepositoryUpdateOne) ClearForgejoURL() *RepositoryUpdateOne {
	_u.mutation.ClearForgejoURL()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *RepositoryUpdateOne) SetUserID(id int) *RepositoryUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RepositoryUpdateOne) SetUser(v *User) *RepositoryUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the RepositoryMutation object of the builder.
func (_u *RepositoryUpdateOne) Mutation() *RepositoryMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RepositoryUpdateOne) ClearUser() *RepositoryUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the RepositoryUpdate builder.
func (_u *RepositoryUpdateOne) Where(ps ...predicate.Repository) *RepositoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RepositoryUpdateOne) Select(field string, fields ...string) *RepositoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Repository entity.
func (_u *RepositoryUpdateOne) Save(ctx context.Context) (*Repository, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepositoryUpdateOne) SaveX(ctx context.Context) *Repository {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RepositoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepositoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RepositoryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := repository.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RepositoryUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Repository.user"`)
	}
	return nil
}

func (_u *RepositoryUpdateOne) sqlSave(ctx context.Context) (_node *Repository, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(repository.Table, repository.Columns, sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Repository.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, repository.FieldID)
		for _, f := range fields {
			if !repository.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != repository.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GithubID(); ok {
		_spec.SetField(repository.FieldGithubID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGithubID(); ok {
		_spec.AddField(repository.FieldGithubID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(repository.FieldOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(repository.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FullName(); ok {
		_spec.SetField(repository.FieldFullName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(repository.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(repository.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.HTMLURL(); ok {
		_spec.SetField(repository.FieldHTMLURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(repository.FieldLanguage, field.TypeString, value)
	}
	if _u.mutation.LanguageCleared() {
		_spec.ClearField(repository.FieldLanguage, field.TypeString)
	}
	if value, ok := _u.mutation.DefaultBranch(); ok {
		_spec.SetField(repository.FieldDefaultBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.LatestCommitSha(); ok {
		_spec.SetField(repository.FieldLatestCommitSha, field.TypeString, value)
	}
	if _u.mutation.LatestCommitShaCleared() {
		_spec.ClearField(repository.FieldLatestCommitSha, field.TypeString)
	}
	if value, ok := _u.mutation.LatestCommitMessage(); ok {
		_spec.SetField(repository.FieldLatestCommitMessage, field.TypeString, value)
	}
	if _u.mutation.LatestCommitMessageCleared() {
		_spec.ClearField(repository.FieldLatestCommitMessage, field.TypeString)
	}
	if value, ok := _u.mutation.LatestCommitDate(); ok {
		_spec.SetField(repository.FieldLatestCommitDate, field.TypeTime, value)
	}
	if _u.mutation.LatestCommitDateCleared() {
		_spec.ClearField(repository.FieldLatestCommitDate, field.TypeTime)
	}
	if value, ok := _u.mutation.LatestReleaseTag(); ok {
		_spec.SetField(repository.FieldLatestReleaseTag, field.TypeString, value)
	}
	if _u.mutation.LatestReleaseTagCleared() {
		_spec.ClearField(repository.FieldLatestReleaseTag, field.TypeString)
	}
	if value, ok := _u.mutation.LatestReleaseName(); ok {
		_spec.SetField(repository.FieldLatestReleaseName, field.TypeString, value)
	}
	if _u.mutation.LatestReleaseNameCleared() {
		_spec.ClearField(repository.FieldLatestReleaseName, field.TypeString)
	}
	if value, ok := _u.mutation.LatestReleaseDate(); ok {
		_spec.SetField(repository.FieldLatestReleaseDate, field.TypeTime, value)
	}
	if _u.mutation.LatestReleaseDateCleared() {
		_spec.ClearField(repository.FieldLatestReleaseDate, field.TypeTime)
	}
	if value, ok := _u.mutation.WorkflowStatus(); ok {
		_spec.SetField(repository.FieldWorkflowStatus, field.TypeString, value)
	}
	if _u.mutation.WorkflowStatusCleared() {
		_spec.ClearField(repository.FieldWorkflowStatus, field.TypeString)
	}
	if value, ok := _u.mutation.WorkflowRunID(); ok {
		_spec.SetField(repository.FieldWorkflowRunID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWorkflowRunID(); ok {
		_spec.AddField(repository.FieldWorkflowRunID, field.TypeInt64, value)
	}
	if _u.mutation.WorkflowRunIDCleared() {
		_spec.ClearField(repository.FieldWorkflowRunID, field.TypeInt64)
	}
	if value, ok := _u.mutation.TotalCommitsFetched(); ok {
		_spec.SetField(repository.FieldTotalCommitsFetched, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalCommitsFetched(); ok {
		_spec.AddField(repository.FieldTotalCommitsFetched, field.TypeInt, value)
	}
	if _u.mutation.TotalCommitsFetchedCleared() {
		_spec.ClearField(repository.FieldTotalCommitsFetched, field.TypeInt)
	}
	if value, ok := _u.mutation.FeatCount(); ok {
		_spec.SetField(repository.FieldFeatCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFeatCount(); ok {
		_spec.AddField(repository.FieldFeatCount, field.TypeInt, value)
	}
	if _u.mutation.FeatCountCleared() {
		_spec.ClearField(repository.FieldFeatCount, field.TypeInt)
	}
	if value, ok := _u.mutation.FixCount(); ok {
		_spec.SetField(repository.FieldFixCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFixCount(); ok {
		_spec.AddField(repository.FieldFixCount, field.TypeInt, value)
	}
	if _u.mutation.FixCountCleared() {
		_spec.ClearField(repository.FieldFixCount, field.TypeInt)
	}
	if value, ok := _u.mutation.DocsCount(); ok {
		_spec.SetField(repository.FieldDocsCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDocsCount(); ok {
		_spec.AddField(repository.FieldDocsCount, field.TypeInt, value)
	}
	if _u.mutation.DocsCountCleared() {
		_spec.ClearField(repository.FieldDocsCount, field.TypeInt)
	}
	if value, ok := _u.mutation.ChoreCount(); ok {
		_spec.SetField(repository.FieldChoreCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChoreCount(); ok {
		_spec.AddField(repository.FieldChoreCount, field.TypeInt, value)
	}
	if _u.mutation.ChoreCountCleared() {
		_spec.ClearField(repository.FieldChoreCount, field.TypeInt)
	}
	if value, ok := _u.mutation.OtherCommitCount(); ok {
		_spec.SetField(repository.FieldOtherCommitCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOtherCommitCount(); ok {
		_spec.AddField(repository.FieldOtherCommitCount, field.TypeInt, value)
	}
	if _u.mutation.OtherCommitCountCleared() {
		_spec.ClearField(repository.FieldOtherCommitCount, field.TypeInt)
	}
	if value, ok := _u.mutation.ReleaseCount(); ok {
		_spec.SetField(repository.FieldReleaseCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReleaseCount(); ok {
		_spec.AddField(repository.FieldReleaseCount, field.TypeInt, value)
	}
	if _u.mutation.ReleaseCountCleared() {
		_spec.ClearField(repository.FieldReleaseCount, field.TypeInt)
	}
	if value, ok := _u.mutation.AvgLeadTimeHours(); ok {
		_spec.SetField(repository.FieldAvgLeadTimeHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAvgLeadTimeHours(); ok {
		_spec.AddField(repository.FieldAvgLeadTimeHours, field.TypeFloat64, value)
	}
	if _u.mutation.AvgLeadTimeHoursCleared() {
		_spec.ClearField(repository.FieldAvgLeadTimeHours, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WorkflowSuccessCount(); ok {
		_spec.SetField(repository.FieldWorkflowSuccessCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWorkflowSuccessCount(); ok {
		_spec.AddField(repository.FieldWorkflowSuccessCount, field.TypeInt, value)
	}
	if _u.mutation.WorkflowSuccessCountCleared() {
		_spec.ClearField(repository.FieldWorkflowSuccessCount, field.TypeInt)
	}
	if value, ok := _u.mutation.WorkflowFailureCount(); ok {
		_spec.SetField(repository.FieldWorkflowFailureCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWorkflowFailureCount(); ok {
		_spec.AddField(repository.FieldWorkflowFailureCount, field.TypeInt, value)
	}
	if _u.mutation.WorkflowFailureCountCleared() {
		_spec.ClearField(repository.FieldWorkflowFailureCount, field.TypeInt)
	}
	if value, ok := _u.mutation.OpenPrCount(); ok {
		_spec.SetField(repository.FieldOpenPrCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOpenPrCount(); ok {
		_spec.AddField(repository.FieldOpenPrCount, field.TypeInt, value)
	}
	if _u.mutation.OpenPrCountCleared() {
		_spec.ClearField(repository.FieldOpenPrCount, field.TypeInt)
	}
	if value, ok := _u.mutation.PullRequests(); ok {
		_spec.SetField(repository.FieldPullRequests, field.TypeString, value)
	}
	if _u.mutation.PullRequestsCleared() {
		_spec.ClearField(repository.FieldPullRequests, field.TypeString)
	}
	if value, ok := _u.mutation.LatestReleaseConclusion(); ok {
		_spec.SetField(repository.FieldLatestReleaseConclusion, field.TypeString, value)
	}
	if _u.mutation.LatestReleaseConclusionCleared() {
		_spec.ClearField(repository.FieldLatestReleaseConclusion, field.TypeString)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(repository.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SyncedAtCleared() {
		_spec.ClearField(repository.FieldSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(repository.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(repository.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(repository.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ForgejoID(); ok {
		_spec.SetField(repository.FieldForgejoID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedForgejoID(); ok {
		_spec.AddField(repository.FieldForgejoID, field.TypeInt64, value)
	}
	if _u.mutation.ForgejoIDCleared() {
		_spec.ClearField(repository.FieldForgejoID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ForgejoOwner(); ok {
		_spec.SetField(repository.FieldForgejoOwner, field.TypeString, value)
	}
	if _u.mutation.ForgejoOwnerCleared() {
		_spec.ClearField(repository.FieldForgejoOwner, field.TypeString)
	}
	if value, ok := _u.mutation.ForgejoName(); ok {
		_spec.SetField(repository.FieldForgejoName, field.TypeString, value)
	}
	if _u.mutation.ForgejoNameCleared() {
		_spec.ClearField(repository.FieldForgejoName, field.TypeString)
	}
	if value, ok := _u.mutation.ForgejoFullName(); ok {
		_spec.SetField(repository.FieldForgejoFullName, field.TypeString, value)
	}
	if _u.mutation.ForgejoFullNameCleared() {
		_spec.ClearField(repository.FieldForgejoFullName, field.TypeString)
	}
	if value, ok := _u.mutation.ForgejoHTMLURL(); ok {
		_spec.SetField(repository.FieldForgejoHTMLURL, field.TypeString, value)
	}
	if _u.mutation.ForgejoHTMLURLCleared() {
		_spec.ClearField(repository.FieldForgejoHTMLURL, field.TypeString)
	}
	if value, ok := _u.mutation.ForgejoURL(); ok {
		_spec.SetField(repository.FieldForgejoURL, field.TypeString, value)
	}
	if _u.mutation.ForgejoURLCleared() {
		_spec.ClearField(repository.FieldForgejoURL, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   repository.UserTable,
			Columns: []string{repository.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   repository.UserTable,
			Columns: []string{repository.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Repository{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repository.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
