// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gitoverviewer/ent/repository"
	"gitoverviewer/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RepositoryCreate is the builder for creating a Repository entity.
type RepositoryCreate struct {
	config
	mutation *RepositoryMutation
	hooks    []Hook
}

// SetGithubID sets the "github_id" field.
func (_c *RepositoryCreate) SetGithubID(v int64) *RepositoryCreate {
	_c.mutation.SetGithubID(v)
	return _c
}

// SetOwner sets the "owner" field.
func (_c *RepositoryCreate) SetOwner(v string) *RepositoryCreate {
	_c.mutation.SetOwner(v)
	return _c
}

// SetName sets the "name" field.
func (_c *RepositoryCreate) SetName(v string) *RepositoryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetFullName sets the "full_name" field.
func (_c *RepositoryCreate) SetFullName(v string) *RepositoryCreate {
	_c.mutation.SetFullName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *RepositoryCreate) SetDescription(v string) *RepositoryCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableDescription(v *string) *RepositoryCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetHTMLURL sets the "html_url" field.
func (_c *RepositoryCreate) SetHTMLURL(v string) *RepositoryCreate {
	_c.mutation.SetHTMLURL(v)
	return _c
}

// SetLanguage sets the "language" field.
func (_c *RepositoryCreate) SetLanguage(v string) *RepositoryCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableLanguage(v *string) *RepositoryCreate {
	if v != nil {
		_c.SetLanguage(*v)
	}
	return _c
}

// SetDefaultBranch sets the "default_branch" field.
func (_c *RepositoryCreate) SetDefaultBranch(v string) *RepositoryCreate {
	_c.mutation.SetDefaultBranch(v)
	return _c
}

// SetLatestCommitSha sets the "latest_commit_sha" field.
func (_c *RepositoryCreate) SetLatestCommitSha(v string) *RepositoryCreate {
	_c.mutation.SetLatestCommitSha(v)
	return _c
}

// SetNillableLatestCommitSha sets the "latest_commit_sha" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableLatestCommitSha(v *string) *RepositoryCreate {
	if v != nil {
		_c.SetLatestCommitSha(*v)
	}
	return _c
}

// SetLatestCommitMessage sets the "latest_commit_message" field.
func (_c *RepositoryCreate) SetLatestCommitMessage(v string) *RepositoryCreate {
	_c.mutation.SetLatestCommitMessage(v)
	return _c
}

// SetNillableLatestCommitMessage sets the "latest_commit_message" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableLatestCommitMessage(v *string) *RepositoryCreate {
	if v != nil {
		_c.SetLatestCommitMessage(*v)
	}
	return _c
}

// SetLatestCommitDate sets the "latest_commit_date" field.
func (_c *RepositoryCreate) SetLatestCommitDate(v time.Time) *RepositoryCreate {
	_c.mutation.SetLatestCommitDate(v)
	return _c
}

// SetNillableLatestCommitDate sets the "latest_commit_date" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableLatestCommitDate(v *time.Time) *RepositoryCreate {
	if v != nil {
		_c.SetLatestCommitDate(*v)
	}
	return _c
}

// SetLatestReleaseTag sets the "latest_release_tag" field.
func (_c *RepositoryCreate) SetLatestReleaseTag(v string) *RepositoryCreate {
	_c.mutation.SetLatestReleaseTag(v)
	return _c
}

// SetNillableLatestReleaseTag sets the "latest_release_tag" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableLatestReleaseTag(v *string) *RepositoryCreate {
	if v != nil {
		_c.SetLatestReleaseTag(*v)
	}
	return _c
}

// SetLatestReleaseName sets the "latest_release_name" field.
func (_c *RepositoryCreate) SetLatestReleaseName(v string) *RepositoryCreate {
	_c.mutation.SetLatestReleaseName(v)
	return _c
}

// SetNillableLatestReleaseName sets the "latest_release_name" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableLatestReleaseName(v *string) *RepositoryCreate {
	if v != nil {
		_c.SetLatestReleaseName(*v)
	}
	return _c
}

// SetLatestReleaseDate sets the "latest_release_date" field.
func (_c *RepositoryCreate) SetLatestReleaseDate(v time.Time) *RepositoryCreate {
	_c.mutation.SetLatestReleaseDate(v)
	return _c
}

// SetNillableLatestReleaseDate sets the "latest_release_date" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableLatestReleaseDate(v *time.Time) *RepositoryCreate {
	if v != nil {
		_c.SetLatestReleaseDate(*v)
	}
	return _c
}

// SetWorkflowStatus sets the "workflow_status" field.
func (_c *RepositoryCreate) SetWorkflowStatus(v string) *RepositoryCreate {
	_c.mutation.SetWorkflowStatus(v)
	return _c
}

// SetNillableWorkflowStatus sets the "workflow_status" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableWorkflowStatus(v *string) *RepositoryCreate {
	if v != nil {
		_c.SetWorkflowStatus(*v)
	}
	return _c
}

// SetWorkflowRunID sets the "workflow_run_id" field.
func (_c *RepositoryCreate) SetWorkflowRunID(v int64) *RepositoryCreate {
	_c.mutation.SetWorkflowRunID(v)
	return _c
}

// SetNillableWorkflowRunID sets the "workflow_run_id" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableWorkflowRunID(v *int64) *RepositoryCreate {
	if v != nil {
		_c.SetWorkflowRunID(*v)
	}
	return _c
}

// SetSyncedAt sets the "synced_at" field.
func (_c *RepositoryCreate) SetSyncedAt(v time.Time) *RepositoryCreate {
	_c.mutation.SetSyncedAt(v)
	return _c
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableSyncedAt(v *time.Time) *RepositoryCreate {
	if v != nil {
		_c.SetSyncedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RepositoryCreate) SetCreatedAt(v time.Time) *RepositoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableCreatedAt(v *time.Time) *RepositoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RepositoryCreate) SetUpdatedAt(v time.Time) *RepositoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableUpdatedAt(v *time.Time) *RepositoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *RepositoryCreate) SetUserID(id int) *RepositoryCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *RepositoryCreate) SetUser(v *User) *RepositoryCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the RepositoryMutation object of the builder.
func (_c *RepositoryCreate) Mutation() *RepositoryMutation {
	return _c.mutation
}

// Save creates the Repository in the database.
func (_c *RepositoryCreate) Save(ctx context.Context) (*Repository, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RepositoryCreate) SaveX(ctx context.Context) *Repository {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepositoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepositoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RepositoryCreate) defaults() {
	if _, ok := _c.mutation.WorkflowStatus(); !ok {
		v := repository.DefaultWorkflowStatus
		_c.mutation.SetWorkflowStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := repository.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := repository.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RepositoryCreate) check() error {
	if _, ok := _c.mutation.GithubID(); !ok {
		return &ValidationError{Name: "github_id", err: errors.New(`ent: missing required field "Repository.github_id"`)}
	}
	if _, ok := _c.mutation.Owner(); !ok {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required field "Repository.owner"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Repository.name"`)}
	}
	if _, ok := _c.mutation.FullName(); !ok {
		return &ValidationError{Name: "full_name", err: errors.New(`ent: missing required field "Repository.full_name"`)}
	}
	if _, ok := _c.mutation.HTMLURL(); !ok {
		return &ValidationError{Name: "html_url", err: errors.New(`ent: missing required field "Repository.html_url"`)}
	}
	if _, ok := _c.mutation.DefaultBranch(); !ok {
		return &ValidationError{Name: "default_branch", err: errors.New(`ent: missing required field "Repository.default_branch"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Repository.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Repository.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Repository.user"`)}
	}
	return nil
}

func (_c *RepositoryCreate) sqlSave(ctx context.Context) (*Repository, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RepositoryCreate) createSpec() (*Repository, *sqlgraph.CreateSpec) {
	var (
		_node = &Repository{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(repository.Table, sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GithubID(); ok {
		_spec.SetField(repository.FieldGithubID, field.TypeInt64, value)
		_node.GithubID = value
	}
	if value, ok := _c.mutation.Owner(); ok {
		_spec.SetField(repository.FieldOwner, field.TypeString, value)
		_node.Owner = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(repository.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.FullName(); ok {
		_spec.SetField(repository.FieldFullName, field.TypeString, value)
		_node.FullName = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(repository.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.HTMLURL(); ok {
		_spec.SetField(repository.FieldHTMLURL, field.TypeString, value)
		_node.HTMLURL = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(repository.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := _c.mutation.DefaultBranch(); ok {
		_spec.SetField(repository.FieldDefaultBranch, field.TypeString, value)
		_node.DefaultBranch = value
	}
	if value, ok := _c.mutation.LatestCommitSha(); ok {
		_spec.SetField(repository.FieldLatestCommitSha, field.TypeString, value)
		_node.LatestCommitSha = value
	}
	if value, ok := _c.mutation.LatestCommitMessage(); ok {
		_spec.SetField(repository.FieldLatestCommitMessage, field.TypeString, value)
		_node.LatestCommitMessage = value
	}
	if value, ok := _c.mutation.LatestCommitDate(); ok {
		_spec.SetField(repository.FieldLatestCommitDate, field.TypeTime, value)
		_node.LatestCommitDate = value
	}
	if value, ok := _c.mutation.LatestReleaseTag(); ok {
		_spec.SetField(repository.FieldLatestReleaseTag, field.TypeString, value)
		_node.LatestReleaseTag = value
	}
	if value, ok := _c.mutation.LatestReleaseName(); ok {
		_spec.SetField(repository.FieldLatestReleaseName, field.TypeString, value)
		_node.LatestReleaseName = value
	}
	if value, ok := _c.mutation.LatestReleaseDate(); ok {
		_spec.SetField(repository.FieldLatestReleaseDate, field.TypeTime, value)
		_node.LatestReleaseDate = value
	}
	if value, ok := _c.mutation.WorkflowStatus(); ok {
		_spec.SetField(repository.FieldWorkflowStatus, field.TypeString, value)
		_node.WorkflowStatus = value
	}
	if value, ok := _c.mutation.WorkflowRunID(); ok {
		_spec.SetField(repository.FieldWorkflowRunID, field.TypeInt64, value)
		_node.WorkflowRunID = value
	}
	if value, ok := _c.mutation.SyncedAt(); ok {
		_spec.SetField(repository.FieldSyncedAt, field.TypeTime, value)
		_node.SyncedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(repository.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(repository.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   repository.UserTable,
			Columns: []string{repository.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_repositories = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RepositoryCreateBulk is the builder for creating many Repository entities in bulk.
type RepositoryCreateBulk struct {
	config
	err      error
	builders []*RepositoryCreate
}

// Save creates the Repository entities in the database.
func (_c *RepositoryCreateBulk) Save(ctx context.Context) ([]*Repository, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Repository, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RepositoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RepositoryCreateBulk) SaveX(ctx context.Context) []*Repository {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepositoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepositoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
