// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gitoverviewer/ent/predicate"
	"gitoverviewer/ent/repository"
	"gitoverviewer/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGithubID sets the "github_id" field.
func (_u *UserUpdate) SetGithubID(v int64) *UserUpdate {
	_u.mutation.ResetGithubID()
	_u.mutation.SetGithubID(v)
	return _u
}

// SetNillableGithubID sets the "github_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableGithubID(v *int64) *UserUpdate {
	if v != nil {
		_u.SetGithubID(*v)
	}
	return _u
}

// AddGithubID adds value to the "github_id" field.
func (_u *UserUpdate) AddGithubID(v int64) *UserUpdate {
	_u.mutation.AddGithubID(v)
	return _u
}

// SetLogin sets the "login" field.
func (_u *UserUpdate) SetLogin(v string) *UserUpdate {
	_u.mutation.SetLogin(v)
	return _u
}

// SetNillableLogin sets the "login" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLogin(v *string) *UserUpdate {
	if v != nil {
		_u.SetLogin(*v)
	}
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *UserUpdate) SetAvatarURL(v string) *UserUpdate {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAvatarURL(v *string) *UserUpdate {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *UserUpdate) ClearAvatarURL() *UserUpdate {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdate) SetName(v string) *UserUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableName(v *string) *UserUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *UserUpdate) ClearName() *UserUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *UserUpdate) SetAccessToken(v string) *UserUpdate {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAccessToken(v *string) *UserUpdate {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// SetSyncIntervalMinutes sets the "sync_interval_minutes" field.
func (_u *UserUpdate) SetSyncIntervalMinutes(v int) *UserUpdate {
	_u.mutation.ResetSyncIntervalMinutes()
	_u.mutation.SetSyncIntervalMinutes(v)
	return _u
}

// SetNillableSyncIntervalMinutes sets the "sync_interval_minutes" field if the given value is not nil.
func (_u *UserUpdate) SetNillableSyncIntervalMinutes(v *int) *UserUpdate {
	if v != nil {
		_u.SetSyncIntervalMinutes(*v)
	}
	return _u
}

// AddSyncIntervalMinutes adds value to the "sync_interval_minutes" field.
func (_u *UserUpdate) AddSyncIntervalMinutes(v int) *UserUpdate {
	_u.mutation.AddSyncIntervalMinutes(v)
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *UserUpdate) SetSyncedAt(v time.Time) *UserUpdate {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableSyncedAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (_u *UserUpdate) ClearSyncedAt() *UserUpdate {
	_u.mutation.ClearSyncedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserUpdate) SetCreatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCreatedAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddRepositoryIDs adds the "repositories" edge to the Repository entity by IDs.
func (_u *UserUpdate) AddRepositoryIDs(ids ...int) *UserUpdate {
	_u.mutation.AddRepositoryIDs(ids...)
	return _u
}

// AddRepositories adds the "repositories" edges to the Repository entity.
func (_u *UserUpdate) AddRepositories(v ...*Repository) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRepositoryIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearRepositories clears all "repositories" edges to the Repository entity.
func (_u *UserUpdate) ClearRepositories() *UserUpdate {
	_u.mutation.ClearRepositories()
	return _u
}

// RemoveRepositoryIDs removes the "repositories" edge to Repository entities by IDs.
func (_u *UserUpdate) RemoveRepositoryIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveRepositoryIDs(ids...)
	return _u
}

// RemoveRepositories removes "repositories" edges to Repository entities.
func (_u *UserUpdate) RemoveRepositories(v ...*Repository) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRepositoryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GithubID(); ok {
		_spec.SetField(user.FieldGithubID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGithubID(); ok {
		_spec.AddField(user.FieldGithubID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Login(); ok {
		_spec.SetField(user.FieldLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(user.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(user.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(user.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(user.FieldAccessToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.SyncIntervalMinutes(); ok {
		_spec.SetField(user.FieldSyncIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSyncIntervalMinutes(); ok {
		_spec.AddField(user.FieldSyncIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(user.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SyncedAtCleared() {
		_spec.ClearField(user.FieldSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.RepositoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RepositoriesTable,
			Columns: []string{user.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRepositoriesIDs(); len(nodes) > 0 && !_u.mutation.RepositoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RepositoriesTable,
			Columns: []string{user.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RepositoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RepositoriesTable,
			Columns: []string{user.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetGithubID sets the "github_id" field.
func (_u *UserUpdateOne) SetGithubID(v int64) *UserUpdateOne {
	_u.mutation.ResetGithubID()
	_u.mutation.SetGithubID(v)
	return _u
}

// SetNillableGithubID sets the "github_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableGithubID(v *int64) *UserUpdateOne {
	if v != nil {
		_u.SetGithubID(*v)
	}
	return _u
}

// AddGithubID adds value to the "github_id" field.
func (_u *UserUpdateOne) AddGithubID(v int64) *UserUpdateOne {
	_u.mutation.AddGithubID(v)
	return _u
}

// SetLogin sets the "login" field.
func (_u *UserUpdateOne) SetLogin(v string) *UserUpdateOne {
	_u.mutation.SetLogin(v)
	return _u
}

// SetNillableLogin sets the "login" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLogin(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetLogin(*v)
	}
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *UserUpdateOne) SetAvatarURL(v string) *UserUpdateOne {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAvatarURL(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *UserUpdateOne) ClearAvatarURL() *UserUpdateOne {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdateOne) SetName(v string) *UserUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *UserUpdateOne) ClearName() *UserUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *UserUpdateOne) SetAccessToken(v string) *UserUpdateOne {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAccessToken(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// SetSyncIntervalMinutes sets the "sync_interval_minutes" field.
func (_u *UserUpdateOne) SetSyncIntervalMinutes(v int) *UserUpdateOne {
	_u.mutation.ResetSyncIntervalMinutes()
	_u.mutation.SetSyncIntervalMinutes(v)
	return _u
}

// SetNillableSyncIntervalMinutes sets the "sync_interval_minutes" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSyncIntervalMinutes(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetSyncIntervalMinutes(*v)
	}
	return _u
}

// AddSyncIntervalMinutes adds value to the "sync_interval_minutes" field.
func (_u *UserUpdateOne) AddSyncIntervalMinutes(v int) *UserUpdateOne {
	_u.mutation.AddSyncIntervalMinutes(v)
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *UserUpdateOne) SetSyncedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSyncedAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (_u *UserUpdateOne) ClearSyncedAt() *UserUpdateOne {
	_u.mutation.ClearSyncedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserUpdateOne) SetCreatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCreatedAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddRepositoryIDs adds the "repositories" edge to the Repository entity by IDs.
func (_u *UserUpdateOne) AddRepositoryIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddRepositoryIDs(ids...)
	return _u
}

// AddRepositories adds the "repositories" edges to the Repository entity.
func (_u *UserUpdateOne) AddRepositories(v ...*Repository) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRepositoryIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearRepositories clears all "repositories" edges to the Repository entity.
func (_u *UserUpdateOne) ClearRepositories() *UserUpdateOne {
	_u.mutation.ClearRepositories()
	return _u
}

// RemoveRepositoryIDs removes the "repositories" edge to Repository entities by IDs.
func (_u *UserUpdateOne) RemoveRepositoryIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveRepositoryIDs(ids...)
	return _u
}

// RemoveRepositories removes "repositories" edges to Repository entities.
func (_u *UserUpdateOne) RemoveRepositories(v ...*Repository) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRepositoryIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GithubID(); ok {
		_spec.SetField(user.FieldGithubID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGithubID(); ok {
		_spec.AddField(user.FieldGithubID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Login(); ok {
		_spec.SetField(user.FieldLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(user.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(user.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(user.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(user.FieldAccessToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.SyncIntervalMinutes(); ok {
		_spec.SetField(user.FieldSyncIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSyncIntervalMinutes(); ok {
		_spec.AddField(user.FieldSyncIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(user.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SyncedAtCleared() {
		_spec.ClearField(user.FieldSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.RepositoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RepositoriesTable,
			Columns: []string{user.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRepositoriesIDs(); len(nodes) > 0 && !_u.mutation.RepositoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RepositoriesTable,
			Columns: []string{user.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RepositoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RepositoriesTable,
			Columns: []string{user.RepositoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
