// Code generated by ent, DO NOT EDIT.

package repository

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the repository type in the database.
	Label = "repository"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGithubID holds the string denoting the github_id field in the database.
	FieldGithubID = "github_id"
	// FieldOwner holds the string denoting the owner field in the database.
	FieldOwner = "owner"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldFullName holds the string denoting the full_name field in the database.
	FieldFullName = "full_name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldHTMLURL holds the string denoting the html_url field in the database.
	FieldHTMLURL = "html_url"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldDefaultBranch holds the string denoting the default_branch field in the database.
	FieldDefaultBranch = "default_branch"
	// FieldLatestCommitSha holds the string denoting the latest_commit_sha field in the database.
	FieldLatestCommitSha = "latest_commit_sha"
	// FieldLatestCommitMessage holds the string denoting the latest_commit_message field in the database.
	FieldLatestCommitMessage = "latest_commit_message"
	// FieldLatestCommitDate holds the string denoting the latest_commit_date field in the database.
	FieldLatestCommitDate = "latest_commit_date"
	// FieldLatestReleaseTag holds the string denoting the latest_release_tag field in the database.
	FieldLatestReleaseTag = "latest_release_tag"
	// FieldLatestReleaseName holds the string denoting the latest_release_name field in the database.
	FieldLatestReleaseName = "latest_release_name"
	// FieldLatestReleaseDate holds the string denoting the latest_release_date field in the database.
	FieldLatestReleaseDate = "latest_release_date"
	// FieldWorkflowStatus holds the string denoting the workflow_status field in the database.
	FieldWorkflowStatus = "workflow_status"
	// FieldWorkflowRunID holds the string denoting the workflow_run_id field in the database.
	FieldWorkflowRunID = "workflow_run_id"
	// FieldTotalCommitsFetched holds the string denoting the total_commits_fetched field in the database.
	FieldTotalCommitsFetched = "total_commits_fetched"
	// FieldFeatCount holds the string denoting the feat_count field in the database.
	FieldFeatCount = "feat_count"
	// FieldFixCount holds the string denoting the fix_count field in the database.
	FieldFixCount = "fix_count"
	// FieldDocsCount holds the string denoting the docs_count field in the database.
	FieldDocsCount = "docs_count"
	// FieldChoreCount holds the string denoting the chore_count field in the database.
	FieldChoreCount = "chore_count"
	// FieldOtherCommitCount holds the string denoting the other_commit_count field in the database.
	FieldOtherCommitCount = "other_commit_count"
	// FieldReleaseCount holds the string denoting the release_count field in the database.
	FieldReleaseCount = "release_count"
	// FieldAvgLeadTimeHours holds the string denoting the avg_lead_time_hours field in the database.
	FieldAvgLeadTimeHours = "avg_lead_time_hours"
	// FieldWorkflowSuccessCount holds the string denoting the workflow_success_count field in the database.
	FieldWorkflowSuccessCount = "workflow_success_count"
	// FieldWorkflowFailureCount holds the string denoting the workflow_failure_count field in the database.
	FieldWorkflowFailureCount = "workflow_failure_count"
	// FieldOpenPrCount holds the string denoting the open_pr_count field in the database.
	FieldOpenPrCount = "open_pr_count"
	// FieldPullRequests holds the string denoting the pull_requests field in the database.
	FieldPullRequests = "pull_requests"
	// FieldLatestReleaseConclusion holds the string denoting the latest_release_conclusion field in the database.
	FieldLatestReleaseConclusion = "latest_release_conclusion"
	// FieldSyncedAt holds the string denoting the synced_at field in the database.
	FieldSyncedAt = "synced_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldForgejoID holds the string denoting the forgejo_id field in the database.
	FieldForgejoID = "forgejo_id"
	// FieldForgejoOwner holds the string denoting the forgejo_owner field in the database.
	FieldForgejoOwner = "forgejo_owner"
	// FieldForgejoName holds the string denoting the forgejo_name field in the database.
	FieldForgejoName = "forgejo_name"
	// FieldForgejoFullName holds the string denoting the forgejo_full_name field in the database.
	FieldForgejoFullName = "forgejo_full_name"
	// FieldForgejoHTMLURL holds the string denoting the forgejo_html_url field in the database.
	FieldForgejoHTMLURL = "forgejo_html_url"
	// FieldForgejoURL holds the string denoting the forgejo_url field in the database.
	FieldForgejoURL = "forgejo_url"
	// FieldBackfillStatus holds the string denoting the backfill_status field in the database.
	FieldBackfillStatus = "backfill_status"
	// FieldBackfillCursorPage holds the string denoting the backfill_cursor_page field in the database.
	FieldBackfillCursorPage = "backfill_cursor_page"
	// FieldBackfillOldestDate holds the string denoting the backfill_oldest_date field in the database.
	FieldBackfillOldestDate = "backfill_oldest_date"
	// FieldBackfillError holds the string denoting the backfill_error field in the database.
	FieldBackfillError = "backfill_error"
	// FieldBackfillUpdatedAt holds the string denoting the backfill_updated_at field in the database.
	FieldBackfillUpdatedAt = "backfill_updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the repository in the database.
	Table = "repositories"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "repositories"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_repositories"
)

// Columns holds all SQL columns for repository fields.
var Columns = []string{
	FieldID,
	FieldGithubID,
	FieldOwner,
	FieldName,
	FieldFullName,
	FieldDescription,
	FieldHTMLURL,
	FieldLanguage,
	FieldDefaultBranch,
	FieldLatestCommitSha,
	FieldLatestCommitMessage,
	FieldLatestCommitDate,
	FieldLatestReleaseTag,
	FieldLatestReleaseName,
	FieldLatestReleaseDate,
	FieldWorkflowStatus,
	FieldWorkflowRunID,
	FieldTotalCommitsFetched,
	FieldFeatCount,
	FieldFixCount,
	FieldDocsCount,
	FieldChoreCount,
	FieldOtherCommitCount,
	FieldReleaseCount,
	FieldAvgLeadTimeHours,
	FieldWorkflowSuccessCount,
	FieldWorkflowFailureCount,
	FieldOpenPrCount,
	FieldPullRequests,
	FieldLatestReleaseConclusion,
	FieldSyncedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldProvider,
	FieldForgejoID,
	FieldForgejoOwner,
	FieldForgejoName,
	FieldForgejoFullName,
	FieldForgejoHTMLURL,
	FieldForgejoURL,
	FieldBackfillStatus,
	FieldBackfillCursorPage,
	FieldBackfillOldestDate,
	FieldBackfillError,
	FieldBackfillUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "repositories"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_repositories",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultWorkflowStatus holds the default value on creation for the "workflow_status" field.
	DefaultWorkflowStatus string
	// DefaultLatestReleaseConclusion holds the default value on creation for the "latest_release_conclusion" field.
	DefaultLatestReleaseConclusion string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultProvider holds the default value on creation for the "provider" field.
	DefaultProvider string
	// DefaultBackfillStatus holds the default value on creation for the "backfill_status" field.
	DefaultBackfillStatus string
	// DefaultBackfillCursorPage holds the default value on creation for the "backfill_cursor_page" field.
	DefaultBackfillCursorPage int
)

// OrderOption defines the ordering options for the Repository queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGithubID orders the results by the github_id field.
func ByGithubID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGithubID, opts...).ToFunc()
}

// ByOwner orders the results by the owner field.
func ByOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwner, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByFullName orders the results by the full_name field.
func ByFullName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFullName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByHTMLURL orders the results by the html_url field.
func ByHTMLURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTMLURL, opts...).ToFunc()
}

// ByLanguage orders the results by the language field.
func ByLanguage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLanguage, opts...).ToFunc()
}

// ByDefaultBranch orders the results by the default_branch field.
func ByDefaultBranch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultBranch, opts...).ToFunc()
}

// ByLatestCommitSha orders the results by the latest_commit_sha field.
func ByLatestCommitSha(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatestCommitSha, opts...).ToFunc()
}

// ByLatestCommitMessage orders the results by the latest_commit_message field.
func ByLatestCommitMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatestCommitMessage, opts...).ToFunc()
}

// ByLatestCommitDate orders the results by the latest_commit_date field.
func ByLatestCommitDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatestCommitDate, opts...).ToFunc()
}

// ByLatestReleaseTag orders the results by the latest_release_tag field.
func ByLatestReleaseTag(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatestReleaseTag, opts...).ToFunc()
}

// ByLatestReleaseName orders the results by the latest_release_name field.
func ByLatestReleaseName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatestReleaseName, opts...).ToFunc()
}

// ByLatestReleaseDate orders the results by the latest_release_date field.
func ByLatestReleaseDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatestReleaseDate, opts...).ToFunc()
}

// ByWorkflowStatus orders the results by the workflow_status field.
func ByWorkflowStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowStatus, opts...).ToFunc()
}

// ByWorkflowRunID orders the results by the workflow_run_id field.
func ByWorkflowRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowRunID, opts...).ToFunc()
}

// ByTotalCommitsFetched orders the results by the total_commits_fetched field.
func ByTotalCommitsFetched(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalCommitsFetched, opts...).ToFunc()
}

// ByFeatCount orders the results by the feat_count field.
func ByFeatCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeatCount, opts...).ToFunc()
}

// ByFixCount orders the results by the fix_count field.
func ByFixCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFixCount, opts...).ToFunc()
}

// ByDocsCount orders the results by the docs_count field.
func ByDocsCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocsCount, opts...).ToFunc()
}

// ByChoreCount orders the results by the chore_count field.
func ByChoreCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChoreCount, opts...).ToFunc()
}

// ByOtherCommitCount orders the results by the other_commit_count field.
func ByOtherCommitCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOtherCommitCount, opts...).ToFunc()
}

// ByReleaseCount orders the results by the release_count field.
func ByReleaseCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleaseCount, opts...).ToFunc()
}

// ByAvgLeadTimeHours orders the results by the avg_lead_time_hours field.
func ByAvgLeadTimeHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvgLeadTimeHours, opts...).ToFunc()
}

// ByWorkflowSuccessCount orders the results by the workflow_success_count field.
func ByWorkflowSuccessCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowSuccessCount, opts...).ToFunc()
}

// ByWorkflowFailureCount orders the results by the workflow_failure_count field.
func ByWorkflowFailureCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowFailureCount, opts...).ToFunc()
}

// ByOpenPrCount orders the results by the open_pr_count field.
func ByOpenPrCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpenPrCount, opts...).ToFunc()
}

// ByPullRequests orders the results by the pull_requests field.
func ByPullRequests(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPullRequests, opts...).ToFunc()
}

// ByLatestReleaseConclusion orders the results by the latest_release_conclusion field.
func ByLatestReleaseConclusion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatestReleaseConclusion, opts...).ToFunc()
}

// BySyncedAt orders the results by the synced_at field.
func BySyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByForgejoID orders the results by the forgejo_id field.
func ByForgejoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldForgejoID, opts...).ToFunc()
}

// ByForgejoOwner orders the results by the forgejo_owner field.
func ByForgejoOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldForgejoOwner, opts...).ToFunc()
}

// ByForgejoName orders the results by the forgejo_name field.
func ByForgejoName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldForgejoName, opts...).ToFunc()
}

// ByForgejoFullName orders the results by the forgejo_full_name field.
func ByForgejoFullName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldForgejoFullName, opts...).ToFunc()
}

// ByForgejoHTMLURL orders the results by the forgejo_html_url field.
func ByForgejoHTMLURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldForgejoHTMLURL, opts...).ToFunc()
}

// ByForgejoURL orders the results by the forgejo_url field.
func ByForgejoURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldForgejoURL, opts...).ToFunc()
}

// ByBackfillStatus orders the results by the backfill_status field.
func ByBackfillStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackfillStatus, opts...).ToFunc()
}

// ByBackfillCursorPage orders the results by the backfill_cursor_page field.
func ByBackfillCursorPage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackfillCursorPage, opts...).ToFunc()
}

// ByBackfillOldestDate orders the results by the backfill_oldest_date field.
func ByBackfillOldestDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackfillOldestDate, opts...).ToFunc()
}

// ByBackfillError orders the results by the backfill_error field.
func ByBackfillError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackfillError, opts...).ToFunc()
}

// ByBackfillUpdatedAt orders the results by the backfill_updated_at field.
func ByBackfillUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackfillUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
