// Code generated by ent, DO NOT EDIT.

package repository

import (
	"gitoverviewer/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldID, id))
}

// GithubID applies equality check predicate on the "github_id" field. It's identical to GithubIDEQ.
func GithubID(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldGithubID, v))
}

// Owner applies equality check predicate on the "owner" field. It's identical to OwnerEQ.
func Owner(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldOwner, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldName, v))
}

// FullName applies equality check predicate on the "full_name" field. It's identical to FullNameEQ.
func FullName(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldFullName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldDescription, v))
}

// HTMLURL applies equality check predicate on the "html_url" field. It's identical to HTMLURLEQ.
func HTMLURL(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldHTMLURL, v))
}

// Language applies equality check predicate on the "language" field. It's identical to LanguageEQ.
func Language(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldLanguage, v))
}

// DefaultBranch applies equality check predicate on the "default_branch" field. It's identical to DefaultBranchEQ.
func DefaultBranch(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldDefaultBranch, v))
}

// LatestCommitSha applies equality check predicate on the "latest_commit_sha" field. It's identical to LatestCommitShaEQ.
func LatestCommitSha(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldLatestCommitSha, v))
}

// LatestCommitMessage applies equality check predicate on the "latest_commit_message" field. It's identical to LatestCommitMessageEQ.
func LatestCommitMessage(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldLatestCommitMessage, v))
}

// LatestCommitDate applies equality check predicate on the "latest_commit_date" field. It's identical to LatestCommitDateEQ.
func LatestCommitDate(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldLatestCommitDate, v))
}

// LatestReleaseTag applies equality check predicate on the "latest_release_tag" field. It's identical to LatestReleaseTagEQ.
func LatestReleaseTag(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldLatestReleaseTag, v))
}

// LatestReleaseName applies equality check predicate on the "latest_release_name" field. It's identical to LatestReleaseNameEQ.
func LatestReleaseName(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldLatestReleaseName, v))
}

// LatestReleaseDate applies equality check predicate on the "latest_release_date" field. It's identical to LatestReleaseDateEQ.
func LatestReleaseDate(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldLatestReleaseDate, v))
}

// WorkflowStatus applies equality check predicate on the "workflow_status" field. It's identical to WorkflowStatusEQ.
func WorkflowStatus(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldWorkflowStatus, v))
}

// WorkflowRunID applies equality check predicate on the "workflow_run_id" field. It's identical to WorkflowRunIDEQ.
func WorkflowRunID(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldWorkflowRunID, v))
}

// SyncedAt applies equality check predicate on the "synced_at" field. It's identical to SyncedAtEQ.
func SyncedAt(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldSyncedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldUpdatedAt, v))
}

// GithubIDEQ applies the EQ predicate on the "github_id" field.
func GithubIDEQ(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldGithubID, v))
}

// GithubIDNEQ applies the NEQ predicate on the "github_id" field.
func GithubIDNEQ(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldGithubID, v))
}

// GithubIDIn applies the In predicate on the "github_id" field.
func GithubIDIn(vs ...int64) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldGithubID, vs...))
}

// GithubIDNotIn applies the NotIn predicate on the "github_id" field.
func GithubIDNotIn(vs ...int64) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldGithubID, vs...))
}

// GithubIDGT applies the GT predicate on the "github_id" field.
func GithubIDGT(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldGithubID, v))
}

// GithubIDGTE applies the GTE predicate on the "github_id" field.
func GithubIDGTE(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldGithubID, v))
}

// GithubIDLT applies the LT predicate on the "github_id" field.
func GithubIDLT(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldGithubID, v))
}

// GithubIDLTE applies the LTE predicate on the "github_id" field.
func GithubIDLTE(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldGithubID, v))
}

// OwnerEQ applies the EQ predicate on the "owner" field.
func OwnerEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldOwner, v))
}

// OwnerNEQ applies the NEQ predicate on the "owner" field.
func OwnerNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldOwner, v))
}

// OwnerIn applies the In predicate on the "owner" field.
func OwnerIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldOwner, vs...))
}

// OwnerNotIn applies the NotIn predicate on the "owner" field.
func OwnerNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldOwner, vs...))
}

// OwnerGT applies the GT predicate on the "owner" field.
func OwnerGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldOwner, v))
}

// OwnerGTE applies the GTE predicate on the "owner" field.
func OwnerGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldOwner, v))
}

// OwnerLT applies the LT predicate on the "owner" field.
func OwnerLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldOwner, v))
}

// OwnerLTE applies the LTE predicate on the "owner" field.
func OwnerLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldOwner, v))
}

// OwnerContains applies the Contains predicate on the "owner" field.
func OwnerContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldOwner, v))
}

// OwnerHasPrefix applies the HasPrefix predicate on the "owner" field.
func OwnerHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldOwner, v))
}

// OwnerHasSuffix applies the HasSuffix predicate on the "owner" field.
func OwnerHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldOwner, v))
}

// OwnerEqualFold applies the EqualFold predicate on the "owner" field.
func OwnerEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldOwner, v))
}

// OwnerContainsFold applies the ContainsFold predicate on the "owner" field.
func OwnerContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldOwner, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldName, v))
}

// FullNameEQ applies the EQ predicate on the "full_name" field.
func FullNameEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldFullName, v))
}

// FullNameNEQ applies the NEQ predicate on the "full_name" field.
func FullNameNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldFullName, v))
}

// FullNameIn applies the In predicate on the "full_name" field.
func FullNameIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldFullName, vs...))
}

// FullNameNotIn applies the NotIn predicate on the "full_name" field.
func FullNameNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldFullName, vs...))
}

// FullNameGT applies the GT predicate on the "full_name" field.
func FullNameGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldFullName, v))
}

// FullNameGTE applies the GTE predicate on the "full_name" field.
func FullNameGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldFullName, v))
}

// FullNameLT applies the LT predicate on the "full_name" field.
func FullNameLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldFullName, v))
}

// FullNameLTE applies the LTE predicate on the "full_name" field.
func FullNameLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldFullName, v))
}

// FullNameContains applies the Contains predicate on the "full_name" field.
func FullNameContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldFullName, v))
}

// FullNameHasPrefix applies the HasPrefix predicate on the "full_name" field.
func FullNameHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldFullName, v))
}

// FullNameHasSuffix applies the HasSuffix predicate on the "full_name" field.
func FullNameHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldFullName, v))
}

// FullNameEqualFold applies the EqualFold predicate on the "full_name" field.
func FullNameEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldFullName, v))
}

// FullNameContainsFold applies the ContainsFold predicate on the "full_name" field.
func FullNameContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldFullName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Repository {
	return predicate.Repository(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Repository {
	return predicate.Repository(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldDescription, v))
}

// HTMLURLEQ applies the EQ predicate on the "html_url" field.
func HTMLURLEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldHTMLURL, v))
}

// HTMLURLNEQ applies the NEQ predicate on the "html_url" field.
func HTMLURLNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldHTMLURL, v))
}

// HTMLURLIn applies the In predicate on the "html_url" field.
func HTMLURLIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldHTMLURL, vs...))
}

// HTMLURLNotIn applies the NotIn predicate on the "html_url" field.
func HTMLURLNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldHTMLURL, vs...))
}

// HTMLURLGT applies the GT predicate on the "html_url" field.
func HTMLURLGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldHTMLURL, v))
}

// HTMLURLGTE applies the GTE predicate on the "html_url" field.
func HTMLURLGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldHTMLURL, v))
}

// HTMLURLLT applies the LT predicate on the "html_url" field.
func HTMLURLLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldHTMLURL, v))
}

// HTMLURLLTE applies the LTE predicate on the "html_url" field.
func HTMLURLLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldHTMLURL, v))
}

// HTMLURLContains applies the Contains predicate on the "html_url" field.
func HTMLURLContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldHTMLURL, v))
}

// HTMLURLHasPrefix applies the HasPrefix predicate on the "html_url" field.
func HTMLURLHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldHTMLURL, v))
}

// HTMLURLHasSuffix applies the HasSuffix predicate on the "html_url" field.
func HTMLURLHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldHTMLURL, v))
}

// HTMLURLEqualFold applies the EqualFold predicate on the "html_url" field.
func HTMLURLEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldHTMLURL, v))
}

// HTMLURLContainsFold applies the ContainsFold predicate on the "html_url" field.
func HTMLURLContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldHTMLURL, v))
}

// LanguageEQ applies the EQ predicate on the "language" field.
func LanguageEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldLanguage, v))
}

// LanguageNEQ applies the NEQ predicate on the "language" field.
func LanguageNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldLanguage, v))
}

// LanguageIn applies the In predicate on the "language" field.
func LanguageIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldLanguage, vs...))
}

// LanguageNotIn applies the NotIn predicate on the "language" field.
func LanguageNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldLanguage, vs...))
}

// LanguageGT applies the GT predicate on the "language" field.
func LanguageGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldLanguage, v))
}

// LanguageGTE applies the GTE predicate on the "language" field.
func LanguageGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldLanguage, v))
}

// LanguageLT applies the LT predicate on the "language" field.
func LanguageLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldLanguage, v))
}

// LanguageLTE applies the LTE predicate on the "language" field.
func LanguageLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldLanguage, v))
}

// LanguageContains applies the Contains predicate on the "language" field.
func LanguageContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldLanguage, v))
}

// LanguageHasPrefix applies the HasPrefix predicate on the "language" field.
func LanguageHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldLanguage, v))
}

// LanguageHasSuffix applies the HasSuffix predicate on the "language" field.
func LanguageHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldLanguage, v))
}

// LanguageIsNil applies the IsNil predicate on the "language" field.
func LanguageIsNil() predicate.Repository {
	return predicate.Repository(sql.FieldIsNull(FieldLanguage))
}

// LanguageNotNil applies the NotNil predicate on the "language" field.
func LanguageNotNil() predicate.Repository {
	return predicate.Repository(sql.FieldNotNull(FieldLanguage))
}

// LanguageEqualFold applies the EqualFold predicate on the "language" field.
func LanguageEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldLanguage, v))
}

// LanguageContainsFold applies the ContainsFold predicate on the "language" field.
func LanguageContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldLanguage, v))
}

// DefaultBranchEQ applies the EQ predicate on the "default_branch" field.
func DefaultBranchEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldDefaultBranch, v))
}

// DefaultBranchNEQ applies the NEQ predicate on the "default_branch" field.
func DefaultBranchNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldDefaultBranch, v))
}

// DefaultBranchIn applies the In predicate on the "default_branch" field.
func DefaultBranchIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldDefaultBranch, vs...))
}

// DefaultBranchNotIn applies the NotIn predicate on the "default_branch" field.
func DefaultBranchNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldDefaultBranch, vs...))
}

// DefaultBranchGT applies the GT predicate on the "default_branch" field.
func DefaultBranchGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldDefaultBranch, v))
}

// DefaultBranchGTE applies the GTE predicate on the "default_branch" field.
func DefaultBranchGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldDefaultBranch, v))
}

// DefaultBranchLT applies the LT predicate on the "default_branch" field.
func DefaultBranchLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldDefaultBranch, v))
}

// DefaultBranchLTE applies the LTE predicate on the "default_branch" field.
func DefaultBranchLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldDefaultBranch, v))
}

// DefaultBranchContains applies the Contains predicate on the "default_branch" field.
func DefaultBranchContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldDefaultBranch, v))
}

// DefaultBranchHasPrefix applies the HasPrefix predicate on the "default_branch" field.
func DefaultBranchHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldDefaultBranch, v))
}

// DefaultBranchHasSuffix applies the HasSuffix predicate on the "default_branch" field.
func DefaultBranchHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldDefaultBranch, v))
}

// DefaultBranchEqualFold applies the EqualFold predicate on the "default_branch" field.
func DefaultBranchEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldDefaultBranch, v))
}

// DefaultBranchContainsFold applies the ContainsFold predicate on the "default_branch" field.
func DefaultBranchContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldDefaultBranch, v))
}

// LatestCommitShaEQ applies the EQ predicate on the "latest_commit_sha" field.
func LatestCommitShaEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldLatestCommitSha, v))
}

// LatestCommitShaNEQ applies the NEQ predicate on the "latest_commit_sha" field.
func LatestCommitShaNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldLatestCommitSha, v))
}

// LatestCommitShaIn applies the In predicate on the "latest_commit_sha" field.
func LatestCommitShaIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldLatestCommitSha, vs...))
}

// LatestCommitShaNotIn applies the NotIn predicate on the "latest_commit_sha" field.
func LatestCommitShaNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldLatestCommitSha, vs...))
}

// LatestCommitShaGT applies the GT predicate on the "latest_commit_sha" field.
func LatestCommitShaGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldLatestCommitSha, v))
}

// LatestCommitShaGTE applies the GTE predicate on the "latest_commit_sha" field.
func LatestCommitShaGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldLatestCommitSha, v))
}

// LatestCommitShaLT applies the LT predicate on the "latest_commit_sha" field.
func LatestCommitShaLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldLatestCommitSha, v))
}

// LatestCommitShaLTE applies the LTE predicate on the "latest_commit_sha" field.
func LatestCommitShaLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldLatestCommitSha, v))
}

// LatestCommitShaContains applies the Contains predicate on the "latest_commit_sha" field.
func LatestCommitShaContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldLatestCommitSha, v))
}

// LatestCommitShaHasPrefix applies the HasPrefix predicate on the "latest_commit_sha" field.
func LatestCommitShaHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldLatestCommitSha, v))
}

// LatestCommitShaHasSuffix applies the HasSuffix predicate on the "latest_commit_sha" field.
func LatestCommitShaHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldLatestCommitSha, v))
}

// LatestCommitShaIsNil applies the IsNil predicate on the "latest_commit_sha" field.
func LatestCommitShaIsNil() predicate.Repository {
	return predicate.Repository(sql.FieldIsNull(FieldLatestCommitSha))
}

// LatestCommitShaNotNil applies the NotNil predicate on the "latest_commit_sha" field.
func LatestCommitShaNotNil() predicate.Repository {
	return predicate.Repository(sql.FieldNotNull(FieldLatestCommitSha))
}

// LatestCommitShaEqualFold applies the EqualFold predicate on the "latest_commit_sha" field.
func LatestCommitShaEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldLatestCommitSha, v))
}

// LatestCommitShaContainsFold applies the ContainsFold predicate on the "latest_commit_sha" field.
func LatestCommitShaContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldLatestCommitSha, v))
}

// LatestCommitMessageEQ applies the EQ predicate on the "latest_commit_message" field.
func LatestCommitMessageEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldLatestCommitMessage, v))
}

// LatestCommitMessageNEQ applies the NEQ predicate on the "latest_commit_message" field.
func LatestCommitMessageNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldLatestCommitMessage, v))
}

// LatestCommitMessageIn applies the In predicate on the "latest_commit_message" field.
func LatestCommitMessageIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldLatestCommitMessage, vs...))
}

// LatestCommitMessageNotIn applies the NotIn predicate on the "latest_commit_message" field.
func LatestCommitMessageNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldLatestCommitMessage, vs...))
}

// LatestCommitMessageGT applies the GT predicate on the "latest_commit_message" field.
func LatestCommitMessageGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldLatestCommitMessage, v))
}

// LatestCommitMessageGTE applies the GTE predicate on the "latest_commit_message" field.
func LatestCommitMessageGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldLatestCommitMessage, v))
}

// LatestCommitMessageLT applies the LT predicate on the "latest_commit_message" field.
func LatestCommitMessageLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldLatestCommitMessage, v))
}

// LatestCommitMessageLTE applies the LTE predicate on the "latest_commit_message" field.
func LatestCommitMessageLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldLatestCommitMessage, v))
}

// LatestCommitMessageContains applies the Contains predicate on the "latest_commit_message" field.
func LatestCommitMessageContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldLatestCommitMessage, v))
}

// LatestCommitMessageHasPrefix applies the HasPrefix predicate on the "latest_commit_message" field.
func LatestCommitMessageHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldLatestCommitMessage, v))
}

// LatestCommitMessageHasSuffix applies the HasSuffix predicate on the "latest_commit_message" field.
func LatestCommitMessageHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldLatestCommitMessage, v))
}

// LatestCommitMessageIsNil applies the IsNil predicate on the "latest_commit_message" field.
func LatestCommitMessageIsNil() predicate.Repository {
	return predicate.Repository(sql.FieldIsNull(FieldLatestCommitMessage))
}

// LatestCommitMessageNotNil applies the NotNil predicate on the "latest_commit_message" field.
func LatestCommitMessageNotNil() predicate.Repository {
	return predicate.Repository(sql.FieldNotNull(FieldLatestCommitMessage))
}

// LatestCommitMessageEqualFold applies the EqualFold predicate on the "latest_commit_message" field.
func LatestCommitMessageEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldLatestCommitMessage, v))
}

// LatestCommitMessageContainsFold applies the ContainsFold predicate on the "latest_commit_message" field.
func LatestCommitMessageContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldLatestCommitMessage, v))
}

// LatestCommitDateEQ applies the EQ predicate on the "latest_commit_date" field.
func LatestCommitDateEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldLatestCommitDate, v))
}

// LatestCommitDateNEQ applies the NEQ predicate on the "latest_commit_date" field.
func LatestCommitDateNEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldLatestCommitDate, v))
}

// LatestCommitDateIn applies the In predicate on the "latest_commit_date" field.
func LatestCommitDateIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldLatestCommitDate, vs...))
}

// LatestCommitDateNotIn applies the NotIn predicate on the "latest_commit_date" field.
func LatestCommitDateNotIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldLatestCommitDate, vs...))
}

// LatestCommitDateGT applies the GT predicate on the "latest_commit_date" field.
func LatestCommitDateGT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldLatestCommitDate, v))
}

// LatestCommitDateGTE applies the GTE predicate on the "latest_commit_date" field.
func LatestCommitDateGTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldLatestCommitDate, v))
}

// LatestCommitDateLT applies the LT predicate on the "latest_commit_date" field.
func LatestCommitDateLT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldLatestCommitDate, v))
}

// LatestCommitDateLTE applies the LTE predicate on the "latest_commit_date" field.
func LatestCommitDateLTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldLatestCommitDate, v))
}

// LatestCommitDateIsNil applies the IsNil predicate on the "latest_commit_date" field.
func LatestCommitDateIsNil() predicate.Repository {
	return predicate.Repository(sql.FieldIsNull(FieldLatestCommitDate))
}

// LatestCommitDateNotNil applies the NotNil predicate on the "latest_commit_date" field.
func LatestCommitDateNotNil() predicate.Repository {
	return predicate.Repository(sql.FieldNotNull(FieldLatestCommitDate))
}

// LatestReleaseTagEQ applies the EQ predicate on the "latest_release_tag" field.
func LatestReleaseTagEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldLatestReleaseTag, v))
}

// LatestReleaseTagNEQ applies the NEQ predicate on the "latest_release_tag" field.
func LatestReleaseTagNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldLatestReleaseTag, v))
}

// LatestReleaseTagIn applies the In predicate on the "latest_release_tag" field.
func LatestReleaseTagIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldLatestReleaseTag, vs...))
}

// LatestReleaseTagNotIn applies the NotIn predicate on the "latest_release_tag" field.
func LatestReleaseTagNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldLatestReleaseTag, vs...))
}

// LatestReleaseTagGT applies the GT predicate on the "latest_release_tag" field.
func LatestReleaseTagGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldLatestReleaseTag, v))
}

// LatestReleaseTagGTE applies the GTE predicate on the "latest_release_tag" field.
func LatestReleaseTagGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldLatestReleaseTag, v))
}

// LatestReleaseTagLT applies the LT predicate on the "latest_release_tag" field.
func LatestReleaseTagLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldLatestReleaseTag, v))
}

// LatestReleaseTagLTE applies the LTE predicate on the "latest_release_tag" field.
func LatestReleaseTagLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldLatestReleaseTag, v))
}

// LatestReleaseTagContains applies the Contains predicate on the "latest_release_tag" field.
func LatestReleaseTagContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldLatestReleaseTag, v))
}

// LatestReleaseTagHasPrefix applies the HasPrefix predicate on the "latest_release_tag" field.
func LatestReleaseTagHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldLatestReleaseTag, v))
}

// LatestReleaseTagHasSuffix applies the HasSuffix predicate on the "latest_release_tag" field.
func LatestReleaseTagHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldLatestReleaseTag, v))
}

// LatestReleaseTagIsNil applies the IsNil predicate on the "latest_release_tag" field.
func LatestReleaseTagIsNil() predicate.Repository {
	return predicate.Repository(sql.FieldIsNull(FieldLatestReleaseTag))
}

// LatestReleaseTagNotNil applies the NotNil predicate on the "latest_release_tag" field.
func LatestReleaseTagNotNil() predicate.Repository {
	return predicate.Repository(sql.FieldNotNull(FieldLatestReleaseTag))
}

// LatestReleaseTagEqualFold applies the EqualFold predicate on the "latest_release_tag" field.
func LatestReleaseTagEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldLatestReleaseTag, v))
}

// LatestReleaseTagContainsFold applies the ContainsFold predicate on the "latest_release_tag" field.
func LatestReleaseTagContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldLatestReleaseTag, v))
}

// LatestReleaseNameEQ applies the EQ predicate on the "latest_release_name" field.
func LatestReleaseNameEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldLatestReleaseName, v))
}

// LatestReleaseNameNEQ applies the NEQ predicate on the "latest_release_name" field.
func LatestReleaseNameNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldLatestReleaseName, v))
}

// LatestReleaseNameIn applies the In predicate on the "latest_release_name" field.
func LatestReleaseNameIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldLatestReleaseName, vs...))
}

// LatestReleaseNameNotIn applies the NotIn predicate on the "latest_release_name" field.
func LatestReleaseNameNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldLatestReleaseName, vs...))
}

// LatestReleaseNameGT applies the GT predicate on the "latest_release_name" field.
func LatestReleaseNameGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldLatestReleaseName, v))
}

// LatestReleaseNameGTE applies the GTE predicate on the "latest_release_name" field.
func LatestReleaseNameGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldLatestReleaseName, v))
}

// LatestReleaseNameLT applies the LT predicate on the "latest_release_name" field.
func LatestReleaseNameLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldLatestReleaseName, v))
}

// LatestReleaseNameLTE applies the LTE predicate on the "latest_release_name" field.
func LatestReleaseNameLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldLatestReleaseName, v))
}

// LatestReleaseNameContains applies the Contains predicate on the "latest_release_name" field.
func LatestReleaseNameContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldLatestReleaseName, v))
}

// LatestReleaseNameHasPrefix applies the HasPrefix predicate on the "latest_release_name" field.
func LatestReleaseNameHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldLatestReleaseName, v))
}

// LatestReleaseNameHasSuffix applies the HasSuffix predicate on the "latest_release_name" field.
func LatestReleaseNameHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldLatestReleaseName, v))
}

// LatestReleaseNameIsNil applies the IsNil predicate on the "latest_release_name" field.
func LatestReleaseNameIsNil() predicate.Repository {
	return predicate.Repository(sql.FieldIsNull(FieldLatestReleaseName))
}

// LatestReleaseNameNotNil applies the NotNil predicate on the "latest_release_name" field.
func LatestReleaseNameNotNil() predicate.Repository {
	return predicate.Repository(sql.FieldNotNull(FieldLatestReleaseName))
}

// LatestReleaseNameEqualFold applies the EqualFold predicate on the "latest_release_name" field.
func LatestReleaseNameEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldLatestReleaseName, v))
}

// LatestReleaseNameContainsFold applies the ContainsFold predicate on the "latest_release_name" field.
func LatestReleaseNameContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldLatestReleaseName, v))
}

// LatestReleaseDateEQ applies the EQ predicate on the "latest_release_date" field.
func LatestReleaseDateEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldLatestReleaseDate, v))
}

// LatestReleaseDateNEQ applies the NEQ predicate on the "latest_release_date" field.
func LatestReleaseDateNEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldLatestReleaseDate, v))
}

// LatestReleaseDateIn applies the In predicate on the "latest_release_date" field.
func LatestReleaseDateIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldLatestReleaseDate, vs...))
}

// LatestReleaseDateNotIn applies the NotIn predicate on the "latest_release_date" field.
func LatestReleaseDateNotIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldLatestReleaseDate, vs...))
}

// LatestReleaseDateGT applies the GT predicate on the "latest_release_date" field.
func LatestReleaseDateGT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldLatestReleaseDate, v))
}

// LatestReleaseDateGTE applies the GTE predicate on the "latest_release_date" field.
func LatestReleaseDateGTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldLatestReleaseDate, v))
}

// LatestReleaseDateLT applies the LT predicate on the "latest_release_date" field.
func LatestReleaseDateLT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldLatestReleaseDate, v))
}

// LatestReleaseDateLTE applies the LTE predicate on the "latest_release_date" field.
func LatestReleaseDateLTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldLatestReleaseDate, v))
}

// LatestReleaseDateIsNil applies the IsNil predicate on the "latest_release_date" field.
func LatestReleaseDateIsNil() predicate.Repository {
	return predicate.Repository(sql.FieldIsNull(FieldLatestReleaseDate))
}

// LatestReleaseDateNotNil applies the NotNil predicate on the "latest_release_date" field.
func LatestReleaseDateNotNil() predicate.Repository {
	return predicate.Repository(sql.FieldNotNull(FieldLatestReleaseDate))
}

// WorkflowStatusEQ applies the EQ predicate on the "workflow_status" field.
func WorkflowStatusEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldWorkflowStatus, v))
}

// WorkflowStatusNEQ applies the NEQ predicate on the "workflow_status" field.
func WorkflowStatusNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldWorkflowStatus, v))
}

// WorkflowStatusIn applies the In predicate on the "workflow_status" field.
func WorkflowStatusIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldWorkflowStatus, vs...))
}

// WorkflowStatusNotIn applies the NotIn predicate on the "workflow_status" field.
func WorkflowStatusNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldWorkflowStatus, vs...))
}

// WorkflowStatusGT applies the GT predicate on the "workflow_status" field.
func WorkflowStatusGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldWorkflowStatus, v))
}

// WorkflowStatusGTE applies the GTE predicate on the "workflow_status" field.
func WorkflowStatusGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldWorkflowStatus, v))
}

// WorkflowStatusLT applies the LT predicate on the "workflow_status" field.
func WorkflowStatusLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldWorkflowStatus, v))
}

// WorkflowStatusLTE applies the LTE predicate on the "workflow_status" field.
func WorkflowStatusLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldWorkflowStatus, v))
}

// WorkflowStatusContains applies the Contains predicate on the "workflow_status" field.
func WorkflowStatusContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldWorkflowStatus, v))
}

// WorkflowStatusHasPrefix applies the HasPrefix predicate on the "workflow_status" field.
func WorkflowStatusHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldWorkflowStatus, v))
}

// WorkflowStatusHasSuffix applies the HasSuffix predicate on the "workflow_status" field.
func WorkflowStatusHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldWorkflowStatus, v))
}

// WorkflowStatusIsNil applies the IsNil predicate on the "workflow_status" field.
func WorkflowStatusIsNil() predicate.Repository {
	return predicate.Repository(sql.FieldIsNull(FieldWorkflowStatus))
}

// WorkflowStatusNotNil applies the NotNil predicate on the "workflow_status" field.
func WorkflowStatusNotNil() predicate.Repository {
	return predicate.Repository(sql.FieldNotNull(FieldWorkflowStatus))
}

// WorkflowStatusEqualFold applies the EqualFold predicate on the "workflow_status" field.
func WorkflowStatusEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldWorkflowStatus, v))
}

// WorkflowStatusContainsFold applies the ContainsFold predicate on the "workflow_status" field.
func WorkflowStatusContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldWorkflowStatus, v))
}

// WorkflowRunIDEQ applies the EQ predicate on the "workflow_run_id" field.
func WorkflowRunIDEQ(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldWorkflowRunID, v))
}

// WorkflowRunIDNEQ applies the NEQ predicate on the "workflow_run_id" field.
func WorkflowRunIDNEQ(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldWorkflowRunID, v))
}

// WorkflowRunIDIn applies the In predicate on the "workflow_run_id" field.
func WorkflowRunIDIn(vs ...int64) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldWorkflowRunID, vs...))
}

// WorkflowRunIDNotIn applies the NotIn predicate on the "workflow_run_id" field.
func WorkflowRunIDNotIn(vs ...int64) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldWorkflowRunID, vs...))
}

// WorkflowRunIDGT applies the GT predicate on the "workflow_run_id" field.
func WorkflowRunIDGT(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldWorkflowRunID, v))
}

// WorkflowRunIDGTE applies the GTE predicate on the "workflow_run_id" field.
func WorkflowRunIDGTE(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldWorkflowRunID, v))
}

// WorkflowRunIDLT applies the LT predicate on the "workflow_run_id" field.
func WorkflowRunIDLT(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldWorkflowRunID, v))
}

// WorkflowRunIDLTE applies the LTE predicate on the "workflow_run_id" field.
func WorkflowRunIDLTE(v int64) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldWorkflowRunID, v))
}

// WorkflowRunIDIsNil applies the IsNil predicate on the "workflow_run_id" field.
func WorkflowRunIDIsNil() predicate.Repository {
	return predicate.Repository(sql.FieldIsNull(FieldWorkflowRunID))
}

// WorkflowRunIDNotNil applies the NotNil predicate on the "workflow_run_id" field.
func WorkflowRunIDNotNil() predicate.Repository {
	return predicate.Repository(sql.FieldNotNull(FieldWorkflowRunID))
}

// SyncedAtEQ applies the EQ predicate on the "synced_at" field.
func SyncedAtEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldSyncedAt, v))
}

// SyncedAtNEQ applies the NEQ predicate on the "synced_at" field.
func SyncedAtNEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldSyncedAt, v))
}

// SyncedAtIn applies the In predicate on the "synced_at" field.
func SyncedAtIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldSyncedAt, vs...))
}

// SyncedAtNotIn applies the NotIn predicate on the "synced_at" field.
func SyncedAtNotIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldSyncedAt, vs...))
}

// SyncedAtGT applies the GT predicate on the "synced_at" field.
func SyncedAtGT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldSyncedAt, v))
}

// SyncedAtGTE applies the GTE predicate on the "synced_at" field.
func SyncedAtGTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldSyncedAt, v))
}

// SyncedAtLT applies the LT predicate on the "synced_at" field.
func SyncedAtLT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldSyncedAt, v))
}

// SyncedAtLTE applies the LTE predicate on the "synced_at" field.
func SyncedAtLTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldSyncedAt, v))
}

// SyncedAtIsNil applies the IsNil predicate on the "synced_at" field.
func SyncedAtIsNil() predicate.Repository {
	return predicate.Repository(sql.FieldIsNull(FieldSyncedAt))
}

// SyncedAtNotNil applies the NotNil predicate on the "synced_at" field.
func SyncedAtNotNil() predicate.Repository {
	return predicate.Repository(sql.FieldNotNull(FieldSyncedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Repository {
	return predicate.Repository(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Repository {
	return predicate.Repository(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Repository) predicate.Repository {
	return predicate.Repository(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Repository) predicate.Repository {
	return predicate.Repository(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Repository) predicate.Repository {
	return predicate.Repository(sql.NotPredicates(p))
}
