// Code generated by ent, DO NOT EDIT.

package commitactivity

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the commitactivity type in the database.
	Label = "commit_activity"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRepoID holds the string denoting the repo_id field in the database.
	FieldRepoID = "repo_id"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// FieldCommitCount holds the string denoting the commit_count field in the database.
	FieldCommitCount = "commit_count"
	// Table holds the table name of the commitactivity in the database.
	Table = "commit_activities"
)

// Columns holds all SQL columns for commitactivity fields.
var Columns = []string{
	FieldID,
	FieldRepoID,
	FieldDate,
	FieldCommitCount,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the CommitActivity queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRepoID orders the results by the repo_id field.
func ByRepoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepoID, opts...).ToFunc()
}

// ByDate orders the results by the date field.
func ByDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDate, opts...).ToFunc()
}

// ByCommitCount orders the results by the commit_count field.
func ByCommitCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommitCount, opts...).ToFunc()
}
