// Code generated by ent, DO NOT EDIT.

package user

import (
	"gitlens/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// GithubID applies equality check predicate on the "github_id" field. It's identical to GithubIDEQ.
func GithubID(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldGithubID, v))
}

// Login applies equality check predicate on the "login" field. It's identical to LoginEQ.
func Login(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLogin, v))
}

// AvatarURL applies equality check predicate on the "avatar_url" field. It's identical to AvatarURLEQ.
func AvatarURL(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarURL, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// AccessToken applies equality check predicate on the "access_token" field. It's identical to AccessTokenEQ.
func AccessToken(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAccessToken, v))
}

// SyncIntervalMinutes applies equality check predicate on the "sync_interval_minutes" field. It's identical to SyncIntervalMinutesEQ.
func SyncIntervalMinutes(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSyncIntervalMinutes, v))
}

// UmamiURL applies equality check predicate on the "umami_url" field. It's identical to UmamiURLEQ.
func UmamiURL(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUmamiURL, v))
}

// UmamiSiteID applies equality check predicate on the "umami_site_id" field. It's identical to UmamiSiteIDEQ.
func UmamiSiteID(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUmamiSiteID, v))
}

// IsAdmin applies equality check predicate on the "is_admin" field. It's identical to IsAdminEQ.
func IsAdmin(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsAdmin, v))
}

// SyncedAt applies equality check predicate on the "synced_at" field. It's identical to SyncedAtEQ.
func SyncedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSyncedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// ForgejoID applies equality check predicate on the "forgejo_id" field. It's identical to ForgejoIDEQ.
func ForgejoID(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldForgejoID, v))
}

// ForgejoLogin applies equality check predicate on the "forgejo_login" field. It's identical to ForgejoLoginEQ.
func ForgejoLogin(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldForgejoLogin, v))
}

// ForgejoAvatarURL applies equality check predicate on the "forgejo_avatar_url" field. It's identical to ForgejoAvatarURLEQ.
func ForgejoAvatarURL(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldForgejoAvatarURL, v))
}

// ForgejoName applies equality check predicate on the "forgejo_name" field. It's identical to ForgejoNameEQ.
func ForgejoName(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldForgejoName, v))
}

// ForgejoAccessToken applies equality check predicate on the "forgejo_access_token" field. It's identical to ForgejoAccessTokenEQ.
func ForgejoAccessToken(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldForgejoAccessToken, v))
}

// ForgejoURL applies equality check predicate on the "forgejo_url" field. It's identical to ForgejoURLEQ.
func ForgejoURL(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldForgejoURL, v))
}

// DismissedForgejoWarningFor applies equality check predicate on the "dismissed_forgejo_warning_for" field. It's identical to DismissedForgejoWarningForEQ.
func DismissedForgejoWarningFor(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDismissedForgejoWarningFor, v))
}

// GithubIDEQ applies the EQ predicate on the "github_id" field.
func GithubIDEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldGithubID, v))
}

// GithubIDNEQ applies the NEQ predicate on the "github_id" field.
func GithubIDNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldGithubID, v))
}

// GithubIDIn applies the In predicate on the "github_id" field.
func GithubIDIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldGithubID, vs...))
}

// GithubIDNotIn applies the NotIn predicate on the "github_id" field.
func GithubIDNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldGithubID, vs...))
}

// GithubIDGT applies the GT predicate on the "github_id" field.
func GithubIDGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldGithubID, v))
}

// GithubIDGTE applies the GTE predicate on the "github_id" field.
func GithubIDGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldGithubID, v))
}

// GithubIDLT applies the LT predicate on the "github_id" field.
func GithubIDLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldGithubID, v))
}

// GithubIDLTE applies the LTE predicate on the "github_id" field.
func GithubIDLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldGithubID, v))
}

// LoginEQ applies the EQ predicate on the "login" field.
func LoginEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLogin, v))
}

// LoginNEQ applies the NEQ predicate on the "login" field.
func LoginNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLogin, v))
}

// LoginIn applies the In predicate on the "login" field.
func LoginIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldLogin, vs...))
}

// LoginNotIn applies the NotIn predicate on the "login" field.
func LoginNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLogin, vs...))
}

// LoginGT applies the GT predicate on the "login" field.
func LoginGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldLogin, v))
}

// LoginGTE applies the GTE predicate on the "login" field.
func LoginGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLogin, v))
}

// LoginLT applies the LT predicate on the "login" field.
func LoginLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldLogin, v))
}

// LoginLTE applies the LTE predicate on the "login" field.
func LoginLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLogin, v))
}

// LoginContains applies the Contains predicate on the "login" field.
func LoginContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldLogin, v))
}

// LoginHasPrefix applies the HasPrefix predicate on the "login" field.
func LoginHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldLogin, v))
}

// LoginHasSuffix applies the HasSuffix predicate on the "login" field.
func LoginHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldLogin, v))
}

// LoginEqualFold applies the EqualFold predicate on the "login" field.
func LoginEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldLogin, v))
}

// LoginContainsFold applies the ContainsFold predicate on the "login" field.
func LoginContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldLogin, v))
}

// AvatarURLEQ applies the EQ predicate on the "avatar_url" field.
func AvatarURLEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarURL, v))
}

// AvatarURLNEQ applies the NEQ predicate on the "avatar_url" field.
func AvatarURLNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAvatarURL, v))
}

// AvatarURLIn applies the In predicate on the "avatar_url" field.
func AvatarURLIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAvatarURL, vs...))
}

// AvatarURLNotIn applies the NotIn predicate on the "avatar_url" field.
func AvatarURLNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAvatarURL, vs...))
}

// AvatarURLGT applies the GT predicate on the "avatar_url" field.
func AvatarURLGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAvatarURL, v))
}

// AvatarURLGTE applies the GTE predicate on the "avatar_url" field.
func AvatarURLGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAvatarURL, v))
}

// AvatarURLLT applies the LT predicate on the "avatar_url" field.
func AvatarURLLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAvatarURL, v))
}

// AvatarURLLTE applies the LTE predicate on the "avatar_url" field.
func AvatarURLLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAvatarURL, v))
}

// AvatarURLContains applies the Contains predicate on the "avatar_url" field.
func AvatarURLContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAvatarURL, v))
}

// AvatarURLHasPrefix applies the HasPrefix predicate on the "avatar_url" field.
func AvatarURLHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAvatarURL, v))
}

// AvatarURLHasSuffix applies the HasSuffix predicate on the "avatar_url" field.
func AvatarURLHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAvatarURL, v))
}

// AvatarURLIsNil applies the IsNil predicate on the "avatar_url" field.
func AvatarURLIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldAvatarURL))
}

// AvatarURLNotNil applies the NotNil predicate on the "avatar_url" field.
func AvatarURLNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldAvatarURL))
}

// AvatarURLEqualFold applies the EqualFold predicate on the "avatar_url" field.
func AvatarURLEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAvatarURL, v))
}

// AvatarURLContainsFold applies the ContainsFold predicate on the "avatar_url" field.
func AvatarURLContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAvatarURL, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldName, v))
}

// AccessTokenEQ applies the EQ predicate on the "access_token" field.
func AccessTokenEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAccessToken, v))
}

// AccessTokenNEQ applies the NEQ predicate on the "access_token" field.
func AccessTokenNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAccessToken, v))
}

// AccessTokenIn applies the In predicate on the "access_token" field.
func AccessTokenIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAccessToken, vs...))
}

// AccessTokenNotIn applies the NotIn predicate on the "access_token" field.
func AccessTokenNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAccessToken, vs...))
}

// AccessTokenGT applies the GT predicate on the "access_token" field.
func AccessTokenGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAccessToken, v))
}

// AccessTokenGTE applies the GTE predicate on the "access_token" field.
func AccessTokenGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAccessToken, v))
}

// AccessTokenLT applies the LT predicate on the "access_token" field.
func AccessTokenLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAccessToken, v))
}

// AccessTokenLTE applies the LTE predicate on the "access_token" field.
func AccessTokenLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAccessToken, v))
}

// AccessTokenContains applies the Contains predicate on the "access_token" field.
func AccessTokenContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAccessToken, v))
}

// AccessTokenHasPrefix applies the HasPrefix predicate on the "access_token" field.
func AccessTokenHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAccessToken, v))
}

// AccessTokenHasSuffix applies the HasSuffix predicate on the "access_token" field.
func AccessTokenHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAccessToken, v))
}

// AccessTokenEqualFold applies the EqualFold predicate on the "access_token" field.
func AccessTokenEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAccessToken, v))
}

// AccessTokenContainsFold applies the ContainsFold predicate on the "access_token" field.
func AccessTokenContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAccessToken, v))
}

// SyncIntervalMinutesEQ applies the EQ predicate on the "sync_interval_minutes" field.
func SyncIntervalMinutesEQ(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSyncIntervalMinutes, v))
}

// SyncIntervalMinutesNEQ applies the NEQ predicate on the "sync_interval_minutes" field.
func SyncIntervalMinutesNEQ(v int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldSyncIntervalMinutes, v))
}

// SyncIntervalMinutesIn applies the In predicate on the "sync_interval_minutes" field.
func SyncIntervalMinutesIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldSyncIntervalMinutes, vs...))
}

// SyncIntervalMinutesNotIn applies the NotIn predicate on the "sync_interval_minutes" field.
func SyncIntervalMinutesNotIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldSyncIntervalMinutes, vs...))
}

// SyncIntervalMinutesGT applies the GT predicate on the "sync_interval_minutes" field.
func SyncIntervalMinutesGT(v int) predicate.User {
	return predicate.User(sql.FieldGT(FieldSyncIntervalMinutes, v))
}

// SyncIntervalMinutesGTE applies the GTE predicate on the "sync_interval_minutes" field.
func SyncIntervalMinutesGTE(v int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldSyncIntervalMinutes, v))
}

// SyncIntervalMinutesLT applies the LT predicate on the "sync_interval_minutes" field.
func SyncIntervalMinutesLT(v int) predicate.User {
	return predicate.User(sql.FieldLT(FieldSyncIntervalMinutes, v))
}

// SyncIntervalMinutesLTE applies the LTE predicate on the "sync_interval_minutes" field.
func SyncIntervalMinutesLTE(v int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldSyncIntervalMinutes, v))
}

// UmamiURLEQ applies the EQ predicate on the "umami_url" field.
func UmamiURLEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUmamiURL, v))
}

// UmamiURLNEQ applies the NEQ predicate on the "umami_url" field.
func UmamiURLNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUmamiURL, v))
}

// UmamiURLIn applies the In predicate on the "umami_url" field.
func UmamiURLIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldUmamiURL, vs...))
}

// UmamiURLNotIn applies the NotIn predicate on the "umami_url" field.
func UmamiURLNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUmamiURL, vs...))
}

// UmamiURLGT applies the GT predicate on the "umami_url" field.
func UmamiURLGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldUmamiURL, v))
}

// UmamiURLGTE applies the GTE predicate on the "umami_url" field.
func UmamiURLGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUmamiURL, v))
}

// UmamiURLLT applies the LT predicate on the "umami_url" field.
func UmamiURLLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldUmamiURL, v))
}

// UmamiURLLTE applies the LTE predicate on the "umami_url" field.
func UmamiURLLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUmamiURL, v))
}

// UmamiURLContains applies the Contains predicate on the "umami_url" field.
func UmamiURLContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldUmamiURL, v))
}

// UmamiURLHasPrefix applies the HasPrefix predicate on the "umami_url" field.
func UmamiURLHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldUmamiURL, v))
}

// UmamiURLHasSuffix applies the HasSuffix predicate on the "umami_url" field.
func UmamiURLHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldUmamiURL, v))
}

// UmamiURLIsNil applies the IsNil predicate on the "umami_url" field.
func UmamiURLIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldUmamiURL))
}

// UmamiURLNotNil applies the NotNil predicate on the "umami_url" field.
func UmamiURLNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldUmamiURL))
}

// UmamiURLEqualFold applies the EqualFold predicate on the "umami_url" field.
func UmamiURLEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldUmamiURL, v))
}

// UmamiURLContainsFold applies the ContainsFold predicate on the "umami_url" field.
func UmamiURLContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldUmamiURL, v))
}

// UmamiSiteIDEQ applies the EQ predicate on the "umami_site_id" field.
func UmamiSiteIDEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUmamiSiteID, v))
}

// UmamiSiteIDNEQ applies the NEQ predicate on the "umami_site_id" field.
func UmamiSiteIDNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUmamiSiteID, v))
}

// UmamiSiteIDIn applies the In predicate on the "umami_site_id" field.
func UmamiSiteIDIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldUmamiSiteID, vs...))
}

// UmamiSiteIDNotIn applies the NotIn predicate on the "umami_site_id" field.
func UmamiSiteIDNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUmamiSiteID, vs...))
}

// UmamiSiteIDGT applies the GT predicate on the "umami_site_id" field.
func UmamiSiteIDGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldUmamiSiteID, v))
}

// UmamiSiteIDGTE applies the GTE predicate on the "umami_site_id" field.
func UmamiSiteIDGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUmamiSiteID, v))
}

// UmamiSiteIDLT applies the LT predicate on the "umami_site_id" field.
func UmamiSiteIDLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldUmamiSiteID, v))
}

// UmamiSiteIDLTE applies the LTE predicate on the "umami_site_id" field.
func UmamiSiteIDLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUmamiSiteID, v))
}

// UmamiSiteIDContains applies the Contains predicate on the "umami_site_id" field.
func UmamiSiteIDContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldUmamiSiteID, v))
}

// UmamiSiteIDHasPrefix applies the HasPrefix predicate on the "umami_site_id" field.
func UmamiSiteIDHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldUmamiSiteID, v))
}

// UmamiSiteIDHasSuffix applies the HasSuffix predicate on the "umami_site_id" field.
func UmamiSiteIDHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldUmamiSiteID, v))
}

// UmamiSiteIDIsNil applies the IsNil predicate on the "umami_site_id" field.
func UmamiSiteIDIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldUmamiSiteID))
}

// UmamiSiteIDNotNil applies the NotNil predicate on the "umami_site_id" field.
func UmamiSiteIDNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldUmamiSiteID))
}

// UmamiSiteIDEqualFold applies the EqualFold predicate on the "umami_site_id" field.
func UmamiSiteIDEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldUmamiSiteID, v))
}

// UmamiSiteIDContainsFold applies the ContainsFold predicate on the "umami_site_id" field.
func UmamiSiteIDContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldUmamiSiteID, v))
}

// IsAdminEQ applies the EQ predicate on the "is_admin" field.
func IsAdminEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsAdmin, v))
}

// IsAdminNEQ applies the NEQ predicate on the "is_admin" field.
func IsAdminNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldIsAdmin, v))
}

// SyncedAtEQ applies the EQ predicate on the "synced_at" field.
func SyncedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSyncedAt, v))
}

// SyncedAtNEQ applies the NEQ predicate on the "synced_at" field.
func SyncedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldSyncedAt, v))
}

// SyncedAtIn applies the In predicate on the "synced_at" field.
func SyncedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldSyncedAt, vs...))
}

// SyncedAtNotIn applies the NotIn predicate on the "synced_at" field.
func SyncedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldSyncedAt, vs...))
}

// SyncedAtGT applies the GT predicate on the "synced_at" field.
func SyncedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldSyncedAt, v))
}

// SyncedAtGTE applies the GTE predicate on the "synced_at" field.
func SyncedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldSyncedAt, v))
}

// SyncedAtLT applies the LT predicate on the "synced_at" field.
func SyncedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldSyncedAt, v))
}

// SyncedAtLTE applies the LTE predicate on the "synced_at" field.
func SyncedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldSyncedAt, v))
}

// SyncedAtIsNil applies the IsNil predicate on the "synced_at" field.
func SyncedAtIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldSyncedAt))
}

// SyncedAtNotNil applies the NotNil predicate on the "synced_at" field.
func SyncedAtNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldSyncedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatedAt, v))
}

// ForgejoIDEQ applies the EQ predicate on the "forgejo_id" field.
func ForgejoIDEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldForgejoID, v))
}

// ForgejoIDNEQ applies the NEQ predicate on the "forgejo_id" field.
func ForgejoIDNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldForgejoID, v))
}

// ForgejoIDIn applies the In predicate on the "forgejo_id" field.
func ForgejoIDIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldForgejoID, vs...))
}

// ForgejoIDNotIn applies the NotIn predicate on the "forgejo_id" field.
func ForgejoIDNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldForgejoID, vs...))
}

// ForgejoIDGT applies the GT predicate on the "forgejo_id" field.
func ForgejoIDGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldForgejoID, v))
}

// ForgejoIDGTE applies the GTE predicate on the "forgejo_id" field.
func ForgejoIDGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldForgejoID, v))
}

// ForgejoIDLT applies the LT predicate on the "forgejo_id" field.
func ForgejoIDLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldForgejoID, v))
}

// ForgejoIDLTE applies the LTE predicate on the "forgejo_id" field.
func ForgejoIDLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldForgejoID, v))
}

// ForgejoIDIsNil applies the IsNil predicate on the "forgejo_id" field.
func ForgejoIDIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldForgejoID))
}

// ForgejoIDNotNil applies the NotNil predicate on the "forgejo_id" field.
func ForgejoIDNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldForgejoID))
}

// ForgejoLoginEQ applies the EQ predicate on the "forgejo_login" field.
func ForgejoLoginEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldForgejoLogin, v))
}

// ForgejoLoginNEQ applies the NEQ predicate on the "forgejo_login" field.
func ForgejoLoginNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldForgejoLogin, v))
}

// ForgejoLoginIn applies the In predicate on the "forgejo_login" field.
func ForgejoLoginIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldForgejoLogin, vs...))
}

// ForgejoLoginNotIn applies the NotIn predicate on the "forgejo_login" field.
func ForgejoLoginNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldForgejoLogin, vs...))
}

// ForgejoLoginGT applies the GT predicate on the "forgejo_login" field.
func ForgejoLoginGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldForgejoLogin, v))
}

// ForgejoLoginGTE applies the GTE predicate on the "forgejo_login" field.
func ForgejoLoginGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldForgejoLogin, v))
}

// ForgejoLoginLT applies the LT predicate on the "forgejo_login" field.
func ForgejoLoginLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldForgejoLogin, v))
}

// ForgejoLoginLTE applies the LTE predicate on the "forgejo_login" field.
func ForgejoLoginLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldForgejoLogin, v))
}

// ForgejoLoginContains applies the Contains predicate on the "forgejo_login" field.
func ForgejoLoginContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldForgejoLogin, v))
}

// ForgejoLoginHasPrefix applies the HasPrefix predicate on the "forgejo_login" field.
func ForgejoLoginHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldForgejoLogin, v))
}

// ForgejoLoginHasSuffix applies the HasSuffix predicate on the "forgejo_login" field.
func ForgejoLoginHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldForgejoLogin, v))
}

// ForgejoLoginIsNil applies the IsNil predicate on the "forgejo_login" field.
func ForgejoLoginIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldForgejoLogin))
}

// ForgejoLoginNotNil applies the NotNil predicate on the "forgejo_login" field.
func ForgejoLoginNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldForgejoLogin))
}

// ForgejoLoginEqualFold applies the EqualFold predicate on the "forgejo_login" field.
func ForgejoLoginEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldForgejoLogin, v))
}

// ForgejoLoginContainsFold applies the ContainsFold predicate on the "forgejo_login" field.
func ForgejoLoginContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldForgejoLogin, v))
}

// ForgejoAvatarURLEQ applies the EQ predicate on the "forgejo_avatar_url" field.
func ForgejoAvatarURLEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldForgejoAvatarURL, v))
}

// ForgejoAvatarURLNEQ applies the NEQ predicate on the "forgejo_avatar_url" field.
func ForgejoAvatarURLNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldForgejoAvatarURL, v))
}

// ForgejoAvatarURLIn applies the In predicate on the "forgejo_avatar_url" field.
func ForgejoAvatarURLIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldForgejoAvatarURL, vs...))
}

// ForgejoAvatarURLNotIn applies the NotIn predicate on the "forgejo_avatar_url" field.
func ForgejoAvatarURLNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldForgejoAvatarURL, vs...))
}

// ForgejoAvatarURLGT applies the GT predicate on the "forgejo_avatar_url" field.
func ForgejoAvatarURLGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldForgejoAvatarURL, v))
}

// ForgejoAvatarURLGTE applies the GTE predicate on the "forgejo_avatar_url" field.
func ForgejoAvatarURLGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldForgejoAvatarURL, v))
}

// ForgejoAvatarURLLT applies the LT predicate on the "forgejo_avatar_url" field.
func ForgejoAvatarURLLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldForgejoAvatarURL, v))
}

// ForgejoAvatarURLLTE applies the LTE predicate on the "forgejo_avatar_url" field.
func ForgejoAvatarURLLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldForgejoAvatarURL, v))
}

// ForgejoAvatarURLContains applies the Contains predicate on the "forgejo_avatar_url" field.
func ForgejoAvatarURLContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldForgejoAvatarURL, v))
}

// ForgejoAvatarURLHasPrefix applies the HasPrefix predicate on the "forgejo_avatar_url" field.
func ForgejoAvatarURLHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldForgejoAvatarURL, v))
}

// ForgejoAvatarURLHasSuffix applies the HasSuffix predicate on the "forgejo_avatar_url" field.
func ForgejoAvatarURLHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldForgejoAvatarURL, v))
}

// ForgejoAvatarURLIsNil applies the IsNil predicate on the "forgejo_avatar_url" field.
func ForgejoAvatarURLIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldForgejoAvatarURL))
}

// ForgejoAvatarURLNotNil applies the NotNil predicate on the "forgejo_avatar_url" field.
func ForgejoAvatarURLNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldForgejoAvatarURL))
}

// ForgejoAvatarURLEqualFold applies the EqualFold predicate on the "forgejo_avatar_url" field.
func ForgejoAvatarURLEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldForgejoAvatarURL, v))
}

// ForgejoAvatarURLContainsFold applies the ContainsFold predicate on the "forgejo_avatar_url" field.
func ForgejoAvatarURLContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldForgejoAvatarURL, v))
}

// ForgejoNameEQ applies the EQ predicate on the "forgejo_name" field.
func ForgejoNameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldForgejoName, v))
}

// ForgejoNameNEQ applies the NEQ predicate on the "forgejo_name" field.
func ForgejoNameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldForgejoName, v))
}

// ForgejoNameIn applies the In predicate on the "forgejo_name" field.
func ForgejoNameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldForgejoName, vs...))
}

// ForgejoNameNotIn applies the NotIn predicate on the "forgejo_name" field.
func ForgejoNameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldForgejoName, vs...))
}

// ForgejoNameGT applies the GT predicate on the "forgejo_name" field.
func ForgejoNameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldForgejoName, v))
}

// ForgejoNameGTE applies the GTE predicate on the "forgejo_name" field.
func ForgejoNameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldForgejoName, v))
}

// ForgejoNameLT applies the LT predicate on the "forgejo_name" field.
func ForgejoNameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldForgejoName, v))
}

// ForgejoNameLTE applies the LTE predicate on the "forgejo_name" field.
func ForgejoNameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldForgejoName, v))
}

// ForgejoNameContains applies the Contains predicate on the "forgejo_name" field.
func ForgejoNameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldForgejoName, v))
}

// ForgejoNameHasPrefix applies the HasPrefix predicate on the "forgejo_name" field.
func ForgejoNameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldForgejoName, v))
}

// ForgejoNameHasSuffix applies the HasSuffix predicate on the "forgejo_name" field.
func ForgejoNameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldForgejoName, v))
}

// ForgejoNameIsNil applies the IsNil predicate on the "forgejo_name" field.
func ForgejoNameIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldForgejoName))
}

// ForgejoNameNotNil applies the NotNil predicate on the "forgejo_name" field.
func ForgejoNameNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldForgejoName))
}

// ForgejoNameEqualFold applies the EqualFold predicate on the "forgejo_name" field.
func ForgejoNameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldForgejoName, v))
}

// ForgejoNameContainsFold applies the ContainsFold predicate on the "forgejo_name" field.
func ForgejoNameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldForgejoName, v))
}

// ForgejoAccessTokenEQ applies the EQ predicate on the "forgejo_access_token" field.
func ForgejoAccessTokenEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldForgejoAccessToken, v))
}

// ForgejoAccessTokenNEQ applies the NEQ predicate on the "forgejo_access_token" field.
func ForgejoAccessTokenNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldForgejoAccessToken, v))
}

// ForgejoAccessTokenIn applies the In predicate on the "forgejo_access_token" field.
func ForgejoAccessTokenIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldForgejoAccessToken, vs...))
}

// ForgejoAccessTokenNotIn applies the NotIn predicate on the "forgejo_access_token" field.
func ForgejoAccessTokenNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldForgejoAccessToken, vs...))
}

// ForgejoAccessTokenGT applies the GT predicate on the "forgejo_access_token" field.
func ForgejoAccessTokenGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldForgejoAccessToken, v))
}

// ForgejoAccessTokenGTE applies the GTE predicate on the "forgejo_access_token" field.
func ForgejoAccessTokenGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldForgejoAccessToken, v))
}

// ForgejoAccessTokenLT applies the LT predicate on the "forgejo_access_token" field.
func ForgejoAccessTokenLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldForgejoAccessToken, v))
}

// ForgejoAccessTokenLTE applies the LTE predicate on the "forgejo_access_token" field.
func ForgejoAccessTokenLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldForgejoAccessToken, v))
}

// ForgejoAccessTokenContains applies the Contains predicate on the "forgejo_access_token" field.
func ForgejoAccessTokenContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldForgejoAccessToken, v))
}

// ForgejoAccessTokenHasPrefix applies the HasPrefix predicate on the "forgejo_access_token" field.
func ForgejoAccessTokenHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldForgejoAccessToken, v))
}

// ForgejoAccessTokenHasSuffix applies the HasSuffix predicate on the "forgejo_access_token" field.
func ForgejoAccessTokenHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldForgejoAccessToken, v))
}

// ForgejoAccessTokenIsNil applies the IsNil predicate on the "forgejo_access_token" field.
func ForgejoAccessTokenIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldForgejoAccessToken))
}

// ForgejoAccessTokenNotNil applies the NotNil predicate on the "forgejo_access_token" field.
func ForgejoAccessTokenNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldForgejoAccessToken))
}

// ForgejoAccessTokenEqualFold applies the EqualFold predicate on the "forgejo_access_token" field.
func ForgejoAccessTokenEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldForgejoAccessToken, v))
}

// ForgejoAccessTokenContainsFold applies the ContainsFold predicate on the "forgejo_access_token" field.
func ForgejoAccessTokenContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldForgejoAccessToken, v))
}

// ForgejoURLEQ applies the EQ predicate on the "forgejo_url" field.
func ForgejoURLEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldForgejoURL, v))
}

// ForgejoURLNEQ applies the NEQ predicate on the "forgejo_url" field.
func ForgejoURLNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldForgejoURL, v))
}

// ForgejoURLIn applies the In predicate on the "forgejo_url" field.
func ForgejoURLIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldForgejoURL, vs...))
}

// ForgejoURLNotIn applies the NotIn predicate on the "forgejo_url" field.
func ForgejoURLNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldForgejoURL, vs...))
}

// ForgejoURLGT applies the GT predicate on the "forgejo_url" field.
func ForgejoURLGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldForgejoURL, v))
}

// ForgejoURLGTE applies the GTE predicate on the "forgejo_url" field.
func ForgejoURLGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldForgejoURL, v))
}

// ForgejoURLLT applies the LT predicate on the "forgejo_url" field.
func ForgejoURLLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldForgejoURL, v))
}

// ForgejoURLLTE applies the LTE predicate on the "forgejo_url" field.
func ForgejoURLLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldForgejoURL, v))
}

// ForgejoURLContains applies the Contains predicate on the "forgejo_url" field.
func ForgejoURLContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldForgejoURL, v))
}

// ForgejoURLHasPrefix applies the HasPrefix predicate on the "forgejo_url" field.
func ForgejoURLHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldForgejoURL, v))
}

// ForgejoURLHasSuffix applies the HasSuffix predicate on the "forgejo_url" field.
func ForgejoURLHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldForgejoURL, v))
}

// ForgejoURLIsNil applies the IsNil predicate on the "forgejo_url" field.
func ForgejoURLIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldForgejoURL))
}

// ForgejoURLNotNil applies the NotNil predicate on the "forgejo_url" field.
func ForgejoURLNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldForgejoURL))
}

// ForgejoURLEqualFold applies the EqualFold predicate on the "forgejo_url" field.
func ForgejoURLEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldForgejoURL, v))
}

// ForgejoURLContainsFold applies the ContainsFold predicate on the "forgejo_url" field.
func ForgejoURLContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldForgejoURL, v))
}

// DismissedForgejoWarningForEQ applies the EQ predicate on the "dismissed_forgejo_warning_for" field.
func DismissedForgejoWarningForEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDismissedForgejoWarningFor, v))
}

// DismissedForgejoWarningForNEQ applies the NEQ predicate on the "dismissed_forgejo_warning_for" field.
func DismissedForgejoWarningForNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldDismissedForgejoWarningFor, v))
}

// DismissedForgejoWarningForIn applies the In predicate on the "dismissed_forgejo_warning_for" field.
func DismissedForgejoWarningForIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldDismissedForgejoWarningFor, vs...))
}

// DismissedForgejoWarningForNotIn applies the NotIn predicate on the "dismissed_forgejo_warning_for" field.
func DismissedForgejoWarningForNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldDismissedForgejoWarningFor, vs...))
}

// DismissedForgejoWarningForGT applies the GT predicate on the "dismissed_forgejo_warning_for" field.
func DismissedForgejoWarningForGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldDismissedForgejoWarningFor, v))
}

// DismissedForgejoWarningForGTE applies the GTE predicate on the "dismissed_forgejo_warning_for" field.
func DismissedForgejoWarningForGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldDismissedForgejoWarningFor, v))
}

// DismissedForgejoWarningForLT applies the LT predicate on the "dismissed_forgejo_warning_for" field.
func DismissedForgejoWarningForLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldDismissedForgejoWarningFor, v))
}

// DismissedForgejoWarningForLTE applies the LTE predicate on the "dismissed_forgejo_warning_for" field.
func DismissedForgejoWarningForLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldDismissedForgejoWarningFor, v))
}

// DismissedForgejoWarningForContains applies the Contains predicate on the "dismissed_forgejo_warning_for" field.
func DismissedForgejoWarningForContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldDismissedForgejoWarningFor, v))
}

// DismissedForgejoWarningForHasPrefix applies the HasPrefix predicate on the "dismissed_forgejo_warning_for" field.
func DismissedForgejoWarningForHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldDismissedForgejoWarningFor, v))
}

// DismissedForgejoWarningForHasSuffix applies the HasSuffix predicate on the "dismissed_forgejo_warning_for" field.
func DismissedForgejoWarningForHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldDismissedForgejoWarningFor, v))
}

// DismissedForgejoWarningForIsNil applies the IsNil predicate on the "dismissed_forgejo_warning_for" field.
func DismissedForgejoWarningForIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldDismissedForgejoWarningFor))
}

// DismissedForgejoWarningForNotNil applies the NotNil predicate on the "dismissed_forgejo_warning_for" field.
func DismissedForgejoWarningForNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldDismissedForgejoWarningFor))
}

// DismissedForgejoWarningForEqualFold applies the EqualFold predicate on the "dismissed_forgejo_warning_for" field.
func DismissedForgejoWarningForEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldDismissedForgejoWarningFor, v))
}

// DismissedForgejoWarningForContainsFold applies the ContainsFold predicate on the "dismissed_forgejo_warning_for" field.
func DismissedForgejoWarningForContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldDismissedForgejoWarningFor, v))
}

// HasRepositories applies the HasEdge predicate on the "repositories" edge.
func HasRepositories() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RepositoriesTable, RepositoriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRepositoriesWith applies the HasEdge predicate on the "repositories" edge with a given conditions (other predicates).
func HasRepositoriesWith(preds ...predicate.Repository) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRepositoriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
