// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AdminConfig is the predicate function for adminconfig builders.
type AdminConfig func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Repository is the predicate function for repository builders.
type Repository func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
